//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.34011
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LazyAtHome.Service.SMS.JianZhouService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://service.nineorange.com", ConfigurationName="JianZhouService.BusinessService")]
    public interface BusinessService {
        
        // CODEGEN: 命名空间 http://service.nineorange.com 的元素名称 account 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        LazyAtHome.Service.SMS.JianZhouService.getReceivedMsgResponse getReceivedMsg(LazyAtHome.Service.SMS.JianZhouService.getReceivedMsg request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<LazyAtHome.Service.SMS.JianZhouService.getReceivedMsgResponse> getReceivedMsgAsync(LazyAtHome.Service.SMS.JianZhouService.getReceivedMsg request);
        
        // CODEGEN: 命名空间 http://service.nineorange.com 的元素名称 account 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        LazyAtHome.Service.SMS.JianZhouService.sendBatchMessageTimelyExtResponse sendBatchMessageTimelyExt(LazyAtHome.Service.SMS.JianZhouService.sendBatchMessageTimelyExt request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<LazyAtHome.Service.SMS.JianZhouService.sendBatchMessageTimelyExtResponse> sendBatchMessageTimelyExtAsync(LazyAtHome.Service.SMS.JianZhouService.sendBatchMessageTimelyExt request);
        
        // CODEGEN: 命名空间 http://service.nineorange.com 的元素名称 account 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        LazyAtHome.Service.SMS.JianZhouService.sendPersonalMessagesResponse sendPersonalMessages(LazyAtHome.Service.SMS.JianZhouService.sendPersonalMessages request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<LazyAtHome.Service.SMS.JianZhouService.sendPersonalMessagesResponse> sendPersonalMessagesAsync(LazyAtHome.Service.SMS.JianZhouService.sendPersonalMessages request);
        
        // CODEGEN: 命名空间 http://service.nineorange.com 的元素名称 account 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        LazyAtHome.Service.SMS.JianZhouService.modifyPasswordResponse modifyPassword(LazyAtHome.Service.SMS.JianZhouService.modifyPassword request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<LazyAtHome.Service.SMS.JianZhouService.modifyPasswordResponse> modifyPasswordAsync(LazyAtHome.Service.SMS.JianZhouService.modifyPassword request);
        
        // CODEGEN: 命名空间 http://service.nineorange.com 的元素名称 account 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        LazyAtHome.Service.SMS.JianZhouService.getReceiptResponse getReceipt(LazyAtHome.Service.SMS.JianZhouService.getReceipt request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<LazyAtHome.Service.SMS.JianZhouService.getReceiptResponse> getReceiptAsync(LazyAtHome.Service.SMS.JianZhouService.getReceipt request);
        
        // CODEGEN: 命名空间 http://service.nineorange.com 的元素名称 account 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        LazyAtHome.Service.SMS.JianZhouService.sendBatchMessageResponse sendBatchMessage(LazyAtHome.Service.SMS.JianZhouService.sendBatchMessage request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<LazyAtHome.Service.SMS.JianZhouService.sendBatchMessageResponse> sendBatchMessageAsync(LazyAtHome.Service.SMS.JianZhouService.sendBatchMessage request);
        
        // CODEGEN: 命名空间 http://service.nineorange.com 的元素名称 account 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        LazyAtHome.Service.SMS.JianZhouService.validateUserResponse validateUser(LazyAtHome.Service.SMS.JianZhouService.validateUser request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<LazyAtHome.Service.SMS.JianZhouService.validateUserResponse> validateUserAsync(LazyAtHome.Service.SMS.JianZhouService.validateUser request);
        
        // CODEGEN: 命名空间 http://service.nineorange.com 的元素名称 account 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        LazyAtHome.Service.SMS.JianZhouService.sendMessageResponse sendMessage(LazyAtHome.Service.SMS.JianZhouService.sendMessage request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<LazyAtHome.Service.SMS.JianZhouService.sendMessageResponse> sendMessageAsync(LazyAtHome.Service.SMS.JianZhouService.sendMessage request);
        
        // CODEGEN: 命名空间 http://service.nineorange.com 的元素名称 account 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        LazyAtHome.Service.SMS.JianZhouService.sendTimelyMessageResponse sendTimelyMessage(LazyAtHome.Service.SMS.JianZhouService.sendTimelyMessage request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<LazyAtHome.Service.SMS.JianZhouService.sendTimelyMessageResponse> sendTimelyMessageAsync(LazyAtHome.Service.SMS.JianZhouService.sendTimelyMessage request);
        
        // CODEGEN: 命名空间 http://service.nineorange.com 的元素名称 account 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        LazyAtHome.Service.SMS.JianZhouService.sendMmsMessagesResponse sendMmsMessages(LazyAtHome.Service.SMS.JianZhouService.sendMmsMessages request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<LazyAtHome.Service.SMS.JianZhouService.sendMmsMessagesResponse> sendMmsMessagesAsync(LazyAtHome.Service.SMS.JianZhouService.sendMmsMessages request);
        
        // CODEGEN: 命名空间 http://service.nineorange.com 的元素名称 account 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        LazyAtHome.Service.SMS.JianZhouService.gxmtResponse gxmt(LazyAtHome.Service.SMS.JianZhouService.gxmt request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<LazyAtHome.Service.SMS.JianZhouService.gxmtResponse> gxmtAsync(LazyAtHome.Service.SMS.JianZhouService.gxmt request);
        
        // CODEGEN: 命名空间 http://service.nineorange.com 的元素名称 account 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        LazyAtHome.Service.SMS.JianZhouService.getUserInfoResponse getUserInfo(LazyAtHome.Service.SMS.JianZhouService.getUserInfo request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<LazyAtHome.Service.SMS.JianZhouService.getUserInfoResponse> getUserInfoAsync(LazyAtHome.Service.SMS.JianZhouService.getUserInfo request);
        
        // CODEGEN: 命名空间 http://service.nineorange.com 的元素名称 account 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        LazyAtHome.Service.SMS.JianZhouService.sendAudioResponse sendAudio(LazyAtHome.Service.SMS.JianZhouService.sendAudio request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<LazyAtHome.Service.SMS.JianZhouService.sendAudioResponse> sendAudioAsync(LazyAtHome.Service.SMS.JianZhouService.sendAudio request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getReceivedMsg {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getReceivedMsg", Namespace="http://service.nineorange.com", Order=0)]
        public LazyAtHome.Service.SMS.JianZhouService.getReceivedMsgBody Body;
        
        public getReceivedMsg() {
        }
        
        public getReceivedMsg(LazyAtHome.Service.SMS.JianZhouService.getReceivedMsgBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://service.nineorange.com")]
    public partial class getReceivedMsgBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string account;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int param;
        
        public getReceivedMsgBody() {
        }
        
        public getReceivedMsgBody(string account, string password, int param) {
            this.account = account;
            this.password = password;
            this.param = param;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getReceivedMsgResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getReceivedMsgResponse", Namespace="http://service.nineorange.com", Order=0)]
        public LazyAtHome.Service.SMS.JianZhouService.getReceivedMsgResponseBody Body;
        
        public getReceivedMsgResponse() {
        }
        
        public getReceivedMsgResponse(LazyAtHome.Service.SMS.JianZhouService.getReceivedMsgResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://service.nineorange.com")]
    public partial class getReceivedMsgResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string getReceivedMsgReturn;
        
        public getReceivedMsgResponseBody() {
        }
        
        public getReceivedMsgResponseBody(string getReceivedMsgReturn) {
            this.getReceivedMsgReturn = getReceivedMsgReturn;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class sendBatchMessageTimelyExt {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="sendBatchMessageTimelyExt", Namespace="http://service.nineorange.com", Order=0)]
        public LazyAtHome.Service.SMS.JianZhouService.sendBatchMessageTimelyExtBody Body;
        
        public sendBatchMessageTimelyExt() {
        }
        
        public sendBatchMessageTimelyExt(LazyAtHome.Service.SMS.JianZhouService.sendBatchMessageTimelyExtBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://service.nineorange.com")]
    public partial class sendBatchMessageTimelyExtBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string account;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string sendDateTime;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string destmobile;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string msgText;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string ext;
        
        public sendBatchMessageTimelyExtBody() {
        }
        
        public sendBatchMessageTimelyExtBody(string account, string password, string sendDateTime, string destmobile, string msgText, string ext) {
            this.account = account;
            this.password = password;
            this.sendDateTime = sendDateTime;
            this.destmobile = destmobile;
            this.msgText = msgText;
            this.ext = ext;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class sendBatchMessageTimelyExtResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="sendBatchMessageTimelyExtResponse", Namespace="http://service.nineorange.com", Order=0)]
        public LazyAtHome.Service.SMS.JianZhouService.sendBatchMessageTimelyExtResponseBody Body;
        
        public sendBatchMessageTimelyExtResponse() {
        }
        
        public sendBatchMessageTimelyExtResponse(LazyAtHome.Service.SMS.JianZhouService.sendBatchMessageTimelyExtResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://service.nineorange.com")]
    public partial class sendBatchMessageTimelyExtResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int @return;
        
        public sendBatchMessageTimelyExtResponseBody() {
        }
        
        public sendBatchMessageTimelyExtResponseBody(int @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class sendPersonalMessages {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="sendPersonalMessages", Namespace="http://service.nineorange.com", Order=0)]
        public LazyAtHome.Service.SMS.JianZhouService.sendPersonalMessagesBody Body;
        
        public sendPersonalMessages() {
        }
        
        public sendPersonalMessages(LazyAtHome.Service.SMS.JianZhouService.sendPersonalMessagesBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://service.nineorange.com")]
    public partial class sendPersonalMessagesBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string account;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string destMobiles;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string msgContents;
        
        public sendPersonalMessagesBody() {
        }
        
        public sendPersonalMessagesBody(string account, string password, string destMobiles, string msgContents) {
            this.account = account;
            this.password = password;
            this.destMobiles = destMobiles;
            this.msgContents = msgContents;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class sendPersonalMessagesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="sendPersonalMessagesResponse", Namespace="http://service.nineorange.com", Order=0)]
        public LazyAtHome.Service.SMS.JianZhouService.sendPersonalMessagesResponseBody Body;
        
        public sendPersonalMessagesResponse() {
        }
        
        public sendPersonalMessagesResponse(LazyAtHome.Service.SMS.JianZhouService.sendPersonalMessagesResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://service.nineorange.com")]
    public partial class sendPersonalMessagesResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int sendPersonalMessagesReturn;
        
        public sendPersonalMessagesResponseBody() {
        }
        
        public sendPersonalMessagesResponseBody(int sendPersonalMessagesReturn) {
            this.sendPersonalMessagesReturn = sendPersonalMessagesReturn;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class modifyPassword {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="modifyPassword", Namespace="http://service.nineorange.com", Order=0)]
        public LazyAtHome.Service.SMS.JianZhouService.modifyPasswordBody Body;
        
        public modifyPassword() {
        }
        
        public modifyPassword(LazyAtHome.Service.SMS.JianZhouService.modifyPasswordBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://service.nineorange.com")]
    public partial class modifyPasswordBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string account;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string oldPassword;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string newPassword;
        
        public modifyPasswordBody() {
        }
        
        public modifyPasswordBody(string account, string oldPassword, string newPassword) {
            this.account = account;
            this.oldPassword = oldPassword;
            this.newPassword = newPassword;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class modifyPasswordResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="modifyPasswordResponse", Namespace="http://service.nineorange.com", Order=0)]
        public LazyAtHome.Service.SMS.JianZhouService.modifyPasswordResponseBody Body;
        
        public modifyPasswordResponse() {
        }
        
        public modifyPasswordResponse(LazyAtHome.Service.SMS.JianZhouService.modifyPasswordResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://service.nineorange.com")]
    public partial class modifyPasswordResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int modifyPasswordReturn;
        
        public modifyPasswordResponseBody() {
        }
        
        public modifyPasswordResponseBody(int modifyPasswordReturn) {
            this.modifyPasswordReturn = modifyPasswordReturn;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getReceipt {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getReceipt", Namespace="http://service.nineorange.com", Order=0)]
        public LazyAtHome.Service.SMS.JianZhouService.getReceiptBody Body;
        
        public getReceipt() {
        }
        
        public getReceipt(LazyAtHome.Service.SMS.JianZhouService.getReceiptBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://service.nineorange.com")]
    public partial class getReceiptBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string account;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int taskID;
        
        public getReceiptBody() {
        }
        
        public getReceiptBody(string account, string password, int taskID) {
            this.account = account;
            this.password = password;
            this.taskID = taskID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getReceiptResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getReceiptResponse", Namespace="http://service.nineorange.com", Order=0)]
        public LazyAtHome.Service.SMS.JianZhouService.getReceiptResponseBody Body;
        
        public getReceiptResponse() {
        }
        
        public getReceiptResponse(LazyAtHome.Service.SMS.JianZhouService.getReceiptResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://service.nineorange.com")]
    public partial class getReceiptResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string getReceiptReturn;
        
        public getReceiptResponseBody() {
        }
        
        public getReceiptResponseBody(string getReceiptReturn) {
            this.getReceiptReturn = getReceiptReturn;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class sendBatchMessage {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="sendBatchMessage", Namespace="http://service.nineorange.com", Order=0)]
        public LazyAtHome.Service.SMS.JianZhouService.sendBatchMessageBody Body;
        
        public sendBatchMessage() {
        }
        
        public sendBatchMessage(LazyAtHome.Service.SMS.JianZhouService.sendBatchMessageBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://service.nineorange.com")]
    public partial class sendBatchMessageBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string account;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string destmobile;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string msgText;
        
        public sendBatchMessageBody() {
        }
        
        public sendBatchMessageBody(string account, string password, string destmobile, string msgText) {
            this.account = account;
            this.password = password;
            this.destmobile = destmobile;
            this.msgText = msgText;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class sendBatchMessageResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="sendBatchMessageResponse", Namespace="http://service.nineorange.com", Order=0)]
        public LazyAtHome.Service.SMS.JianZhouService.sendBatchMessageResponseBody Body;
        
        public sendBatchMessageResponse() {
        }
        
        public sendBatchMessageResponse(LazyAtHome.Service.SMS.JianZhouService.sendBatchMessageResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://service.nineorange.com")]
    public partial class sendBatchMessageResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int sendBatchMessageReturn;
        
        public sendBatchMessageResponseBody() {
        }
        
        public sendBatchMessageResponseBody(int sendBatchMessageReturn) {
            this.sendBatchMessageReturn = sendBatchMessageReturn;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class validateUser {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="validateUser", Namespace="http://service.nineorange.com", Order=0)]
        public LazyAtHome.Service.SMS.JianZhouService.validateUserBody Body;
        
        public validateUser() {
        }
        
        public validateUser(LazyAtHome.Service.SMS.JianZhouService.validateUserBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://service.nineorange.com")]
    public partial class validateUserBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string account;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        public validateUserBody() {
        }
        
        public validateUserBody(string account, string password) {
            this.account = account;
            this.password = password;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class validateUserResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="validateUserResponse", Namespace="http://service.nineorange.com", Order=0)]
        public LazyAtHome.Service.SMS.JianZhouService.validateUserResponseBody Body;
        
        public validateUserResponse() {
        }
        
        public validateUserResponse(LazyAtHome.Service.SMS.JianZhouService.validateUserResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://service.nineorange.com")]
    public partial class validateUserResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int validateUserReturn;
        
        public validateUserResponseBody() {
        }
        
        public validateUserResponseBody(int validateUserReturn) {
            this.validateUserReturn = validateUserReturn;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class sendMessage {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="sendMessage", Namespace="http://service.nineorange.com", Order=0)]
        public LazyAtHome.Service.SMS.JianZhouService.sendMessageBody Body;
        
        public sendMessage() {
        }
        
        public sendMessage(LazyAtHome.Service.SMS.JianZhouService.sendMessageBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://service.nineorange.com")]
    public partial class sendMessageBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string account;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string destmobile;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string msgText;
        
        public sendMessageBody() {
        }
        
        public sendMessageBody(string account, string password, string destmobile, string msgText) {
            this.account = account;
            this.password = password;
            this.destmobile = destmobile;
            this.msgText = msgText;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class sendMessageResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="sendMessageResponse", Namespace="http://service.nineorange.com", Order=0)]
        public LazyAtHome.Service.SMS.JianZhouService.sendMessageResponseBody Body;
        
        public sendMessageResponse() {
        }
        
        public sendMessageResponse(LazyAtHome.Service.SMS.JianZhouService.sendMessageResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://service.nineorange.com")]
    public partial class sendMessageResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int sendMessageReturn;
        
        public sendMessageResponseBody() {
        }
        
        public sendMessageResponseBody(int sendMessageReturn) {
            this.sendMessageReturn = sendMessageReturn;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class sendTimelyMessage {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="sendTimelyMessage", Namespace="http://service.nineorange.com", Order=0)]
        public LazyAtHome.Service.SMS.JianZhouService.sendTimelyMessageBody Body;
        
        public sendTimelyMessage() {
        }
        
        public sendTimelyMessage(LazyAtHome.Service.SMS.JianZhouService.sendTimelyMessageBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://service.nineorange.com")]
    public partial class sendTimelyMessageBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string account;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string sendDateTime;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string destmobile;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string msgText;
        
        public sendTimelyMessageBody() {
        }
        
        public sendTimelyMessageBody(string account, string password, string sendDateTime, string destmobile, string msgText) {
            this.account = account;
            this.password = password;
            this.sendDateTime = sendDateTime;
            this.destmobile = destmobile;
            this.msgText = msgText;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class sendTimelyMessageResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="sendTimelyMessageResponse", Namespace="http://service.nineorange.com", Order=0)]
        public LazyAtHome.Service.SMS.JianZhouService.sendTimelyMessageResponseBody Body;
        
        public sendTimelyMessageResponse() {
        }
        
        public sendTimelyMessageResponse(LazyAtHome.Service.SMS.JianZhouService.sendTimelyMessageResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://service.nineorange.com")]
    public partial class sendTimelyMessageResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int sendTimelyMessageReturn;
        
        public sendTimelyMessageResponseBody() {
        }
        
        public sendTimelyMessageResponseBody(int sendTimelyMessageReturn) {
            this.sendTimelyMessageReturn = sendTimelyMessageReturn;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class sendMmsMessages {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="sendMmsMessages", Namespace="http://service.nineorange.com", Order=0)]
        public LazyAtHome.Service.SMS.JianZhouService.sendMmsMessagesBody Body;
        
        public sendMmsMessages() {
        }
        
        public sendMmsMessages(LazyAtHome.Service.SMS.JianZhouService.sendMmsMessagesBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://service.nineorange.com")]
    public partial class sendMmsMessagesBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string account;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string phones;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string mmsString;
        
        public sendMmsMessagesBody() {
        }
        
        public sendMmsMessagesBody(string account, string password, string phones, string mmsString) {
            this.account = account;
            this.password = password;
            this.phones = phones;
            this.mmsString = mmsString;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class sendMmsMessagesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="sendMmsMessagesResponse", Namespace="http://service.nineorange.com", Order=0)]
        public LazyAtHome.Service.SMS.JianZhouService.sendMmsMessagesResponseBody Body;
        
        public sendMmsMessagesResponse() {
        }
        
        public sendMmsMessagesResponse(LazyAtHome.Service.SMS.JianZhouService.sendMmsMessagesResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://service.nineorange.com")]
    public partial class sendMmsMessagesResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int sendMmsMessagesReturn;
        
        public sendMmsMessagesResponseBody() {
        }
        
        public sendMmsMessagesResponseBody(int sendMmsMessagesReturn) {
            this.sendMmsMessagesReturn = sendMmsMessagesReturn;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class gxmt {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="gxmt", Namespace="http://service.nineorange.com", Order=0)]
        public LazyAtHome.Service.SMS.JianZhouService.gxmtBody Body;
        
        public gxmt() {
        }
        
        public gxmt(LazyAtHome.Service.SMS.JianZhouService.gxmtBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://service.nineorange.com")]
    public partial class gxmtBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string account;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string sendDateTime;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string destmobiles;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string msgTexts;
        
        public gxmtBody() {
        }
        
        public gxmtBody(string account, string password, string sendDateTime, string destmobiles, string msgTexts) {
            this.account = account;
            this.password = password;
            this.sendDateTime = sendDateTime;
            this.destmobiles = destmobiles;
            this.msgTexts = msgTexts;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class gxmtResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="gxmtResponse", Namespace="http://service.nineorange.com", Order=0)]
        public LazyAtHome.Service.SMS.JianZhouService.gxmtResponseBody Body;
        
        public gxmtResponse() {
        }
        
        public gxmtResponse(LazyAtHome.Service.SMS.JianZhouService.gxmtResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://service.nineorange.com")]
    public partial class gxmtResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int gxmtReturn;
        
        public gxmtResponseBody() {
        }
        
        public gxmtResponseBody(int gxmtReturn) {
            this.gxmtReturn = gxmtReturn;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getUserInfo {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getUserInfo", Namespace="http://service.nineorange.com", Order=0)]
        public LazyAtHome.Service.SMS.JianZhouService.getUserInfoBody Body;
        
        public getUserInfo() {
        }
        
        public getUserInfo(LazyAtHome.Service.SMS.JianZhouService.getUserInfoBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://service.nineorange.com")]
    public partial class getUserInfoBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string account;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        public getUserInfoBody() {
        }
        
        public getUserInfoBody(string account, string password) {
            this.account = account;
            this.password = password;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getUserInfoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getUserInfoResponse", Namespace="http://service.nineorange.com", Order=0)]
        public LazyAtHome.Service.SMS.JianZhouService.getUserInfoResponseBody Body;
        
        public getUserInfoResponse() {
        }
        
        public getUserInfoResponse(LazyAtHome.Service.SMS.JianZhouService.getUserInfoResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://service.nineorange.com")]
    public partial class getUserInfoResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string getUserInfoReturn;
        
        public getUserInfoResponseBody() {
        }
        
        public getUserInfoResponseBody(string getUserInfoReturn) {
            this.getUserInfoReturn = getUserInfoReturn;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class sendAudio {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="sendAudio", Namespace="http://service.nineorange.com", Order=0)]
        public LazyAtHome.Service.SMS.JianZhouService.sendAudioBody Body;
        
        public sendAudio() {
        }
        
        public sendAudio(LazyAtHome.Service.SMS.JianZhouService.sendAudioBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://service.nineorange.com")]
    public partial class sendAudioBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string account;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string sendDateTime;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string destmobile;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string msgText;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string srcMobile;
        
        public sendAudioBody() {
        }
        
        public sendAudioBody(string account, string password, string sendDateTime, string destmobile, string msgText, string srcMobile) {
            this.account = account;
            this.password = password;
            this.sendDateTime = sendDateTime;
            this.destmobile = destmobile;
            this.msgText = msgText;
            this.srcMobile = srcMobile;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class sendAudioResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="sendAudioResponse", Namespace="http://service.nineorange.com", Order=0)]
        public LazyAtHome.Service.SMS.JianZhouService.sendAudioResponseBody Body;
        
        public sendAudioResponse() {
        }
        
        public sendAudioResponse(LazyAtHome.Service.SMS.JianZhouService.sendAudioResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://service.nineorange.com")]
    public partial class sendAudioResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int @return;
        
        public sendAudioResponseBody() {
        }
        
        public sendAudioResponseBody(int @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface BusinessServiceChannel : LazyAtHome.Service.SMS.JianZhouService.BusinessService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class BusinessServiceClient : System.ServiceModel.ClientBase<LazyAtHome.Service.SMS.JianZhouService.BusinessService>, LazyAtHome.Service.SMS.JianZhouService.BusinessService {
        
        public BusinessServiceClient() {
        }
        
        public BusinessServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public BusinessServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BusinessServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BusinessServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        LazyAtHome.Service.SMS.JianZhouService.getReceivedMsgResponse LazyAtHome.Service.SMS.JianZhouService.BusinessService.getReceivedMsg(LazyAtHome.Service.SMS.JianZhouService.getReceivedMsg request) {
            return base.Channel.getReceivedMsg(request);
        }
        
        public string getReceivedMsg(string account, string password, int param) {
            LazyAtHome.Service.SMS.JianZhouService.getReceivedMsg inValue = new LazyAtHome.Service.SMS.JianZhouService.getReceivedMsg();
            inValue.Body = new LazyAtHome.Service.SMS.JianZhouService.getReceivedMsgBody();
            inValue.Body.account = account;
            inValue.Body.password = password;
            inValue.Body.param = param;
            LazyAtHome.Service.SMS.JianZhouService.getReceivedMsgResponse retVal = ((LazyAtHome.Service.SMS.JianZhouService.BusinessService)(this)).getReceivedMsg(inValue);
            return retVal.Body.getReceivedMsgReturn;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<LazyAtHome.Service.SMS.JianZhouService.getReceivedMsgResponse> LazyAtHome.Service.SMS.JianZhouService.BusinessService.getReceivedMsgAsync(LazyAtHome.Service.SMS.JianZhouService.getReceivedMsg request) {
            return base.Channel.getReceivedMsgAsync(request);
        }
        
        public System.Threading.Tasks.Task<LazyAtHome.Service.SMS.JianZhouService.getReceivedMsgResponse> getReceivedMsgAsync(string account, string password, int param) {
            LazyAtHome.Service.SMS.JianZhouService.getReceivedMsg inValue = new LazyAtHome.Service.SMS.JianZhouService.getReceivedMsg();
            inValue.Body = new LazyAtHome.Service.SMS.JianZhouService.getReceivedMsgBody();
            inValue.Body.account = account;
            inValue.Body.password = password;
            inValue.Body.param = param;
            return ((LazyAtHome.Service.SMS.JianZhouService.BusinessService)(this)).getReceivedMsgAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        LazyAtHome.Service.SMS.JianZhouService.sendBatchMessageTimelyExtResponse LazyAtHome.Service.SMS.JianZhouService.BusinessService.sendBatchMessageTimelyExt(LazyAtHome.Service.SMS.JianZhouService.sendBatchMessageTimelyExt request) {
            return base.Channel.sendBatchMessageTimelyExt(request);
        }
        
        public int sendBatchMessageTimelyExt(string account, string password, string sendDateTime, string destmobile, string msgText, string ext) {
            LazyAtHome.Service.SMS.JianZhouService.sendBatchMessageTimelyExt inValue = new LazyAtHome.Service.SMS.JianZhouService.sendBatchMessageTimelyExt();
            inValue.Body = new LazyAtHome.Service.SMS.JianZhouService.sendBatchMessageTimelyExtBody();
            inValue.Body.account = account;
            inValue.Body.password = password;
            inValue.Body.sendDateTime = sendDateTime;
            inValue.Body.destmobile = destmobile;
            inValue.Body.msgText = msgText;
            inValue.Body.ext = ext;
            LazyAtHome.Service.SMS.JianZhouService.sendBatchMessageTimelyExtResponse retVal = ((LazyAtHome.Service.SMS.JianZhouService.BusinessService)(this)).sendBatchMessageTimelyExt(inValue);
            return retVal.Body.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<LazyAtHome.Service.SMS.JianZhouService.sendBatchMessageTimelyExtResponse> LazyAtHome.Service.SMS.JianZhouService.BusinessService.sendBatchMessageTimelyExtAsync(LazyAtHome.Service.SMS.JianZhouService.sendBatchMessageTimelyExt request) {
            return base.Channel.sendBatchMessageTimelyExtAsync(request);
        }
        
        public System.Threading.Tasks.Task<LazyAtHome.Service.SMS.JianZhouService.sendBatchMessageTimelyExtResponse> sendBatchMessageTimelyExtAsync(string account, string password, string sendDateTime, string destmobile, string msgText, string ext) {
            LazyAtHome.Service.SMS.JianZhouService.sendBatchMessageTimelyExt inValue = new LazyAtHome.Service.SMS.JianZhouService.sendBatchMessageTimelyExt();
            inValue.Body = new LazyAtHome.Service.SMS.JianZhouService.sendBatchMessageTimelyExtBody();
            inValue.Body.account = account;
            inValue.Body.password = password;
            inValue.Body.sendDateTime = sendDateTime;
            inValue.Body.destmobile = destmobile;
            inValue.Body.msgText = msgText;
            inValue.Body.ext = ext;
            return ((LazyAtHome.Service.SMS.JianZhouService.BusinessService)(this)).sendBatchMessageTimelyExtAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        LazyAtHome.Service.SMS.JianZhouService.sendPersonalMessagesResponse LazyAtHome.Service.SMS.JianZhouService.BusinessService.sendPersonalMessages(LazyAtHome.Service.SMS.JianZhouService.sendPersonalMessages request) {
            return base.Channel.sendPersonalMessages(request);
        }
        
        public int sendPersonalMessages(string account, string password, string destMobiles, string msgContents) {
            LazyAtHome.Service.SMS.JianZhouService.sendPersonalMessages inValue = new LazyAtHome.Service.SMS.JianZhouService.sendPersonalMessages();
            inValue.Body = new LazyAtHome.Service.SMS.JianZhouService.sendPersonalMessagesBody();
            inValue.Body.account = account;
            inValue.Body.password = password;
            inValue.Body.destMobiles = destMobiles;
            inValue.Body.msgContents = msgContents;
            LazyAtHome.Service.SMS.JianZhouService.sendPersonalMessagesResponse retVal = ((LazyAtHome.Service.SMS.JianZhouService.BusinessService)(this)).sendPersonalMessages(inValue);
            return retVal.Body.sendPersonalMessagesReturn;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<LazyAtHome.Service.SMS.JianZhouService.sendPersonalMessagesResponse> LazyAtHome.Service.SMS.JianZhouService.BusinessService.sendPersonalMessagesAsync(LazyAtHome.Service.SMS.JianZhouService.sendPersonalMessages request) {
            return base.Channel.sendPersonalMessagesAsync(request);
        }
        
        public System.Threading.Tasks.Task<LazyAtHome.Service.SMS.JianZhouService.sendPersonalMessagesResponse> sendPersonalMessagesAsync(string account, string password, string destMobiles, string msgContents) {
            LazyAtHome.Service.SMS.JianZhouService.sendPersonalMessages inValue = new LazyAtHome.Service.SMS.JianZhouService.sendPersonalMessages();
            inValue.Body = new LazyAtHome.Service.SMS.JianZhouService.sendPersonalMessagesBody();
            inValue.Body.account = account;
            inValue.Body.password = password;
            inValue.Body.destMobiles = destMobiles;
            inValue.Body.msgContents = msgContents;
            return ((LazyAtHome.Service.SMS.JianZhouService.BusinessService)(this)).sendPersonalMessagesAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        LazyAtHome.Service.SMS.JianZhouService.modifyPasswordResponse LazyAtHome.Service.SMS.JianZhouService.BusinessService.modifyPassword(LazyAtHome.Service.SMS.JianZhouService.modifyPassword request) {
            return base.Channel.modifyPassword(request);
        }
        
        public int modifyPassword(string account, string oldPassword, string newPassword) {
            LazyAtHome.Service.SMS.JianZhouService.modifyPassword inValue = new LazyAtHome.Service.SMS.JianZhouService.modifyPassword();
            inValue.Body = new LazyAtHome.Service.SMS.JianZhouService.modifyPasswordBody();
            inValue.Body.account = account;
            inValue.Body.oldPassword = oldPassword;
            inValue.Body.newPassword = newPassword;
            LazyAtHome.Service.SMS.JianZhouService.modifyPasswordResponse retVal = ((LazyAtHome.Service.SMS.JianZhouService.BusinessService)(this)).modifyPassword(inValue);
            return retVal.Body.modifyPasswordReturn;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<LazyAtHome.Service.SMS.JianZhouService.modifyPasswordResponse> LazyAtHome.Service.SMS.JianZhouService.BusinessService.modifyPasswordAsync(LazyAtHome.Service.SMS.JianZhouService.modifyPassword request) {
            return base.Channel.modifyPasswordAsync(request);
        }
        
        public System.Threading.Tasks.Task<LazyAtHome.Service.SMS.JianZhouService.modifyPasswordResponse> modifyPasswordAsync(string account, string oldPassword, string newPassword) {
            LazyAtHome.Service.SMS.JianZhouService.modifyPassword inValue = new LazyAtHome.Service.SMS.JianZhouService.modifyPassword();
            inValue.Body = new LazyAtHome.Service.SMS.JianZhouService.modifyPasswordBody();
            inValue.Body.account = account;
            inValue.Body.oldPassword = oldPassword;
            inValue.Body.newPassword = newPassword;
            return ((LazyAtHome.Service.SMS.JianZhouService.BusinessService)(this)).modifyPasswordAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        LazyAtHome.Service.SMS.JianZhouService.getReceiptResponse LazyAtHome.Service.SMS.JianZhouService.BusinessService.getReceipt(LazyAtHome.Service.SMS.JianZhouService.getReceipt request) {
            return base.Channel.getReceipt(request);
        }
        
        public string getReceipt(string account, string password, int taskID) {
            LazyAtHome.Service.SMS.JianZhouService.getReceipt inValue = new LazyAtHome.Service.SMS.JianZhouService.getReceipt();
            inValue.Body = new LazyAtHome.Service.SMS.JianZhouService.getReceiptBody();
            inValue.Body.account = account;
            inValue.Body.password = password;
            inValue.Body.taskID = taskID;
            LazyAtHome.Service.SMS.JianZhouService.getReceiptResponse retVal = ((LazyAtHome.Service.SMS.JianZhouService.BusinessService)(this)).getReceipt(inValue);
            return retVal.Body.getReceiptReturn;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<LazyAtHome.Service.SMS.JianZhouService.getReceiptResponse> LazyAtHome.Service.SMS.JianZhouService.BusinessService.getReceiptAsync(LazyAtHome.Service.SMS.JianZhouService.getReceipt request) {
            return base.Channel.getReceiptAsync(request);
        }
        
        public System.Threading.Tasks.Task<LazyAtHome.Service.SMS.JianZhouService.getReceiptResponse> getReceiptAsync(string account, string password, int taskID) {
            LazyAtHome.Service.SMS.JianZhouService.getReceipt inValue = new LazyAtHome.Service.SMS.JianZhouService.getReceipt();
            inValue.Body = new LazyAtHome.Service.SMS.JianZhouService.getReceiptBody();
            inValue.Body.account = account;
            inValue.Body.password = password;
            inValue.Body.taskID = taskID;
            return ((LazyAtHome.Service.SMS.JianZhouService.BusinessService)(this)).getReceiptAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        LazyAtHome.Service.SMS.JianZhouService.sendBatchMessageResponse LazyAtHome.Service.SMS.JianZhouService.BusinessService.sendBatchMessage(LazyAtHome.Service.SMS.JianZhouService.sendBatchMessage request) {
            return base.Channel.sendBatchMessage(request);
        }
        
        public int sendBatchMessage(string account, string password, string destmobile, string msgText) {
            LazyAtHome.Service.SMS.JianZhouService.sendBatchMessage inValue = new LazyAtHome.Service.SMS.JianZhouService.sendBatchMessage();
            inValue.Body = new LazyAtHome.Service.SMS.JianZhouService.sendBatchMessageBody();
            inValue.Body.account = account;
            inValue.Body.password = password;
            inValue.Body.destmobile = destmobile;
            inValue.Body.msgText = msgText;
            LazyAtHome.Service.SMS.JianZhouService.sendBatchMessageResponse retVal = ((LazyAtHome.Service.SMS.JianZhouService.BusinessService)(this)).sendBatchMessage(inValue);
            return retVal.Body.sendBatchMessageReturn;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<LazyAtHome.Service.SMS.JianZhouService.sendBatchMessageResponse> LazyAtHome.Service.SMS.JianZhouService.BusinessService.sendBatchMessageAsync(LazyAtHome.Service.SMS.JianZhouService.sendBatchMessage request) {
            return base.Channel.sendBatchMessageAsync(request);
        }
        
        public System.Threading.Tasks.Task<LazyAtHome.Service.SMS.JianZhouService.sendBatchMessageResponse> sendBatchMessageAsync(string account, string password, string destmobile, string msgText) {
            LazyAtHome.Service.SMS.JianZhouService.sendBatchMessage inValue = new LazyAtHome.Service.SMS.JianZhouService.sendBatchMessage();
            inValue.Body = new LazyAtHome.Service.SMS.JianZhouService.sendBatchMessageBody();
            inValue.Body.account = account;
            inValue.Body.password = password;
            inValue.Body.destmobile = destmobile;
            inValue.Body.msgText = msgText;
            return ((LazyAtHome.Service.SMS.JianZhouService.BusinessService)(this)).sendBatchMessageAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        LazyAtHome.Service.SMS.JianZhouService.validateUserResponse LazyAtHome.Service.SMS.JianZhouService.BusinessService.validateUser(LazyAtHome.Service.SMS.JianZhouService.validateUser request) {
            return base.Channel.validateUser(request);
        }
        
        public int validateUser(string account, string password) {
            LazyAtHome.Service.SMS.JianZhouService.validateUser inValue = new LazyAtHome.Service.SMS.JianZhouService.validateUser();
            inValue.Body = new LazyAtHome.Service.SMS.JianZhouService.validateUserBody();
            inValue.Body.account = account;
            inValue.Body.password = password;
            LazyAtHome.Service.SMS.JianZhouService.validateUserResponse retVal = ((LazyAtHome.Service.SMS.JianZhouService.BusinessService)(this)).validateUser(inValue);
            return retVal.Body.validateUserReturn;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<LazyAtHome.Service.SMS.JianZhouService.validateUserResponse> LazyAtHome.Service.SMS.JianZhouService.BusinessService.validateUserAsync(LazyAtHome.Service.SMS.JianZhouService.validateUser request) {
            return base.Channel.validateUserAsync(request);
        }
        
        public System.Threading.Tasks.Task<LazyAtHome.Service.SMS.JianZhouService.validateUserResponse> validateUserAsync(string account, string password) {
            LazyAtHome.Service.SMS.JianZhouService.validateUser inValue = new LazyAtHome.Service.SMS.JianZhouService.validateUser();
            inValue.Body = new LazyAtHome.Service.SMS.JianZhouService.validateUserBody();
            inValue.Body.account = account;
            inValue.Body.password = password;
            return ((LazyAtHome.Service.SMS.JianZhouService.BusinessService)(this)).validateUserAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        LazyAtHome.Service.SMS.JianZhouService.sendMessageResponse LazyAtHome.Service.SMS.JianZhouService.BusinessService.sendMessage(LazyAtHome.Service.SMS.JianZhouService.sendMessage request) {
            return base.Channel.sendMessage(request);
        }
        
        public int sendMessage(string account, string password, string destmobile, string msgText) {
            LazyAtHome.Service.SMS.JianZhouService.sendMessage inValue = new LazyAtHome.Service.SMS.JianZhouService.sendMessage();
            inValue.Body = new LazyAtHome.Service.SMS.JianZhouService.sendMessageBody();
            inValue.Body.account = account;
            inValue.Body.password = password;
            inValue.Body.destmobile = destmobile;
            inValue.Body.msgText = msgText;
            LazyAtHome.Service.SMS.JianZhouService.sendMessageResponse retVal = ((LazyAtHome.Service.SMS.JianZhouService.BusinessService)(this)).sendMessage(inValue);
            return retVal.Body.sendMessageReturn;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<LazyAtHome.Service.SMS.JianZhouService.sendMessageResponse> LazyAtHome.Service.SMS.JianZhouService.BusinessService.sendMessageAsync(LazyAtHome.Service.SMS.JianZhouService.sendMessage request) {
            return base.Channel.sendMessageAsync(request);
        }
        
        public System.Threading.Tasks.Task<LazyAtHome.Service.SMS.JianZhouService.sendMessageResponse> sendMessageAsync(string account, string password, string destmobile, string msgText) {
            LazyAtHome.Service.SMS.JianZhouService.sendMessage inValue = new LazyAtHome.Service.SMS.JianZhouService.sendMessage();
            inValue.Body = new LazyAtHome.Service.SMS.JianZhouService.sendMessageBody();
            inValue.Body.account = account;
            inValue.Body.password = password;
            inValue.Body.destmobile = destmobile;
            inValue.Body.msgText = msgText;
            return ((LazyAtHome.Service.SMS.JianZhouService.BusinessService)(this)).sendMessageAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        LazyAtHome.Service.SMS.JianZhouService.sendTimelyMessageResponse LazyAtHome.Service.SMS.JianZhouService.BusinessService.sendTimelyMessage(LazyAtHome.Service.SMS.JianZhouService.sendTimelyMessage request) {
            return base.Channel.sendTimelyMessage(request);
        }
        
        public int sendTimelyMessage(string account, string password, string sendDateTime, string destmobile, string msgText) {
            LazyAtHome.Service.SMS.JianZhouService.sendTimelyMessage inValue = new LazyAtHome.Service.SMS.JianZhouService.sendTimelyMessage();
            inValue.Body = new LazyAtHome.Service.SMS.JianZhouService.sendTimelyMessageBody();
            inValue.Body.account = account;
            inValue.Body.password = password;
            inValue.Body.sendDateTime = sendDateTime;
            inValue.Body.destmobile = destmobile;
            inValue.Body.msgText = msgText;
            LazyAtHome.Service.SMS.JianZhouService.sendTimelyMessageResponse retVal = ((LazyAtHome.Service.SMS.JianZhouService.BusinessService)(this)).sendTimelyMessage(inValue);
            return retVal.Body.sendTimelyMessageReturn;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<LazyAtHome.Service.SMS.JianZhouService.sendTimelyMessageResponse> LazyAtHome.Service.SMS.JianZhouService.BusinessService.sendTimelyMessageAsync(LazyAtHome.Service.SMS.JianZhouService.sendTimelyMessage request) {
            return base.Channel.sendTimelyMessageAsync(request);
        }
        
        public System.Threading.Tasks.Task<LazyAtHome.Service.SMS.JianZhouService.sendTimelyMessageResponse> sendTimelyMessageAsync(string account, string password, string sendDateTime, string destmobile, string msgText) {
            LazyAtHome.Service.SMS.JianZhouService.sendTimelyMessage inValue = new LazyAtHome.Service.SMS.JianZhouService.sendTimelyMessage();
            inValue.Body = new LazyAtHome.Service.SMS.JianZhouService.sendTimelyMessageBody();
            inValue.Body.account = account;
            inValue.Body.password = password;
            inValue.Body.sendDateTime = sendDateTime;
            inValue.Body.destmobile = destmobile;
            inValue.Body.msgText = msgText;
            return ((LazyAtHome.Service.SMS.JianZhouService.BusinessService)(this)).sendTimelyMessageAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        LazyAtHome.Service.SMS.JianZhouService.sendMmsMessagesResponse LazyAtHome.Service.SMS.JianZhouService.BusinessService.sendMmsMessages(LazyAtHome.Service.SMS.JianZhouService.sendMmsMessages request) {
            return base.Channel.sendMmsMessages(request);
        }
        
        public int sendMmsMessages(string account, string password, string phones, string mmsString) {
            LazyAtHome.Service.SMS.JianZhouService.sendMmsMessages inValue = new LazyAtHome.Service.SMS.JianZhouService.sendMmsMessages();
            inValue.Body = new LazyAtHome.Service.SMS.JianZhouService.sendMmsMessagesBody();
            inValue.Body.account = account;
            inValue.Body.password = password;
            inValue.Body.phones = phones;
            inValue.Body.mmsString = mmsString;
            LazyAtHome.Service.SMS.JianZhouService.sendMmsMessagesResponse retVal = ((LazyAtHome.Service.SMS.JianZhouService.BusinessService)(this)).sendMmsMessages(inValue);
            return retVal.Body.sendMmsMessagesReturn;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<LazyAtHome.Service.SMS.JianZhouService.sendMmsMessagesResponse> LazyAtHome.Service.SMS.JianZhouService.BusinessService.sendMmsMessagesAsync(LazyAtHome.Service.SMS.JianZhouService.sendMmsMessages request) {
            return base.Channel.sendMmsMessagesAsync(request);
        }
        
        public System.Threading.Tasks.Task<LazyAtHome.Service.SMS.JianZhouService.sendMmsMessagesResponse> sendMmsMessagesAsync(string account, string password, string phones, string mmsString) {
            LazyAtHome.Service.SMS.JianZhouService.sendMmsMessages inValue = new LazyAtHome.Service.SMS.JianZhouService.sendMmsMessages();
            inValue.Body = new LazyAtHome.Service.SMS.JianZhouService.sendMmsMessagesBody();
            inValue.Body.account = account;
            inValue.Body.password = password;
            inValue.Body.phones = phones;
            inValue.Body.mmsString = mmsString;
            return ((LazyAtHome.Service.SMS.JianZhouService.BusinessService)(this)).sendMmsMessagesAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        LazyAtHome.Service.SMS.JianZhouService.gxmtResponse LazyAtHome.Service.SMS.JianZhouService.BusinessService.gxmt(LazyAtHome.Service.SMS.JianZhouService.gxmt request) {
            return base.Channel.gxmt(request);
        }
        
        public int gxmt(string account, string password, string sendDateTime, string destmobiles, string msgTexts) {
            LazyAtHome.Service.SMS.JianZhouService.gxmt inValue = new LazyAtHome.Service.SMS.JianZhouService.gxmt();
            inValue.Body = new LazyAtHome.Service.SMS.JianZhouService.gxmtBody();
            inValue.Body.account = account;
            inValue.Body.password = password;
            inValue.Body.sendDateTime = sendDateTime;
            inValue.Body.destmobiles = destmobiles;
            inValue.Body.msgTexts = msgTexts;
            LazyAtHome.Service.SMS.JianZhouService.gxmtResponse retVal = ((LazyAtHome.Service.SMS.JianZhouService.BusinessService)(this)).gxmt(inValue);
            return retVal.Body.gxmtReturn;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<LazyAtHome.Service.SMS.JianZhouService.gxmtResponse> LazyAtHome.Service.SMS.JianZhouService.BusinessService.gxmtAsync(LazyAtHome.Service.SMS.JianZhouService.gxmt request) {
            return base.Channel.gxmtAsync(request);
        }
        
        public System.Threading.Tasks.Task<LazyAtHome.Service.SMS.JianZhouService.gxmtResponse> gxmtAsync(string account, string password, string sendDateTime, string destmobiles, string msgTexts) {
            LazyAtHome.Service.SMS.JianZhouService.gxmt inValue = new LazyAtHome.Service.SMS.JianZhouService.gxmt();
            inValue.Body = new LazyAtHome.Service.SMS.JianZhouService.gxmtBody();
            inValue.Body.account = account;
            inValue.Body.password = password;
            inValue.Body.sendDateTime = sendDateTime;
            inValue.Body.destmobiles = destmobiles;
            inValue.Body.msgTexts = msgTexts;
            return ((LazyAtHome.Service.SMS.JianZhouService.BusinessService)(this)).gxmtAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        LazyAtHome.Service.SMS.JianZhouService.getUserInfoResponse LazyAtHome.Service.SMS.JianZhouService.BusinessService.getUserInfo(LazyAtHome.Service.SMS.JianZhouService.getUserInfo request) {
            return base.Channel.getUserInfo(request);
        }
        
        public string getUserInfo(string account, string password) {
            LazyAtHome.Service.SMS.JianZhouService.getUserInfo inValue = new LazyAtHome.Service.SMS.JianZhouService.getUserInfo();
            inValue.Body = new LazyAtHome.Service.SMS.JianZhouService.getUserInfoBody();
            inValue.Body.account = account;
            inValue.Body.password = password;
            LazyAtHome.Service.SMS.JianZhouService.getUserInfoResponse retVal = ((LazyAtHome.Service.SMS.JianZhouService.BusinessService)(this)).getUserInfo(inValue);
            return retVal.Body.getUserInfoReturn;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<LazyAtHome.Service.SMS.JianZhouService.getUserInfoResponse> LazyAtHome.Service.SMS.JianZhouService.BusinessService.getUserInfoAsync(LazyAtHome.Service.SMS.JianZhouService.getUserInfo request) {
            return base.Channel.getUserInfoAsync(request);
        }
        
        public System.Threading.Tasks.Task<LazyAtHome.Service.SMS.JianZhouService.getUserInfoResponse> getUserInfoAsync(string account, string password) {
            LazyAtHome.Service.SMS.JianZhouService.getUserInfo inValue = new LazyAtHome.Service.SMS.JianZhouService.getUserInfo();
            inValue.Body = new LazyAtHome.Service.SMS.JianZhouService.getUserInfoBody();
            inValue.Body.account = account;
            inValue.Body.password = password;
            return ((LazyAtHome.Service.SMS.JianZhouService.BusinessService)(this)).getUserInfoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        LazyAtHome.Service.SMS.JianZhouService.sendAudioResponse LazyAtHome.Service.SMS.JianZhouService.BusinessService.sendAudio(LazyAtHome.Service.SMS.JianZhouService.sendAudio request) {
            return base.Channel.sendAudio(request);
        }
        
        public int sendAudio(string account, string password, string sendDateTime, string destmobile, string msgText, string srcMobile) {
            LazyAtHome.Service.SMS.JianZhouService.sendAudio inValue = new LazyAtHome.Service.SMS.JianZhouService.sendAudio();
            inValue.Body = new LazyAtHome.Service.SMS.JianZhouService.sendAudioBody();
            inValue.Body.account = account;
            inValue.Body.password = password;
            inValue.Body.sendDateTime = sendDateTime;
            inValue.Body.destmobile = destmobile;
            inValue.Body.msgText = msgText;
            inValue.Body.srcMobile = srcMobile;
            LazyAtHome.Service.SMS.JianZhouService.sendAudioResponse retVal = ((LazyAtHome.Service.SMS.JianZhouService.BusinessService)(this)).sendAudio(inValue);
            return retVal.Body.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<LazyAtHome.Service.SMS.JianZhouService.sendAudioResponse> LazyAtHome.Service.SMS.JianZhouService.BusinessService.sendAudioAsync(LazyAtHome.Service.SMS.JianZhouService.sendAudio request) {
            return base.Channel.sendAudioAsync(request);
        }
        
        public System.Threading.Tasks.Task<LazyAtHome.Service.SMS.JianZhouService.sendAudioResponse> sendAudioAsync(string account, string password, string sendDateTime, string destmobile, string msgText, string srcMobile) {
            LazyAtHome.Service.SMS.JianZhouService.sendAudio inValue = new LazyAtHome.Service.SMS.JianZhouService.sendAudio();
            inValue.Body = new LazyAtHome.Service.SMS.JianZhouService.sendAudioBody();
            inValue.Body.account = account;
            inValue.Body.password = password;
            inValue.Body.sendDateTime = sendDateTime;
            inValue.Body.destmobile = destmobile;
            inValue.Body.msgText = msgText;
            inValue.Body.srcMobile = srcMobile;
            return ((LazyAtHome.Service.SMS.JianZhouService.BusinessService)(this)).sendAudioAsync(inValue);
        }
    }
}
