
package com.landaojia.washclothes.userappserver.service.sms.jianzhou.ws;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.0.4
 * 2015-03-16T15:53:48.198+08:00
 * Generated source version: 3.0.4
 * 
 */
public final class BusinessService_BusinessServicePort_Client {

    private static final QName SERVICE_NAME = new QName("http://service.nineorange.com", "BusinessServiceService");

    private BusinessService_BusinessServicePort_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = BusinessServiceService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        BusinessServiceService ss = new BusinessServiceService(wsdlURL, SERVICE_NAME);
        BusinessService port = ss.getBusinessServicePort();  
        
        {
        System.out.println("Invoking validateUser...");
        java.lang.String _validateUser_account = "";
        java.lang.String _validateUser_password = "";
        int _validateUser__return = port.validateUser(_validateUser_account, _validateUser_password);
        System.out.println("validateUser.result=" + _validateUser__return);


        }
        {
        System.out.println("Invoking sendBatchMessage...");
        java.lang.String _sendBatchMessage_account = "";
        java.lang.String _sendBatchMessage_password = "";
        java.lang.String _sendBatchMessage_destmobile = "";
        java.lang.String _sendBatchMessage_msgText = "";
        int _sendBatchMessage__return = port.sendBatchMessage(_sendBatchMessage_account, _sendBatchMessage_password, _sendBatchMessage_destmobile, _sendBatchMessage_msgText);
        System.out.println("sendBatchMessage.result=" + _sendBatchMessage__return);


        }
        {
        System.out.println("Invoking getReceivedMsg...");
        java.lang.String _getReceivedMsg_account = "";
        java.lang.String _getReceivedMsg_password = "";
        int _getReceivedMsg_param = 0;
        java.lang.String _getReceivedMsg__return = port.getReceivedMsg(_getReceivedMsg_account, _getReceivedMsg_password, _getReceivedMsg_param);
        System.out.println("getReceivedMsg.result=" + _getReceivedMsg__return);


        }
        {
        System.out.println("Invoking sendGjBatchMessage...");
        java.lang.String _sendGjBatchMessage_account = "";
        java.lang.String _sendGjBatchMessage_password = "";
        java.lang.String _sendGjBatchMessage_sendDateTime = "";
        java.lang.String _sendGjBatchMessage_destmobile = "";
        java.lang.String _sendGjBatchMessage_msgText = "";
        int _sendGjBatchMessage__return = port.sendGjBatchMessage(_sendGjBatchMessage_account, _sendGjBatchMessage_password, _sendGjBatchMessage_sendDateTime, _sendGjBatchMessage_destmobile, _sendGjBatchMessage_msgText);
        System.out.println("sendGjBatchMessage.result=" + _sendGjBatchMessage__return);


        }
        {
        System.out.println("Invoking sendAudio...");
        java.lang.String _sendAudio_account = "";
        java.lang.String _sendAudio_password = "";
        java.lang.String _sendAudio_sendDateTime = "";
        java.lang.String _sendAudio_destmobile = "";
        java.lang.String _sendAudio_msgText = "";
        java.lang.String _sendAudio_srcMobile = "";
        int _sendAudio__return = port.sendAudio(_sendAudio_account, _sendAudio_password, _sendAudio_sendDateTime, _sendAudio_destmobile, _sendAudio_msgText, _sendAudio_srcMobile);
        System.out.println("sendAudio.result=" + _sendAudio__return);


        }
        {
        System.out.println("Invoking getUserInfo...");
        java.lang.String _getUserInfo_account = "";
        java.lang.String _getUserInfo_password = "";
        java.lang.String _getUserInfo__return = port.getUserInfo(_getUserInfo_account, _getUserInfo_password);
        System.out.println("getUserInfo.result=" + _getUserInfo__return);


        }
        {
        System.out.println("Invoking sendPersonalMessages...");
        java.lang.String _sendPersonalMessages_account = "";
        java.lang.String _sendPersonalMessages_password = "";
        java.lang.String _sendPersonalMessages_destMobiles = "";
        java.lang.String _sendPersonalMessages_msgContents = "";
        int _sendPersonalMessages__return = port.sendPersonalMessages(_sendPersonalMessages_account, _sendPersonalMessages_password, _sendPersonalMessages_destMobiles, _sendPersonalMessages_msgContents);
        System.out.println("sendPersonalMessages.result=" + _sendPersonalMessages__return);


        }
        {
        System.out.println("Invoking sendBatchMessageTimelyExt...");
        java.lang.String _sendBatchMessageTimelyExt_account = "";
        java.lang.String _sendBatchMessageTimelyExt_password = "";
        java.lang.String _sendBatchMessageTimelyExt_sendDateTime = "";
        java.lang.String _sendBatchMessageTimelyExt_destmobile = "";
        java.lang.String _sendBatchMessageTimelyExt_msgText = "";
        java.lang.String _sendBatchMessageTimelyExt_ext = "";
        int _sendBatchMessageTimelyExt__return = port.sendBatchMessageTimelyExt(_sendBatchMessageTimelyExt_account, _sendBatchMessageTimelyExt_password, _sendBatchMessageTimelyExt_sendDateTime, _sendBatchMessageTimelyExt_destmobile, _sendBatchMessageTimelyExt_msgText, _sendBatchMessageTimelyExt_ext);
        System.out.println("sendBatchMessageTimelyExt.result=" + _sendBatchMessageTimelyExt__return);


        }
        {
        System.out.println("Invoking modifyPassword...");
        java.lang.String _modifyPassword_account = "";
        java.lang.String _modifyPassword_oldPassword = "";
        java.lang.String _modifyPassword_newPassword = "";
        int _modifyPassword__return = port.modifyPassword(_modifyPassword_account, _modifyPassword_oldPassword, _modifyPassword_newPassword);
        System.out.println("modifyPassword.result=" + _modifyPassword__return);


        }
        {
        System.out.println("Invoking gxmt...");
        com.landaojia.washclothes.userappserver.service.sms.jianzhou.ws.Gxmt _gxmt_parameters = null;
        com.landaojia.washclothes.userappserver.service.sms.jianzhou.ws.GxmtResponse _gxmt__return = port.gxmt(_gxmt_parameters);
        System.out.println("gxmt.result=" + _gxmt__return);


        }
        {
        System.out.println("Invoking sendMessage...");
        java.lang.String _sendMessage_account = "";
        java.lang.String _sendMessage_password = "";
        java.lang.String _sendMessage_destmobile = "";
        java.lang.String _sendMessage_msgText = "";
        int _sendMessage__return = port.sendMessage(_sendMessage_account, _sendMessage_password, _sendMessage_destmobile, _sendMessage_msgText);
        System.out.println("sendMessage.result=" + _sendMessage__return);


        }
        {
        System.out.println("Invoking sendMmsMessages...");
        java.lang.String _sendMmsMessages_account = "";
        java.lang.String _sendMmsMessages_password = "";
        java.lang.String _sendMmsMessages_phones = "";
        java.lang.String _sendMmsMessages_mmsString = "";
        int _sendMmsMessages__return = port.sendMmsMessages(_sendMmsMessages_account, _sendMmsMessages_password, _sendMmsMessages_phones, _sendMmsMessages_mmsString);
        System.out.println("sendMmsMessages.result=" + _sendMmsMessages__return);


        }
        {
        System.out.println("Invoking sendTimelyMessage...");
        java.lang.String _sendTimelyMessage_account = "";
        java.lang.String _sendTimelyMessage_password = "";
        java.lang.String _sendTimelyMessage_sendDateTime = "";
        java.lang.String _sendTimelyMessage_destmobile = "";
        java.lang.String _sendTimelyMessage_msgText = "";
        int _sendTimelyMessage__return = port.sendTimelyMessage(_sendTimelyMessage_account, _sendTimelyMessage_password, _sendTimelyMessage_sendDateTime, _sendTimelyMessage_destmobile, _sendTimelyMessage_msgText);
        System.out.println("sendTimelyMessage.result=" + _sendTimelyMessage__return);


        }
        {
        System.out.println("Invoking getReceipt...");
        java.lang.String _getReceipt_account = "";
        java.lang.String _getReceipt_password = "";
        int _getReceipt_taskID = 0;
        java.lang.String _getReceipt__return = port.getReceipt(_getReceipt_account, _getReceipt_password, _getReceipt_taskID);
        System.out.println("getReceipt.result=" + _getReceipt__return);


        }

        System.exit(0);
    }

}
