//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.34011
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LazyAtHome.WCF.WebService.Console_Client.WashProductService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="LoginCredentials", Namespace="http://schemas.datacontract.org/2004/07/LazyAtHome.WCF.WebService.Contract.DataCo" +
        "ntract.PR")]
    [System.SerializableAttribute()]
    public partial class LoginCredentials : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LoginNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private LazyAtHome.WCF.WebService.Console_Client.WashProductService.OperatorType OperatorTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PasswordField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LoginName {
            get {
                return this.LoginNameField;
            }
            set {
                if ((object.ReferenceEquals(this.LoginNameField, value) != true)) {
                    this.LoginNameField = value;
                    this.RaisePropertyChanged("LoginName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public LazyAtHome.WCF.WebService.Console_Client.WashProductService.OperatorType OperatorType {
            get {
                return this.OperatorTypeField;
            }
            set {
                if ((this.OperatorTypeField.Equals(value) != true)) {
                    this.OperatorTypeField = value;
                    this.RaisePropertyChanged("OperatorType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Password {
            get {
                return this.PasswordField;
            }
            set {
                if ((object.ReferenceEquals(this.PasswordField, value) != true)) {
                    this.PasswordField = value;
                    this.RaisePropertyChanged("Password");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="OperatorType", Namespace="http://schemas.datacontract.org/2004/07/LazyAtHome.WCF.Common.Contract.Enumerate")]
    public enum OperatorType : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Manage = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Factory = 2,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ReturnEntityOfArrayOfWash_ClassDC0nVOtipR", Namespace="http://schemas.datacontract.org/2004/07/LazyAtHome.Core.Infrastructure.WCF")]
    [System.SerializableAttribute()]
    public partial class ReturnEntityOfArrayOfWash_ClassDC0nVOtipR : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private LazyAtHome.WCF.WebService.Console_Client.WashProductService.Wash_ClassDC[] OBJField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TitleField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Code {
            get {
                return this.CodeField;
            }
            set {
                if ((this.CodeField.Equals(value) != true)) {
                    this.CodeField = value;
                    this.RaisePropertyChanged("Code");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public LazyAtHome.WCF.WebService.Console_Client.WashProductService.Wash_ClassDC[] OBJ {
            get {
                return this.OBJField;
            }
            set {
                if ((object.ReferenceEquals(this.OBJField, value) != true)) {
                    this.OBJField = value;
                    this.RaisePropertyChanged("OBJ");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Title {
            get {
                return this.TitleField;
            }
            set {
                if ((object.ReferenceEquals(this.TitleField, value) != true)) {
                    this.TitleField = value;
                    this.RaisePropertyChanged("Title");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Wash_ClassDC", Namespace="http://schemas.datacontract.org/2004/07/LazyAtHome.WCF.Wash.Contract.DataContract" +
        "")]
    [System.SerializableAttribute()]
    public partial class Wash_ClassDC : LazyAtHome.WCF.WebService.Console_Client.WashProductService.EntityBase {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int EnableField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IsDefaultField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ParentIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int SortField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Code {
            get {
                return this.CodeField;
            }
            set {
                if ((object.ReferenceEquals(this.CodeField, value) != true)) {
                    this.CodeField = value;
                    this.RaisePropertyChanged("Code");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Enable {
            get {
                return this.EnableField;
            }
            set {
                if ((this.EnableField.Equals(value) != true)) {
                    this.EnableField = value;
                    this.RaisePropertyChanged("Enable");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IsDefault {
            get {
                return this.IsDefaultField;
            }
            set {
                if ((this.IsDefaultField.Equals(value) != true)) {
                    this.IsDefaultField = value;
                    this.RaisePropertyChanged("IsDefault");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ParentID {
            get {
                return this.ParentIDField;
            }
            set {
                if ((this.ParentIDField.Equals(value) != true)) {
                    this.ParentIDField = value;
                    this.RaisePropertyChanged("ParentID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Sort {
            get {
                return this.SortField;
            }
            set {
                if ((this.SortField.Equals(value) != true)) {
                    this.SortField = value;
                    this.RaisePropertyChanged("Sort");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EntityBase", Namespace="http://schemas.datacontract.org/2004/07/LazyAtHome.Core.Infrastructure.WCF")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(LazyAtHome.WCF.WebService.Console_Client.WashProductService.Wash_ProductDC))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(LazyAtHome.WCF.WebService.Console_Client.WashProductService.Wash_ProductAttributeDC))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(LazyAtHome.WCF.WebService.Console_Client.WashProductService.Wash_ClassDC))]
    public partial class EntityBase : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool ModifyEnableField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> Obj_CdateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int Obj_CuserField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Obj_CuserNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> Obj_MdateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int Obj_MuserField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Obj_MuserNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Obj_RemarkField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte Obj_StatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private LazyAtHome.WCF.WebService.Console_Client.WashProductService.UpdateModel UpdateFlagField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private LazyAtHome.WCF.WebService.Console_Client.WashProductService.UpdateParamEntity[] UpdateParamField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool ModifyEnable {
            get {
                return this.ModifyEnableField;
            }
            set {
                if ((this.ModifyEnableField.Equals(value) != true)) {
                    this.ModifyEnableField = value;
                    this.RaisePropertyChanged("ModifyEnable");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> Obj_Cdate {
            get {
                return this.Obj_CdateField;
            }
            set {
                if ((this.Obj_CdateField.Equals(value) != true)) {
                    this.Obj_CdateField = value;
                    this.RaisePropertyChanged("Obj_Cdate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Obj_Cuser {
            get {
                return this.Obj_CuserField;
            }
            set {
                if ((this.Obj_CuserField.Equals(value) != true)) {
                    this.Obj_CuserField = value;
                    this.RaisePropertyChanged("Obj_Cuser");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Obj_CuserName {
            get {
                return this.Obj_CuserNameField;
            }
            set {
                if ((object.ReferenceEquals(this.Obj_CuserNameField, value) != true)) {
                    this.Obj_CuserNameField = value;
                    this.RaisePropertyChanged("Obj_CuserName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> Obj_Mdate {
            get {
                return this.Obj_MdateField;
            }
            set {
                if ((this.Obj_MdateField.Equals(value) != true)) {
                    this.Obj_MdateField = value;
                    this.RaisePropertyChanged("Obj_Mdate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Obj_Muser {
            get {
                return this.Obj_MuserField;
            }
            set {
                if ((this.Obj_MuserField.Equals(value) != true)) {
                    this.Obj_MuserField = value;
                    this.RaisePropertyChanged("Obj_Muser");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Obj_MuserName {
            get {
                return this.Obj_MuserNameField;
            }
            set {
                if ((object.ReferenceEquals(this.Obj_MuserNameField, value) != true)) {
                    this.Obj_MuserNameField = value;
                    this.RaisePropertyChanged("Obj_MuserName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Obj_Remark {
            get {
                return this.Obj_RemarkField;
            }
            set {
                if ((object.ReferenceEquals(this.Obj_RemarkField, value) != true)) {
                    this.Obj_RemarkField = value;
                    this.RaisePropertyChanged("Obj_Remark");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte Obj_Status {
            get {
                return this.Obj_StatusField;
            }
            set {
                if ((this.Obj_StatusField.Equals(value) != true)) {
                    this.Obj_StatusField = value;
                    this.RaisePropertyChanged("Obj_Status");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public LazyAtHome.WCF.WebService.Console_Client.WashProductService.UpdateModel UpdateFlag {
            get {
                return this.UpdateFlagField;
            }
            set {
                if ((this.UpdateFlagField.Equals(value) != true)) {
                    this.UpdateFlagField = value;
                    this.RaisePropertyChanged("UpdateFlag");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public LazyAtHome.WCF.WebService.Console_Client.WashProductService.UpdateParamEntity[] UpdateParam {
            get {
                return this.UpdateParamField;
            }
            set {
                if ((object.ReferenceEquals(this.UpdateParamField, value) != true)) {
                    this.UpdateParamField = value;
                    this.RaisePropertyChanged("UpdateParam");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Wash_ProductDC", Namespace="http://schemas.datacontract.org/2004/07/LazyAtHome.WCF.Wash.Contract.DataContract" +
        "")]
    [System.SerializableAttribute()]
    public partial class Wash_ProductDC : LazyAtHome.WCF.WebService.Console_Client.WashProductService.EntityBase {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> AduitDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> AduitOperatorIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private LazyAtHome.WCF.WebService.Console_Client.WashProductService.Wash_ProductAttributeDC[] AttributeListField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CategoryIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CategoryNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ClassIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ClassNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CommentField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CommitStatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ContentField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string KeywordField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal MarketPriceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> OffDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> OffOperatorIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> OnDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> OnOperatorIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ParentClassIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ParentClassNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal SalesPriceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int SiteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> SubmitDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> SubmitOperatorIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int TypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int VerifyStatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string WebNameField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> AduitDate {
            get {
                return this.AduitDateField;
            }
            set {
                if ((this.AduitDateField.Equals(value) != true)) {
                    this.AduitDateField = value;
                    this.RaisePropertyChanged("AduitDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> AduitOperatorID {
            get {
                return this.AduitOperatorIDField;
            }
            set {
                if ((this.AduitOperatorIDField.Equals(value) != true)) {
                    this.AduitOperatorIDField = value;
                    this.RaisePropertyChanged("AduitOperatorID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public LazyAtHome.WCF.WebService.Console_Client.WashProductService.Wash_ProductAttributeDC[] AttributeList {
            get {
                return this.AttributeListField;
            }
            set {
                if ((object.ReferenceEquals(this.AttributeListField, value) != true)) {
                    this.AttributeListField = value;
                    this.RaisePropertyChanged("AttributeList");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CategoryID {
            get {
                return this.CategoryIDField;
            }
            set {
                if ((this.CategoryIDField.Equals(value) != true)) {
                    this.CategoryIDField = value;
                    this.RaisePropertyChanged("CategoryID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CategoryName {
            get {
                return this.CategoryNameField;
            }
            set {
                if ((object.ReferenceEquals(this.CategoryNameField, value) != true)) {
                    this.CategoryNameField = value;
                    this.RaisePropertyChanged("CategoryName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ClassID {
            get {
                return this.ClassIDField;
            }
            set {
                if ((this.ClassIDField.Equals(value) != true)) {
                    this.ClassIDField = value;
                    this.RaisePropertyChanged("ClassID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ClassName {
            get {
                return this.ClassNameField;
            }
            set {
                if ((object.ReferenceEquals(this.ClassNameField, value) != true)) {
                    this.ClassNameField = value;
                    this.RaisePropertyChanged("ClassName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Code {
            get {
                return this.CodeField;
            }
            set {
                if ((object.ReferenceEquals(this.CodeField, value) != true)) {
                    this.CodeField = value;
                    this.RaisePropertyChanged("Code");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Comment {
            get {
                return this.CommentField;
            }
            set {
                if ((object.ReferenceEquals(this.CommentField, value) != true)) {
                    this.CommentField = value;
                    this.RaisePropertyChanged("Comment");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CommitStatus {
            get {
                return this.CommitStatusField;
            }
            set {
                if ((this.CommitStatusField.Equals(value) != true)) {
                    this.CommitStatusField = value;
                    this.RaisePropertyChanged("CommitStatus");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Content {
            get {
                return this.ContentField;
            }
            set {
                if ((object.ReferenceEquals(this.ContentField, value) != true)) {
                    this.ContentField = value;
                    this.RaisePropertyChanged("Content");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Keyword {
            get {
                return this.KeywordField;
            }
            set {
                if ((object.ReferenceEquals(this.KeywordField, value) != true)) {
                    this.KeywordField = value;
                    this.RaisePropertyChanged("Keyword");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal MarketPrice {
            get {
                return this.MarketPriceField;
            }
            set {
                if ((this.MarketPriceField.Equals(value) != true)) {
                    this.MarketPriceField = value;
                    this.RaisePropertyChanged("MarketPrice");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> OffDate {
            get {
                return this.OffDateField;
            }
            set {
                if ((this.OffDateField.Equals(value) != true)) {
                    this.OffDateField = value;
                    this.RaisePropertyChanged("OffDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> OffOperatorID {
            get {
                return this.OffOperatorIDField;
            }
            set {
                if ((this.OffOperatorIDField.Equals(value) != true)) {
                    this.OffOperatorIDField = value;
                    this.RaisePropertyChanged("OffOperatorID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> OnDate {
            get {
                return this.OnDateField;
            }
            set {
                if ((this.OnDateField.Equals(value) != true)) {
                    this.OnDateField = value;
                    this.RaisePropertyChanged("OnDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> OnOperatorID {
            get {
                return this.OnOperatorIDField;
            }
            set {
                if ((this.OnOperatorIDField.Equals(value) != true)) {
                    this.OnOperatorIDField = value;
                    this.RaisePropertyChanged("OnOperatorID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ParentClassID {
            get {
                return this.ParentClassIDField;
            }
            set {
                if ((this.ParentClassIDField.Equals(value) != true)) {
                    this.ParentClassIDField = value;
                    this.RaisePropertyChanged("ParentClassID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ParentClassName {
            get {
                return this.ParentClassNameField;
            }
            set {
                if ((object.ReferenceEquals(this.ParentClassNameField, value) != true)) {
                    this.ParentClassNameField = value;
                    this.RaisePropertyChanged("ParentClassName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal SalesPrice {
            get {
                return this.SalesPriceField;
            }
            set {
                if ((this.SalesPriceField.Equals(value) != true)) {
                    this.SalesPriceField = value;
                    this.RaisePropertyChanged("SalesPrice");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Site {
            get {
                return this.SiteField;
            }
            set {
                if ((this.SiteField.Equals(value) != true)) {
                    this.SiteField = value;
                    this.RaisePropertyChanged("Site");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> SubmitDate {
            get {
                return this.SubmitDateField;
            }
            set {
                if ((this.SubmitDateField.Equals(value) != true)) {
                    this.SubmitDateField = value;
                    this.RaisePropertyChanged("SubmitDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> SubmitOperatorID {
            get {
                return this.SubmitOperatorIDField;
            }
            set {
                if ((this.SubmitOperatorIDField.Equals(value) != true)) {
                    this.SubmitOperatorIDField = value;
                    this.RaisePropertyChanged("SubmitOperatorID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Type {
            get {
                return this.TypeField;
            }
            set {
                if ((this.TypeField.Equals(value) != true)) {
                    this.TypeField = value;
                    this.RaisePropertyChanged("Type");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int VerifyStatus {
            get {
                return this.VerifyStatusField;
            }
            set {
                if ((this.VerifyStatusField.Equals(value) != true)) {
                    this.VerifyStatusField = value;
                    this.RaisePropertyChanged("VerifyStatus");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string WebName {
            get {
                return this.WebNameField;
            }
            set {
                if ((object.ReferenceEquals(this.WebNameField, value) != true)) {
                    this.WebNameField = value;
                    this.RaisePropertyChanged("WebName");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Wash_ProductAttributeDC", Namespace="http://schemas.datacontract.org/2004/07/LazyAtHome.WCF.Wash.Contract.DataContract" +
        "")]
    [System.SerializableAttribute()]
    public partial class Wash_ProductAttributeDC : LazyAtHome.WCF.WebService.Console_Client.WashProductService.EntityBase {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int AttributeIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AttributeNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ContentField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int DefaultField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ParentAttributeIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal PriceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ProductIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int SelectedField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int AttributeID {
            get {
                return this.AttributeIDField;
            }
            set {
                if ((this.AttributeIDField.Equals(value) != true)) {
                    this.AttributeIDField = value;
                    this.RaisePropertyChanged("AttributeID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AttributeName {
            get {
                return this.AttributeNameField;
            }
            set {
                if ((object.ReferenceEquals(this.AttributeNameField, value) != true)) {
                    this.AttributeNameField = value;
                    this.RaisePropertyChanged("AttributeName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Content {
            get {
                return this.ContentField;
            }
            set {
                if ((object.ReferenceEquals(this.ContentField, value) != true)) {
                    this.ContentField = value;
                    this.RaisePropertyChanged("Content");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Default {
            get {
                return this.DefaultField;
            }
            set {
                if ((this.DefaultField.Equals(value) != true)) {
                    this.DefaultField = value;
                    this.RaisePropertyChanged("Default");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ParentAttributeID {
            get {
                return this.ParentAttributeIDField;
            }
            set {
                if ((this.ParentAttributeIDField.Equals(value) != true)) {
                    this.ParentAttributeIDField = value;
                    this.RaisePropertyChanged("ParentAttributeID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Price {
            get {
                return this.PriceField;
            }
            set {
                if ((this.PriceField.Equals(value) != true)) {
                    this.PriceField = value;
                    this.RaisePropertyChanged("Price");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ProductID {
            get {
                return this.ProductIDField;
            }
            set {
                if ((this.ProductIDField.Equals(value) != true)) {
                    this.ProductIDField = value;
                    this.RaisePropertyChanged("ProductID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Selected {
            get {
                return this.SelectedField;
            }
            set {
                if ((this.SelectedField.Equals(value) != true)) {
                    this.SelectedField = value;
                    this.RaisePropertyChanged("Selected");
                }
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UpdateModel", Namespace="http://schemas.datacontract.org/2004/07/LazyAtHome.Core.Enumerate")]
    public enum UpdateModel : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Insert = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Update = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Delete = 2,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UpdateParamEntity", Namespace="http://schemas.datacontract.org/2004/07/LazyAtHome.Core.Infrastructure.WCF")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(LazyAtHome.WCF.WebService.Console_Client.WashProductService.Wash_ClassDC[]))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(LazyAtHome.WCF.WebService.Console_Client.WashProductService.Wash_ClassDC))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(LazyAtHome.WCF.WebService.Console_Client.WashProductService.Wash_ProductDC[]))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(LazyAtHome.WCF.WebService.Console_Client.WashProductService.Wash_ProductDC))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(LazyAtHome.WCF.WebService.Console_Client.WashProductService.Wash_ProductAttributeDC[]))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(LazyAtHome.WCF.WebService.Console_Client.WashProductService.Wash_ProductAttributeDC))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(System.DBNull))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(LazyAtHome.WCF.WebService.Console_Client.WashProductService.OperatorType))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(LazyAtHome.WCF.WebService.Console_Client.WashProductService.ReturnEntityOfArrayOfWash_ClassDC0nVOtipR))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(LazyAtHome.WCF.WebService.Console_Client.WashProductService.EntityBase))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(LazyAtHome.WCF.WebService.Console_Client.WashProductService.UpdateParamEntity[]))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(LazyAtHome.WCF.WebService.Console_Client.WashProductService.ReturnEntityOfArrayOfWash_ProductDC0nVOtipR))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(System.Data.DbType))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(LazyAtHome.WCF.WebService.Console_Client.WashProductService.UpdateModel))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(LazyAtHome.WCF.WebService.Console_Client.WashProductService.LoginCredentials))]
    public partial class UpdateParamEntity : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Data.DbType DbTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsPrimaryKeyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private object NewValueField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private object OldValueField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Data.DbType DbType {
            get {
                return this.DbTypeField;
            }
            set {
                if ((this.DbTypeField.Equals(value) != true)) {
                    this.DbTypeField = value;
                    this.RaisePropertyChanged("DbType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsPrimaryKey {
            get {
                return this.IsPrimaryKeyField;
            }
            set {
                if ((this.IsPrimaryKeyField.Equals(value) != true)) {
                    this.IsPrimaryKeyField = value;
                    this.RaisePropertyChanged("IsPrimaryKey");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public object NewValue {
            get {
                return this.NewValueField;
            }
            set {
                if ((object.ReferenceEquals(this.NewValueField, value) != true)) {
                    this.NewValueField = value;
                    this.RaisePropertyChanged("NewValue");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public object OldValue {
            get {
                return this.OldValueField;
            }
            set {
                if ((object.ReferenceEquals(this.OldValueField, value) != true)) {
                    this.OldValueField = value;
                    this.RaisePropertyChanged("OldValue");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ReturnEntityOfArrayOfWash_ProductDC0nVOtipR", Namespace="http://schemas.datacontract.org/2004/07/LazyAtHome.Core.Infrastructure.WCF")]
    [System.SerializableAttribute()]
    public partial class ReturnEntityOfArrayOfWash_ProductDC0nVOtipR : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private LazyAtHome.WCF.WebService.Console_Client.WashProductService.Wash_ProductDC[] OBJField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TitleField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Code {
            get {
                return this.CodeField;
            }
            set {
                if ((this.CodeField.Equals(value) != true)) {
                    this.CodeField = value;
                    this.RaisePropertyChanged("Code");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public LazyAtHome.WCF.WebService.Console_Client.WashProductService.Wash_ProductDC[] OBJ {
            get {
                return this.OBJField;
            }
            set {
                if ((object.ReferenceEquals(this.OBJField, value) != true)) {
                    this.OBJField = value;
                    this.RaisePropertyChanged("OBJ");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Title {
            get {
                return this.TitleField;
            }
            set {
                if ((object.ReferenceEquals(this.TitleField, value) != true)) {
                    this.TitleField = value;
                    this.RaisePropertyChanged("Title");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WashProductService.IWashProduct", SessionMode=System.ServiceModel.SessionMode.Required)]
    public interface IWashProduct {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWashProduct/Wash_Class_SELECT_List_Second", ReplyAction="http://tempuri.org/IWashProduct/Wash_Class_SELECT_List_SecondResponse")]
        LazyAtHome.WCF.WebService.Console_Client.WashProductService.ReturnEntityOfArrayOfWash_ClassDC0nVOtipR Wash_Class_SELECT_List_Second(LazyAtHome.WCF.WebService.Console_Client.WashProductService.LoginCredentials iCredentials);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWashProduct/Wash_Class_SELECT_List_Second", ReplyAction="http://tempuri.org/IWashProduct/Wash_Class_SELECT_List_SecondResponse")]
        System.Threading.Tasks.Task<LazyAtHome.WCF.WebService.Console_Client.WashProductService.ReturnEntityOfArrayOfWash_ClassDC0nVOtipR> Wash_Class_SELECT_List_SecondAsync(LazyAtHome.WCF.WebService.Console_Client.WashProductService.LoginCredentials iCredentials);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWashProduct/Wash_Product_SELECT_List", ReplyAction="http://tempuri.org/IWashProduct/Wash_Product_SELECT_ListResponse")]
        LazyAtHome.WCF.WebService.Console_Client.WashProductService.ReturnEntityOfArrayOfWash_ProductDC0nVOtipR Wash_Product_SELECT_List(LazyAtHome.WCF.WebService.Console_Client.WashProductService.LoginCredentials iCredentials);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWashProduct/Wash_Product_SELECT_List", ReplyAction="http://tempuri.org/IWashProduct/Wash_Product_SELECT_ListResponse")]
        System.Threading.Tasks.Task<LazyAtHome.WCF.WebService.Console_Client.WashProductService.ReturnEntityOfArrayOfWash_ProductDC0nVOtipR> Wash_Product_SELECT_ListAsync(LazyAtHome.WCF.WebService.Console_Client.WashProductService.LoginCredentials iCredentials);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IWashProductChannel : LazyAtHome.WCF.WebService.Console_Client.WashProductService.IWashProduct, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WashProductClient : System.ServiceModel.ClientBase<LazyAtHome.WCF.WebService.Console_Client.WashProductService.IWashProduct>, LazyAtHome.WCF.WebService.Console_Client.WashProductService.IWashProduct {
        
        public WashProductClient() {
        }
        
        public WashProductClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WashProductClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WashProductClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WashProductClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public LazyAtHome.WCF.WebService.Console_Client.WashProductService.ReturnEntityOfArrayOfWash_ClassDC0nVOtipR Wash_Class_SELECT_List_Second(LazyAtHome.WCF.WebService.Console_Client.WashProductService.LoginCredentials iCredentials) {
            return base.Channel.Wash_Class_SELECT_List_Second(iCredentials);
        }
        
        public System.Threading.Tasks.Task<LazyAtHome.WCF.WebService.Console_Client.WashProductService.ReturnEntityOfArrayOfWash_ClassDC0nVOtipR> Wash_Class_SELECT_List_SecondAsync(LazyAtHome.WCF.WebService.Console_Client.WashProductService.LoginCredentials iCredentials) {
            return base.Channel.Wash_Class_SELECT_List_SecondAsync(iCredentials);
        }
        
        public LazyAtHome.WCF.WebService.Console_Client.WashProductService.ReturnEntityOfArrayOfWash_ProductDC0nVOtipR Wash_Product_SELECT_List(LazyAtHome.WCF.WebService.Console_Client.WashProductService.LoginCredentials iCredentials) {
            return base.Channel.Wash_Product_SELECT_List(iCredentials);
        }
        
        public System.Threading.Tasks.Task<LazyAtHome.WCF.WebService.Console_Client.WashProductService.ReturnEntityOfArrayOfWash_ProductDC0nVOtipR> Wash_Product_SELECT_ListAsync(LazyAtHome.WCF.WebService.Console_Client.WashProductService.LoginCredentials iCredentials) {
            return base.Channel.Wash_Product_SELECT_ListAsync(iCredentials);
        }
    }
}
