//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.34014
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LazyAtHome.Service.SMS.YiMeiService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://sdkhttp.eucp.b2m.cn/", ConfigurationName="YiMeiService.SDKClient")]
    public interface SDKClient {
        
        // CODEGEN: 参数“return”需要其他方案信息，使用参数模式无法捕获这些信息。特定特性为“System.Xml.Serialization.XmlElementAttribute”。
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        LazyAtHome.Service.SMS.YiMeiService.getVersionResponse getVersion(LazyAtHome.Service.SMS.YiMeiService.getVersionRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<LazyAtHome.Service.SMS.YiMeiService.getVersionResponse> getVersionAsync(LazyAtHome.Service.SMS.YiMeiService.getVersionRequest request);
        
        // CODEGEN: 参数“return”需要其他方案信息，使用参数模式无法捕获这些信息。特定特性为“System.Xml.Serialization.XmlElementAttribute”。
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        LazyAtHome.Service.SMS.YiMeiService.getReportResponse getReport(LazyAtHome.Service.SMS.YiMeiService.getReportRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<LazyAtHome.Service.SMS.YiMeiService.getReportResponse> getReportAsync(LazyAtHome.Service.SMS.YiMeiService.getReportRequest request);
        
        // CODEGEN: 参数“return”需要其他方案信息，使用参数模式无法捕获这些信息。特定特性为“System.Xml.Serialization.XmlElementAttribute”。
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        LazyAtHome.Service.SMS.YiMeiService.cancelMOForwardResponse cancelMOForward(LazyAtHome.Service.SMS.YiMeiService.cancelMOForwardRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<LazyAtHome.Service.SMS.YiMeiService.cancelMOForwardResponse> cancelMOForwardAsync(LazyAtHome.Service.SMS.YiMeiService.cancelMOForwardRequest request);
        
        // CODEGEN: 参数“return”需要其他方案信息，使用参数模式无法捕获这些信息。特定特性为“System.Xml.Serialization.XmlElementAttribute”。
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        LazyAtHome.Service.SMS.YiMeiService.chargeUpResponse chargeUp(LazyAtHome.Service.SMS.YiMeiService.chargeUpRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<LazyAtHome.Service.SMS.YiMeiService.chargeUpResponse> chargeUpAsync(LazyAtHome.Service.SMS.YiMeiService.chargeUpRequest request);
        
        // CODEGEN: 参数“return”需要其他方案信息，使用参数模式无法捕获这些信息。特定特性为“System.Xml.Serialization.XmlElementAttribute”。
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        LazyAtHome.Service.SMS.YiMeiService.getBalanceResponse getBalance(LazyAtHome.Service.SMS.YiMeiService.getBalanceRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<LazyAtHome.Service.SMS.YiMeiService.getBalanceResponse> getBalanceAsync(LazyAtHome.Service.SMS.YiMeiService.getBalanceRequest request);
        
        // CODEGEN: 参数“return”需要其他方案信息，使用参数模式无法捕获这些信息。特定特性为“System.Xml.Serialization.XmlElementAttribute”。
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        LazyAtHome.Service.SMS.YiMeiService.getEachFeeResponse getEachFee(LazyAtHome.Service.SMS.YiMeiService.getEachFeeRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<LazyAtHome.Service.SMS.YiMeiService.getEachFeeResponse> getEachFeeAsync(LazyAtHome.Service.SMS.YiMeiService.getEachFeeRequest request);
        
        // CODEGEN: 参数“return”需要其他方案信息，使用参数模式无法捕获这些信息。特定特性为“System.Xml.Serialization.XmlElementAttribute”。
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        LazyAtHome.Service.SMS.YiMeiService.getMOResponse getMO(LazyAtHome.Service.SMS.YiMeiService.getMORequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<LazyAtHome.Service.SMS.YiMeiService.getMOResponse> getMOAsync(LazyAtHome.Service.SMS.YiMeiService.getMORequest request);
        
        // CODEGEN: 参数“return”需要其他方案信息，使用参数模式无法捕获这些信息。特定特性为“System.Xml.Serialization.XmlElementAttribute”。
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        LazyAtHome.Service.SMS.YiMeiService.logoutResponse logout(LazyAtHome.Service.SMS.YiMeiService.logoutRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<LazyAtHome.Service.SMS.YiMeiService.logoutResponse> logoutAsync(LazyAtHome.Service.SMS.YiMeiService.logoutRequest request);
        
        // CODEGEN: 参数“return”需要其他方案信息，使用参数模式无法捕获这些信息。特定特性为“System.Xml.Serialization.XmlElementAttribute”。
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        LazyAtHome.Service.SMS.YiMeiService.registDetailInfoResponse registDetailInfo(LazyAtHome.Service.SMS.YiMeiService.registDetailInfoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<LazyAtHome.Service.SMS.YiMeiService.registDetailInfoResponse> registDetailInfoAsync(LazyAtHome.Service.SMS.YiMeiService.registDetailInfoRequest request);
        
        // CODEGEN: 参数“return”需要其他方案信息，使用参数模式无法捕获这些信息。特定特性为“System.Xml.Serialization.XmlElementAttribute”。
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        LazyAtHome.Service.SMS.YiMeiService.registExResponse registEx(LazyAtHome.Service.SMS.YiMeiService.registExRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<LazyAtHome.Service.SMS.YiMeiService.registExResponse> registExAsync(LazyAtHome.Service.SMS.YiMeiService.registExRequest request);
        
        // CODEGEN: 参数“return”需要其他方案信息，使用参数模式无法捕获这些信息。特定特性为“System.Xml.Serialization.XmlElementAttribute”。
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        LazyAtHome.Service.SMS.YiMeiService.sendSMSResponse sendSMS(LazyAtHome.Service.SMS.YiMeiService.sendSMSRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<LazyAtHome.Service.SMS.YiMeiService.sendSMSResponse> sendSMSAsync(LazyAtHome.Service.SMS.YiMeiService.sendSMSRequest request);
        
        // CODEGEN: 参数“return”需要其他方案信息，使用参数模式无法捕获这些信息。特定特性为“System.Xml.Serialization.XmlElementAttribute”。
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        LazyAtHome.Service.SMS.YiMeiService.sendVoiceResponse sendVoice(LazyAtHome.Service.SMS.YiMeiService.sendVoiceRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<LazyAtHome.Service.SMS.YiMeiService.sendVoiceResponse> sendVoiceAsync(LazyAtHome.Service.SMS.YiMeiService.sendVoiceRequest request);
        
        // CODEGEN: 参数“return”需要其他方案信息，使用参数模式无法捕获这些信息。特定特性为“System.Xml.Serialization.XmlElementAttribute”。
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        LazyAtHome.Service.SMS.YiMeiService.serialPwdUpdResponse serialPwdUpd(LazyAtHome.Service.SMS.YiMeiService.serialPwdUpdRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<LazyAtHome.Service.SMS.YiMeiService.serialPwdUpdResponse> serialPwdUpdAsync(LazyAtHome.Service.SMS.YiMeiService.serialPwdUpdRequest request);
        
        // CODEGEN: 参数“return”需要其他方案信息，使用参数模式无法捕获这些信息。特定特性为“System.Xml.Serialization.XmlElementAttribute”。
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        LazyAtHome.Service.SMS.YiMeiService.setMOForwardResponse setMOForward(LazyAtHome.Service.SMS.YiMeiService.setMOForwardRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<LazyAtHome.Service.SMS.YiMeiService.setMOForwardResponse> setMOForwardAsync(LazyAtHome.Service.SMS.YiMeiService.setMOForwardRequest request);
        
        // CODEGEN: 参数“return”需要其他方案信息，使用参数模式无法捕获这些信息。特定特性为“System.Xml.Serialization.XmlElementAttribute”。
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        LazyAtHome.Service.SMS.YiMeiService.setMOForwardExResponse setMOForwardEx(LazyAtHome.Service.SMS.YiMeiService.setMOForwardExRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<LazyAtHome.Service.SMS.YiMeiService.setMOForwardExResponse> setMOForwardExAsync(LazyAtHome.Service.SMS.YiMeiService.setMOForwardExRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getVersion", WrapperNamespace="http://sdkhttp.eucp.b2m.cn/", IsWrapped=true)]
    public partial class getVersionRequest {
        
        public getVersionRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getVersionResponse", WrapperNamespace="http://sdkhttp.eucp.b2m.cn/", IsWrapped=true)]
    public partial class getVersionResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sdkhttp.eucp.b2m.cn/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string @return;
        
        public getVersionResponse() {
        }
        
        public getVersionResponse(string @return) {
            this.@return = @return;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://sdkhttp.eucp.b2m.cn/")]
    public partial class statusReport : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string errorCodeField;
        
        private string memoField;
        
        private string mobileField;
        
        private string receiveDateField;
        
        private int reportStatusField;
        
        private long seqIDField;
        
        private string serviceCodeAddField;
        
        private string submitDateField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string errorCode {
            get {
                return this.errorCodeField;
            }
            set {
                this.errorCodeField = value;
                this.RaisePropertyChanged("errorCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string memo {
            get {
                return this.memoField;
            }
            set {
                this.memoField = value;
                this.RaisePropertyChanged("memo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string mobile {
            get {
                return this.mobileField;
            }
            set {
                this.mobileField = value;
                this.RaisePropertyChanged("mobile");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string receiveDate {
            get {
                return this.receiveDateField;
            }
            set {
                this.receiveDateField = value;
                this.RaisePropertyChanged("receiveDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public int reportStatus {
            get {
                return this.reportStatusField;
            }
            set {
                this.reportStatusField = value;
                this.RaisePropertyChanged("reportStatus");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public long seqID {
            get {
                return this.seqIDField;
            }
            set {
                this.seqIDField = value;
                this.RaisePropertyChanged("seqID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string serviceCodeAdd {
            get {
                return this.serviceCodeAddField;
            }
            set {
                this.serviceCodeAddField = value;
                this.RaisePropertyChanged("serviceCodeAdd");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string submitDate {
            get {
                return this.submitDateField;
            }
            set {
                this.submitDateField = value;
                this.RaisePropertyChanged("submitDate");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://sdkhttp.eucp.b2m.cn/")]
    public partial class mo : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string addSerialField;
        
        private string addSerialRevField;
        
        private string channelnumberField;
        
        private string mobileNumberField;
        
        private string sentTimeField;
        
        private string smsContentField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string addSerial {
            get {
                return this.addSerialField;
            }
            set {
                this.addSerialField = value;
                this.RaisePropertyChanged("addSerial");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string addSerialRev {
            get {
                return this.addSerialRevField;
            }
            set {
                this.addSerialRevField = value;
                this.RaisePropertyChanged("addSerialRev");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string channelnumber {
            get {
                return this.channelnumberField;
            }
            set {
                this.channelnumberField = value;
                this.RaisePropertyChanged("channelnumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string mobileNumber {
            get {
                return this.mobileNumberField;
            }
            set {
                this.mobileNumberField = value;
                this.RaisePropertyChanged("mobileNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string sentTime {
            get {
                return this.sentTimeField;
            }
            set {
                this.sentTimeField = value;
                this.RaisePropertyChanged("sentTime");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string smsContent {
            get {
                return this.smsContentField;
            }
            set {
                this.smsContentField = value;
                this.RaisePropertyChanged("smsContent");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getReport", WrapperNamespace="http://sdkhttp.eucp.b2m.cn/", IsWrapped=true)]
    public partial class getReportRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sdkhttp.eucp.b2m.cn/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string arg0;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sdkhttp.eucp.b2m.cn/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string arg1;
        
        public getReportRequest() {
        }
        
        public getReportRequest(string arg0, string arg1) {
            this.arg0 = arg0;
            this.arg1 = arg1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getReportResponse", WrapperNamespace="http://sdkhttp.eucp.b2m.cn/", IsWrapped=true)]
    public partial class getReportResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sdkhttp.eucp.b2m.cn/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public LazyAtHome.Service.SMS.YiMeiService.statusReport[] @return;
        
        public getReportResponse() {
        }
        
        public getReportResponse(LazyAtHome.Service.SMS.YiMeiService.statusReport[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="cancelMOForward", WrapperNamespace="http://sdkhttp.eucp.b2m.cn/", IsWrapped=true)]
    public partial class cancelMOForwardRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sdkhttp.eucp.b2m.cn/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string arg0;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sdkhttp.eucp.b2m.cn/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string arg1;
        
        public cancelMOForwardRequest() {
        }
        
        public cancelMOForwardRequest(string arg0, string arg1) {
            this.arg0 = arg0;
            this.arg1 = arg1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="cancelMOForwardResponse", WrapperNamespace="http://sdkhttp.eucp.b2m.cn/", IsWrapped=true)]
    public partial class cancelMOForwardResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sdkhttp.eucp.b2m.cn/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public cancelMOForwardResponse() {
        }
        
        public cancelMOForwardResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="chargeUp", WrapperNamespace="http://sdkhttp.eucp.b2m.cn/", IsWrapped=true)]
    public partial class chargeUpRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sdkhttp.eucp.b2m.cn/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string arg0;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sdkhttp.eucp.b2m.cn/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string arg1;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sdkhttp.eucp.b2m.cn/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string arg2;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sdkhttp.eucp.b2m.cn/", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string arg3;
        
        public chargeUpRequest() {
        }
        
        public chargeUpRequest(string arg0, string arg1, string arg2, string arg3) {
            this.arg0 = arg0;
            this.arg1 = arg1;
            this.arg2 = arg2;
            this.arg3 = arg3;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="chargeUpResponse", WrapperNamespace="http://sdkhttp.eucp.b2m.cn/", IsWrapped=true)]
    public partial class chargeUpResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sdkhttp.eucp.b2m.cn/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public chargeUpResponse() {
        }
        
        public chargeUpResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getBalance", WrapperNamespace="http://sdkhttp.eucp.b2m.cn/", IsWrapped=true)]
    public partial class getBalanceRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sdkhttp.eucp.b2m.cn/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string arg0;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sdkhttp.eucp.b2m.cn/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string arg1;
        
        public getBalanceRequest() {
        }
        
        public getBalanceRequest(string arg0, string arg1) {
            this.arg0 = arg0;
            this.arg1 = arg1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getBalanceResponse", WrapperNamespace="http://sdkhttp.eucp.b2m.cn/", IsWrapped=true)]
    public partial class getBalanceResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sdkhttp.eucp.b2m.cn/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public double @return;
        
        public getBalanceResponse() {
        }
        
        public getBalanceResponse(double @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getEachFee", WrapperNamespace="http://sdkhttp.eucp.b2m.cn/", IsWrapped=true)]
    public partial class getEachFeeRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sdkhttp.eucp.b2m.cn/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string arg0;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sdkhttp.eucp.b2m.cn/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string arg1;
        
        public getEachFeeRequest() {
        }
        
        public getEachFeeRequest(string arg0, string arg1) {
            this.arg0 = arg0;
            this.arg1 = arg1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getEachFeeResponse", WrapperNamespace="http://sdkhttp.eucp.b2m.cn/", IsWrapped=true)]
    public partial class getEachFeeResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sdkhttp.eucp.b2m.cn/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public double @return;
        
        public getEachFeeResponse() {
        }
        
        public getEachFeeResponse(double @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getMO", WrapperNamespace="http://sdkhttp.eucp.b2m.cn/", IsWrapped=true)]
    public partial class getMORequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sdkhttp.eucp.b2m.cn/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string arg0;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sdkhttp.eucp.b2m.cn/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string arg1;
        
        public getMORequest() {
        }
        
        public getMORequest(string arg0, string arg1) {
            this.arg0 = arg0;
            this.arg1 = arg1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getMOResponse", WrapperNamespace="http://sdkhttp.eucp.b2m.cn/", IsWrapped=true)]
    public partial class getMOResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sdkhttp.eucp.b2m.cn/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public LazyAtHome.Service.SMS.YiMeiService.mo[] @return;
        
        public getMOResponse() {
        }
        
        public getMOResponse(LazyAtHome.Service.SMS.YiMeiService.mo[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="logout", WrapperNamespace="http://sdkhttp.eucp.b2m.cn/", IsWrapped=true)]
    public partial class logoutRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sdkhttp.eucp.b2m.cn/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string arg0;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sdkhttp.eucp.b2m.cn/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string arg1;
        
        public logoutRequest() {
        }
        
        public logoutRequest(string arg0, string arg1) {
            this.arg0 = arg0;
            this.arg1 = arg1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="logoutResponse", WrapperNamespace="http://sdkhttp.eucp.b2m.cn/", IsWrapped=true)]
    public partial class logoutResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sdkhttp.eucp.b2m.cn/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public logoutResponse() {
        }
        
        public logoutResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="registDetailInfo", WrapperNamespace="http://sdkhttp.eucp.b2m.cn/", IsWrapped=true)]
    public partial class registDetailInfoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sdkhttp.eucp.b2m.cn/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string arg0;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sdkhttp.eucp.b2m.cn/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string arg1;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sdkhttp.eucp.b2m.cn/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string arg2;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sdkhttp.eucp.b2m.cn/", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string arg3;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sdkhttp.eucp.b2m.cn/", Order=4)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string arg4;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sdkhttp.eucp.b2m.cn/", Order=5)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string arg5;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sdkhttp.eucp.b2m.cn/", Order=6)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string arg6;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sdkhttp.eucp.b2m.cn/", Order=7)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string arg7;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sdkhttp.eucp.b2m.cn/", Order=8)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string arg8;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sdkhttp.eucp.b2m.cn/", Order=9)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string arg9;
        
        public registDetailInfoRequest() {
        }
        
        public registDetailInfoRequest(string arg0, string arg1, string arg2, string arg3, string arg4, string arg5, string arg6, string arg7, string arg8, string arg9) {
            this.arg0 = arg0;
            this.arg1 = arg1;
            this.arg2 = arg2;
            this.arg3 = arg3;
            this.arg4 = arg4;
            this.arg5 = arg5;
            this.arg6 = arg6;
            this.arg7 = arg7;
            this.arg8 = arg8;
            this.arg9 = arg9;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="registDetailInfoResponse", WrapperNamespace="http://sdkhttp.eucp.b2m.cn/", IsWrapped=true)]
    public partial class registDetailInfoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sdkhttp.eucp.b2m.cn/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public registDetailInfoResponse() {
        }
        
        public registDetailInfoResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="registEx", WrapperNamespace="http://sdkhttp.eucp.b2m.cn/", IsWrapped=true)]
    public partial class registExRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sdkhttp.eucp.b2m.cn/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string arg0;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sdkhttp.eucp.b2m.cn/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string arg1;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sdkhttp.eucp.b2m.cn/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string arg2;
        
        public registExRequest() {
        }
        
        public registExRequest(string arg0, string arg1, string arg2) {
            this.arg0 = arg0;
            this.arg1 = arg1;
            this.arg2 = arg2;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="registExResponse", WrapperNamespace="http://sdkhttp.eucp.b2m.cn/", IsWrapped=true)]
    public partial class registExResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sdkhttp.eucp.b2m.cn/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public registExResponse() {
        }
        
        public registExResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="sendSMS", WrapperNamespace="http://sdkhttp.eucp.b2m.cn/", IsWrapped=true)]
    public partial class sendSMSRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sdkhttp.eucp.b2m.cn/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string arg0;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sdkhttp.eucp.b2m.cn/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string arg1;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sdkhttp.eucp.b2m.cn/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string arg2;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sdkhttp.eucp.b2m.cn/", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute("arg3", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string[] arg3;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sdkhttp.eucp.b2m.cn/", Order=4)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string arg4;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sdkhttp.eucp.b2m.cn/", Order=5)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string arg5;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sdkhttp.eucp.b2m.cn/", Order=6)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string arg6;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sdkhttp.eucp.b2m.cn/", Order=7)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int arg7;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sdkhttp.eucp.b2m.cn/", Order=8)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long arg8;
        
        public sendSMSRequest() {
        }
        
        public sendSMSRequest(string arg0, string arg1, string arg2, string[] arg3, string arg4, string arg5, string arg6, int arg7, long arg8) {
            this.arg0 = arg0;
            this.arg1 = arg1;
            this.arg2 = arg2;
            this.arg3 = arg3;
            this.arg4 = arg4;
            this.arg5 = arg5;
            this.arg6 = arg6;
            this.arg7 = arg7;
            this.arg8 = arg8;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="sendSMSResponse", WrapperNamespace="http://sdkhttp.eucp.b2m.cn/", IsWrapped=true)]
    public partial class sendSMSResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sdkhttp.eucp.b2m.cn/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public sendSMSResponse() {
        }
        
        public sendSMSResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="sendVoice", WrapperNamespace="http://sdkhttp.eucp.b2m.cn/", IsWrapped=true)]
    public partial class sendVoiceRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sdkhttp.eucp.b2m.cn/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string arg0;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sdkhttp.eucp.b2m.cn/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string arg1;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sdkhttp.eucp.b2m.cn/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string arg2;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sdkhttp.eucp.b2m.cn/", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute("arg3", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string[] arg3;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sdkhttp.eucp.b2m.cn/", Order=4)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string arg4;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sdkhttp.eucp.b2m.cn/", Order=5)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string arg5;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sdkhttp.eucp.b2m.cn/", Order=6)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string arg6;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sdkhttp.eucp.b2m.cn/", Order=7)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int arg7;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sdkhttp.eucp.b2m.cn/", Order=8)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long arg8;
        
        public sendVoiceRequest() {
        }
        
        public sendVoiceRequest(string arg0, string arg1, string arg2, string[] arg3, string arg4, string arg5, string arg6, int arg7, long arg8) {
            this.arg0 = arg0;
            this.arg1 = arg1;
            this.arg2 = arg2;
            this.arg3 = arg3;
            this.arg4 = arg4;
            this.arg5 = arg5;
            this.arg6 = arg6;
            this.arg7 = arg7;
            this.arg8 = arg8;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="sendVoiceResponse", WrapperNamespace="http://sdkhttp.eucp.b2m.cn/", IsWrapped=true)]
    public partial class sendVoiceResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sdkhttp.eucp.b2m.cn/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string @return;
        
        public sendVoiceResponse() {
        }
        
        public sendVoiceResponse(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="serialPwdUpd", WrapperNamespace="http://sdkhttp.eucp.b2m.cn/", IsWrapped=true)]
    public partial class serialPwdUpdRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sdkhttp.eucp.b2m.cn/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string arg0;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sdkhttp.eucp.b2m.cn/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string arg1;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sdkhttp.eucp.b2m.cn/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string arg2;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sdkhttp.eucp.b2m.cn/", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string arg3;
        
        public serialPwdUpdRequest() {
        }
        
        public serialPwdUpdRequest(string arg0, string arg1, string arg2, string arg3) {
            this.arg0 = arg0;
            this.arg1 = arg1;
            this.arg2 = arg2;
            this.arg3 = arg3;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="serialPwdUpdResponse", WrapperNamespace="http://sdkhttp.eucp.b2m.cn/", IsWrapped=true)]
    public partial class serialPwdUpdResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sdkhttp.eucp.b2m.cn/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public serialPwdUpdResponse() {
        }
        
        public serialPwdUpdResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="setMOForward", WrapperNamespace="http://sdkhttp.eucp.b2m.cn/", IsWrapped=true)]
    public partial class setMOForwardRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sdkhttp.eucp.b2m.cn/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string arg0;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sdkhttp.eucp.b2m.cn/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string arg1;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sdkhttp.eucp.b2m.cn/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string arg2;
        
        public setMOForwardRequest() {
        }
        
        public setMOForwardRequest(string arg0, string arg1, string arg2) {
            this.arg0 = arg0;
            this.arg1 = arg1;
            this.arg2 = arg2;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="setMOForwardResponse", WrapperNamespace="http://sdkhttp.eucp.b2m.cn/", IsWrapped=true)]
    public partial class setMOForwardResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sdkhttp.eucp.b2m.cn/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public setMOForwardResponse() {
        }
        
        public setMOForwardResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="setMOForwardEx", WrapperNamespace="http://sdkhttp.eucp.b2m.cn/", IsWrapped=true)]
    public partial class setMOForwardExRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sdkhttp.eucp.b2m.cn/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string arg0;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sdkhttp.eucp.b2m.cn/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string arg1;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sdkhttp.eucp.b2m.cn/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute("arg2", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string[] arg2;
        
        public setMOForwardExRequest() {
        }
        
        public setMOForwardExRequest(string arg0, string arg1, string[] arg2) {
            this.arg0 = arg0;
            this.arg1 = arg1;
            this.arg2 = arg2;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="setMOForwardExResponse", WrapperNamespace="http://sdkhttp.eucp.b2m.cn/", IsWrapped=true)]
    public partial class setMOForwardExResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sdkhttp.eucp.b2m.cn/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public setMOForwardExResponse() {
        }
        
        public setMOForwardExResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface SDKClientChannel : LazyAtHome.Service.SMS.YiMeiService.SDKClient, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SDKClientClient : System.ServiceModel.ClientBase<LazyAtHome.Service.SMS.YiMeiService.SDKClient>, LazyAtHome.Service.SMS.YiMeiService.SDKClient {
        
        public SDKClientClient() {
        }
        
        public SDKClientClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SDKClientClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SDKClientClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SDKClientClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        LazyAtHome.Service.SMS.YiMeiService.getVersionResponse LazyAtHome.Service.SMS.YiMeiService.SDKClient.getVersion(LazyAtHome.Service.SMS.YiMeiService.getVersionRequest request) {
            return base.Channel.getVersion(request);
        }
        
        public string getVersion() {
            LazyAtHome.Service.SMS.YiMeiService.getVersionRequest inValue = new LazyAtHome.Service.SMS.YiMeiService.getVersionRequest();
            LazyAtHome.Service.SMS.YiMeiService.getVersionResponse retVal = ((LazyAtHome.Service.SMS.YiMeiService.SDKClient)(this)).getVersion(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<LazyAtHome.Service.SMS.YiMeiService.getVersionResponse> LazyAtHome.Service.SMS.YiMeiService.SDKClient.getVersionAsync(LazyAtHome.Service.SMS.YiMeiService.getVersionRequest request) {
            return base.Channel.getVersionAsync(request);
        }
        
        public System.Threading.Tasks.Task<LazyAtHome.Service.SMS.YiMeiService.getVersionResponse> getVersionAsync() {
            LazyAtHome.Service.SMS.YiMeiService.getVersionRequest inValue = new LazyAtHome.Service.SMS.YiMeiService.getVersionRequest();
            return ((LazyAtHome.Service.SMS.YiMeiService.SDKClient)(this)).getVersionAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        LazyAtHome.Service.SMS.YiMeiService.getReportResponse LazyAtHome.Service.SMS.YiMeiService.SDKClient.getReport(LazyAtHome.Service.SMS.YiMeiService.getReportRequest request) {
            return base.Channel.getReport(request);
        }
        
        public LazyAtHome.Service.SMS.YiMeiService.statusReport[] getReport(string arg0, string arg1) {
            LazyAtHome.Service.SMS.YiMeiService.getReportRequest inValue = new LazyAtHome.Service.SMS.YiMeiService.getReportRequest();
            inValue.arg0 = arg0;
            inValue.arg1 = arg1;
            LazyAtHome.Service.SMS.YiMeiService.getReportResponse retVal = ((LazyAtHome.Service.SMS.YiMeiService.SDKClient)(this)).getReport(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<LazyAtHome.Service.SMS.YiMeiService.getReportResponse> LazyAtHome.Service.SMS.YiMeiService.SDKClient.getReportAsync(LazyAtHome.Service.SMS.YiMeiService.getReportRequest request) {
            return base.Channel.getReportAsync(request);
        }
        
        public System.Threading.Tasks.Task<LazyAtHome.Service.SMS.YiMeiService.getReportResponse> getReportAsync(string arg0, string arg1) {
            LazyAtHome.Service.SMS.YiMeiService.getReportRequest inValue = new LazyAtHome.Service.SMS.YiMeiService.getReportRequest();
            inValue.arg0 = arg0;
            inValue.arg1 = arg1;
            return ((LazyAtHome.Service.SMS.YiMeiService.SDKClient)(this)).getReportAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        LazyAtHome.Service.SMS.YiMeiService.cancelMOForwardResponse LazyAtHome.Service.SMS.YiMeiService.SDKClient.cancelMOForward(LazyAtHome.Service.SMS.YiMeiService.cancelMOForwardRequest request) {
            return base.Channel.cancelMOForward(request);
        }
        
        public int cancelMOForward(string arg0, string arg1) {
            LazyAtHome.Service.SMS.YiMeiService.cancelMOForwardRequest inValue = new LazyAtHome.Service.SMS.YiMeiService.cancelMOForwardRequest();
            inValue.arg0 = arg0;
            inValue.arg1 = arg1;
            LazyAtHome.Service.SMS.YiMeiService.cancelMOForwardResponse retVal = ((LazyAtHome.Service.SMS.YiMeiService.SDKClient)(this)).cancelMOForward(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<LazyAtHome.Service.SMS.YiMeiService.cancelMOForwardResponse> LazyAtHome.Service.SMS.YiMeiService.SDKClient.cancelMOForwardAsync(LazyAtHome.Service.SMS.YiMeiService.cancelMOForwardRequest request) {
            return base.Channel.cancelMOForwardAsync(request);
        }
        
        public System.Threading.Tasks.Task<LazyAtHome.Service.SMS.YiMeiService.cancelMOForwardResponse> cancelMOForwardAsync(string arg0, string arg1) {
            LazyAtHome.Service.SMS.YiMeiService.cancelMOForwardRequest inValue = new LazyAtHome.Service.SMS.YiMeiService.cancelMOForwardRequest();
            inValue.arg0 = arg0;
            inValue.arg1 = arg1;
            return ((LazyAtHome.Service.SMS.YiMeiService.SDKClient)(this)).cancelMOForwardAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        LazyAtHome.Service.SMS.YiMeiService.chargeUpResponse LazyAtHome.Service.SMS.YiMeiService.SDKClient.chargeUp(LazyAtHome.Service.SMS.YiMeiService.chargeUpRequest request) {
            return base.Channel.chargeUp(request);
        }
        
        public int chargeUp(string arg0, string arg1, string arg2, string arg3) {
            LazyAtHome.Service.SMS.YiMeiService.chargeUpRequest inValue = new LazyAtHome.Service.SMS.YiMeiService.chargeUpRequest();
            inValue.arg0 = arg0;
            inValue.arg1 = arg1;
            inValue.arg2 = arg2;
            inValue.arg3 = arg3;
            LazyAtHome.Service.SMS.YiMeiService.chargeUpResponse retVal = ((LazyAtHome.Service.SMS.YiMeiService.SDKClient)(this)).chargeUp(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<LazyAtHome.Service.SMS.YiMeiService.chargeUpResponse> LazyAtHome.Service.SMS.YiMeiService.SDKClient.chargeUpAsync(LazyAtHome.Service.SMS.YiMeiService.chargeUpRequest request) {
            return base.Channel.chargeUpAsync(request);
        }
        
        public System.Threading.Tasks.Task<LazyAtHome.Service.SMS.YiMeiService.chargeUpResponse> chargeUpAsync(string arg0, string arg1, string arg2, string arg3) {
            LazyAtHome.Service.SMS.YiMeiService.chargeUpRequest inValue = new LazyAtHome.Service.SMS.YiMeiService.chargeUpRequest();
            inValue.arg0 = arg0;
            inValue.arg1 = arg1;
            inValue.arg2 = arg2;
            inValue.arg3 = arg3;
            return ((LazyAtHome.Service.SMS.YiMeiService.SDKClient)(this)).chargeUpAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        LazyAtHome.Service.SMS.YiMeiService.getBalanceResponse LazyAtHome.Service.SMS.YiMeiService.SDKClient.getBalance(LazyAtHome.Service.SMS.YiMeiService.getBalanceRequest request) {
            return base.Channel.getBalance(request);
        }
        
        public double getBalance(string arg0, string arg1) {
            LazyAtHome.Service.SMS.YiMeiService.getBalanceRequest inValue = new LazyAtHome.Service.SMS.YiMeiService.getBalanceRequest();
            inValue.arg0 = arg0;
            inValue.arg1 = arg1;
            LazyAtHome.Service.SMS.YiMeiService.getBalanceResponse retVal = ((LazyAtHome.Service.SMS.YiMeiService.SDKClient)(this)).getBalance(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<LazyAtHome.Service.SMS.YiMeiService.getBalanceResponse> LazyAtHome.Service.SMS.YiMeiService.SDKClient.getBalanceAsync(LazyAtHome.Service.SMS.YiMeiService.getBalanceRequest request) {
            return base.Channel.getBalanceAsync(request);
        }
        
        public System.Threading.Tasks.Task<LazyAtHome.Service.SMS.YiMeiService.getBalanceResponse> getBalanceAsync(string arg0, string arg1) {
            LazyAtHome.Service.SMS.YiMeiService.getBalanceRequest inValue = new LazyAtHome.Service.SMS.YiMeiService.getBalanceRequest();
            inValue.arg0 = arg0;
            inValue.arg1 = arg1;
            return ((LazyAtHome.Service.SMS.YiMeiService.SDKClient)(this)).getBalanceAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        LazyAtHome.Service.SMS.YiMeiService.getEachFeeResponse LazyAtHome.Service.SMS.YiMeiService.SDKClient.getEachFee(LazyAtHome.Service.SMS.YiMeiService.getEachFeeRequest request) {
            return base.Channel.getEachFee(request);
        }
        
        public double getEachFee(string arg0, string arg1) {
            LazyAtHome.Service.SMS.YiMeiService.getEachFeeRequest inValue = new LazyAtHome.Service.SMS.YiMeiService.getEachFeeRequest();
            inValue.arg0 = arg0;
            inValue.arg1 = arg1;
            LazyAtHome.Service.SMS.YiMeiService.getEachFeeResponse retVal = ((LazyAtHome.Service.SMS.YiMeiService.SDKClient)(this)).getEachFee(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<LazyAtHome.Service.SMS.YiMeiService.getEachFeeResponse> LazyAtHome.Service.SMS.YiMeiService.SDKClient.getEachFeeAsync(LazyAtHome.Service.SMS.YiMeiService.getEachFeeRequest request) {
            return base.Channel.getEachFeeAsync(request);
        }
        
        public System.Threading.Tasks.Task<LazyAtHome.Service.SMS.YiMeiService.getEachFeeResponse> getEachFeeAsync(string arg0, string arg1) {
            LazyAtHome.Service.SMS.YiMeiService.getEachFeeRequest inValue = new LazyAtHome.Service.SMS.YiMeiService.getEachFeeRequest();
            inValue.arg0 = arg0;
            inValue.arg1 = arg1;
            return ((LazyAtHome.Service.SMS.YiMeiService.SDKClient)(this)).getEachFeeAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        LazyAtHome.Service.SMS.YiMeiService.getMOResponse LazyAtHome.Service.SMS.YiMeiService.SDKClient.getMO(LazyAtHome.Service.SMS.YiMeiService.getMORequest request) {
            return base.Channel.getMO(request);
        }
        
        public LazyAtHome.Service.SMS.YiMeiService.mo[] getMO(string arg0, string arg1) {
            LazyAtHome.Service.SMS.YiMeiService.getMORequest inValue = new LazyAtHome.Service.SMS.YiMeiService.getMORequest();
            inValue.arg0 = arg0;
            inValue.arg1 = arg1;
            LazyAtHome.Service.SMS.YiMeiService.getMOResponse retVal = ((LazyAtHome.Service.SMS.YiMeiService.SDKClient)(this)).getMO(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<LazyAtHome.Service.SMS.YiMeiService.getMOResponse> LazyAtHome.Service.SMS.YiMeiService.SDKClient.getMOAsync(LazyAtHome.Service.SMS.YiMeiService.getMORequest request) {
            return base.Channel.getMOAsync(request);
        }
        
        public System.Threading.Tasks.Task<LazyAtHome.Service.SMS.YiMeiService.getMOResponse> getMOAsync(string arg0, string arg1) {
            LazyAtHome.Service.SMS.YiMeiService.getMORequest inValue = new LazyAtHome.Service.SMS.YiMeiService.getMORequest();
            inValue.arg0 = arg0;
            inValue.arg1 = arg1;
            return ((LazyAtHome.Service.SMS.YiMeiService.SDKClient)(this)).getMOAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        LazyAtHome.Service.SMS.YiMeiService.logoutResponse LazyAtHome.Service.SMS.YiMeiService.SDKClient.logout(LazyAtHome.Service.SMS.YiMeiService.logoutRequest request) {
            return base.Channel.logout(request);
        }
        
        public int logout(string arg0, string arg1) {
            LazyAtHome.Service.SMS.YiMeiService.logoutRequest inValue = new LazyAtHome.Service.SMS.YiMeiService.logoutRequest();
            inValue.arg0 = arg0;
            inValue.arg1 = arg1;
            LazyAtHome.Service.SMS.YiMeiService.logoutResponse retVal = ((LazyAtHome.Service.SMS.YiMeiService.SDKClient)(this)).logout(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<LazyAtHome.Service.SMS.YiMeiService.logoutResponse> LazyAtHome.Service.SMS.YiMeiService.SDKClient.logoutAsync(LazyAtHome.Service.SMS.YiMeiService.logoutRequest request) {
            return base.Channel.logoutAsync(request);
        }
        
        public System.Threading.Tasks.Task<LazyAtHome.Service.SMS.YiMeiService.logoutResponse> logoutAsync(string arg0, string arg1) {
            LazyAtHome.Service.SMS.YiMeiService.logoutRequest inValue = new LazyAtHome.Service.SMS.YiMeiService.logoutRequest();
            inValue.arg0 = arg0;
            inValue.arg1 = arg1;
            return ((LazyAtHome.Service.SMS.YiMeiService.SDKClient)(this)).logoutAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        LazyAtHome.Service.SMS.YiMeiService.registDetailInfoResponse LazyAtHome.Service.SMS.YiMeiService.SDKClient.registDetailInfo(LazyAtHome.Service.SMS.YiMeiService.registDetailInfoRequest request) {
            return base.Channel.registDetailInfo(request);
        }
        
        public int registDetailInfo(string arg0, string arg1, string arg2, string arg3, string arg4, string arg5, string arg6, string arg7, string arg8, string arg9) {
            LazyAtHome.Service.SMS.YiMeiService.registDetailInfoRequest inValue = new LazyAtHome.Service.SMS.YiMeiService.registDetailInfoRequest();
            inValue.arg0 = arg0;
            inValue.arg1 = arg1;
            inValue.arg2 = arg2;
            inValue.arg3 = arg3;
            inValue.arg4 = arg4;
            inValue.arg5 = arg5;
            inValue.arg6 = arg6;
            inValue.arg7 = arg7;
            inValue.arg8 = arg8;
            inValue.arg9 = arg9;
            LazyAtHome.Service.SMS.YiMeiService.registDetailInfoResponse retVal = ((LazyAtHome.Service.SMS.YiMeiService.SDKClient)(this)).registDetailInfo(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<LazyAtHome.Service.SMS.YiMeiService.registDetailInfoResponse> LazyAtHome.Service.SMS.YiMeiService.SDKClient.registDetailInfoAsync(LazyAtHome.Service.SMS.YiMeiService.registDetailInfoRequest request) {
            return base.Channel.registDetailInfoAsync(request);
        }
        
        public System.Threading.Tasks.Task<LazyAtHome.Service.SMS.YiMeiService.registDetailInfoResponse> registDetailInfoAsync(string arg0, string arg1, string arg2, string arg3, string arg4, string arg5, string arg6, string arg7, string arg8, string arg9) {
            LazyAtHome.Service.SMS.YiMeiService.registDetailInfoRequest inValue = new LazyAtHome.Service.SMS.YiMeiService.registDetailInfoRequest();
            inValue.arg0 = arg0;
            inValue.arg1 = arg1;
            inValue.arg2 = arg2;
            inValue.arg3 = arg3;
            inValue.arg4 = arg4;
            inValue.arg5 = arg5;
            inValue.arg6 = arg6;
            inValue.arg7 = arg7;
            inValue.arg8 = arg8;
            inValue.arg9 = arg9;
            return ((LazyAtHome.Service.SMS.YiMeiService.SDKClient)(this)).registDetailInfoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        LazyAtHome.Service.SMS.YiMeiService.registExResponse LazyAtHome.Service.SMS.YiMeiService.SDKClient.registEx(LazyAtHome.Service.SMS.YiMeiService.registExRequest request) {
            return base.Channel.registEx(request);
        }
        
        public int registEx(string arg0, string arg1, string arg2) {
            LazyAtHome.Service.SMS.YiMeiService.registExRequest inValue = new LazyAtHome.Service.SMS.YiMeiService.registExRequest();
            inValue.arg0 = arg0;
            inValue.arg1 = arg1;
            inValue.arg2 = arg2;
            LazyAtHome.Service.SMS.YiMeiService.registExResponse retVal = ((LazyAtHome.Service.SMS.YiMeiService.SDKClient)(this)).registEx(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<LazyAtHome.Service.SMS.YiMeiService.registExResponse> LazyAtHome.Service.SMS.YiMeiService.SDKClient.registExAsync(LazyAtHome.Service.SMS.YiMeiService.registExRequest request) {
            return base.Channel.registExAsync(request);
        }
        
        public System.Threading.Tasks.Task<LazyAtHome.Service.SMS.YiMeiService.registExResponse> registExAsync(string arg0, string arg1, string arg2) {
            LazyAtHome.Service.SMS.YiMeiService.registExRequest inValue = new LazyAtHome.Service.SMS.YiMeiService.registExRequest();
            inValue.arg0 = arg0;
            inValue.arg1 = arg1;
            inValue.arg2 = arg2;
            return ((LazyAtHome.Service.SMS.YiMeiService.SDKClient)(this)).registExAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        LazyAtHome.Service.SMS.YiMeiService.sendSMSResponse LazyAtHome.Service.SMS.YiMeiService.SDKClient.sendSMS(LazyAtHome.Service.SMS.YiMeiService.sendSMSRequest request) {
            return base.Channel.sendSMS(request);
        }
        
        public int sendSMS(string arg0, string arg1, string arg2, string[] arg3, string arg4, string arg5, string arg6, int arg7, long arg8) {
            LazyAtHome.Service.SMS.YiMeiService.sendSMSRequest inValue = new LazyAtHome.Service.SMS.YiMeiService.sendSMSRequest();
            inValue.arg0 = arg0;
            inValue.arg1 = arg1;
            inValue.arg2 = arg2;
            inValue.arg3 = arg3;
            inValue.arg4 = arg4;
            inValue.arg5 = arg5;
            inValue.arg6 = arg6;
            inValue.arg7 = arg7;
            inValue.arg8 = arg8;
            LazyAtHome.Service.SMS.YiMeiService.sendSMSResponse retVal = ((LazyAtHome.Service.SMS.YiMeiService.SDKClient)(this)).sendSMS(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<LazyAtHome.Service.SMS.YiMeiService.sendSMSResponse> LazyAtHome.Service.SMS.YiMeiService.SDKClient.sendSMSAsync(LazyAtHome.Service.SMS.YiMeiService.sendSMSRequest request) {
            return base.Channel.sendSMSAsync(request);
        }
        
        public System.Threading.Tasks.Task<LazyAtHome.Service.SMS.YiMeiService.sendSMSResponse> sendSMSAsync(string arg0, string arg1, string arg2, string[] arg3, string arg4, string arg5, string arg6, int arg7, long arg8) {
            LazyAtHome.Service.SMS.YiMeiService.sendSMSRequest inValue = new LazyAtHome.Service.SMS.YiMeiService.sendSMSRequest();
            inValue.arg0 = arg0;
            inValue.arg1 = arg1;
            inValue.arg2 = arg2;
            inValue.arg3 = arg3;
            inValue.arg4 = arg4;
            inValue.arg5 = arg5;
            inValue.arg6 = arg6;
            inValue.arg7 = arg7;
            inValue.arg8 = arg8;
            return ((LazyAtHome.Service.SMS.YiMeiService.SDKClient)(this)).sendSMSAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        LazyAtHome.Service.SMS.YiMeiService.sendVoiceResponse LazyAtHome.Service.SMS.YiMeiService.SDKClient.sendVoice(LazyAtHome.Service.SMS.YiMeiService.sendVoiceRequest request) {
            return base.Channel.sendVoice(request);
        }
        
        public string sendVoice(string arg0, string arg1, string arg2, string[] arg3, string arg4, string arg5, string arg6, int arg7, long arg8) {
            LazyAtHome.Service.SMS.YiMeiService.sendVoiceRequest inValue = new LazyAtHome.Service.SMS.YiMeiService.sendVoiceRequest();
            inValue.arg0 = arg0;
            inValue.arg1 = arg1;
            inValue.arg2 = arg2;
            inValue.arg3 = arg3;
            inValue.arg4 = arg4;
            inValue.arg5 = arg5;
            inValue.arg6 = arg6;
            inValue.arg7 = arg7;
            inValue.arg8 = arg8;
            LazyAtHome.Service.SMS.YiMeiService.sendVoiceResponse retVal = ((LazyAtHome.Service.SMS.YiMeiService.SDKClient)(this)).sendVoice(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<LazyAtHome.Service.SMS.YiMeiService.sendVoiceResponse> LazyAtHome.Service.SMS.YiMeiService.SDKClient.sendVoiceAsync(LazyAtHome.Service.SMS.YiMeiService.sendVoiceRequest request) {
            return base.Channel.sendVoiceAsync(request);
        }
        
        public System.Threading.Tasks.Task<LazyAtHome.Service.SMS.YiMeiService.sendVoiceResponse> sendVoiceAsync(string arg0, string arg1, string arg2, string[] arg3, string arg4, string arg5, string arg6, int arg7, long arg8) {
            LazyAtHome.Service.SMS.YiMeiService.sendVoiceRequest inValue = new LazyAtHome.Service.SMS.YiMeiService.sendVoiceRequest();
            inValue.arg0 = arg0;
            inValue.arg1 = arg1;
            inValue.arg2 = arg2;
            inValue.arg3 = arg3;
            inValue.arg4 = arg4;
            inValue.arg5 = arg5;
            inValue.arg6 = arg6;
            inValue.arg7 = arg7;
            inValue.arg8 = arg8;
            return ((LazyAtHome.Service.SMS.YiMeiService.SDKClient)(this)).sendVoiceAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        LazyAtHome.Service.SMS.YiMeiService.serialPwdUpdResponse LazyAtHome.Service.SMS.YiMeiService.SDKClient.serialPwdUpd(LazyAtHome.Service.SMS.YiMeiService.serialPwdUpdRequest request) {
            return base.Channel.serialPwdUpd(request);
        }
        
        public int serialPwdUpd(string arg0, string arg1, string arg2, string arg3) {
            LazyAtHome.Service.SMS.YiMeiService.serialPwdUpdRequest inValue = new LazyAtHome.Service.SMS.YiMeiService.serialPwdUpdRequest();
            inValue.arg0 = arg0;
            inValue.arg1 = arg1;
            inValue.arg2 = arg2;
            inValue.arg3 = arg3;
            LazyAtHome.Service.SMS.YiMeiService.serialPwdUpdResponse retVal = ((LazyAtHome.Service.SMS.YiMeiService.SDKClient)(this)).serialPwdUpd(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<LazyAtHome.Service.SMS.YiMeiService.serialPwdUpdResponse> LazyAtHome.Service.SMS.YiMeiService.SDKClient.serialPwdUpdAsync(LazyAtHome.Service.SMS.YiMeiService.serialPwdUpdRequest request) {
            return base.Channel.serialPwdUpdAsync(request);
        }
        
        public System.Threading.Tasks.Task<LazyAtHome.Service.SMS.YiMeiService.serialPwdUpdResponse> serialPwdUpdAsync(string arg0, string arg1, string arg2, string arg3) {
            LazyAtHome.Service.SMS.YiMeiService.serialPwdUpdRequest inValue = new LazyAtHome.Service.SMS.YiMeiService.serialPwdUpdRequest();
            inValue.arg0 = arg0;
            inValue.arg1 = arg1;
            inValue.arg2 = arg2;
            inValue.arg3 = arg3;
            return ((LazyAtHome.Service.SMS.YiMeiService.SDKClient)(this)).serialPwdUpdAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        LazyAtHome.Service.SMS.YiMeiService.setMOForwardResponse LazyAtHome.Service.SMS.YiMeiService.SDKClient.setMOForward(LazyAtHome.Service.SMS.YiMeiService.setMOForwardRequest request) {
            return base.Channel.setMOForward(request);
        }
        
        public int setMOForward(string arg0, string arg1, string arg2) {
            LazyAtHome.Service.SMS.YiMeiService.setMOForwardRequest inValue = new LazyAtHome.Service.SMS.YiMeiService.setMOForwardRequest();
            inValue.arg0 = arg0;
            inValue.arg1 = arg1;
            inValue.arg2 = arg2;
            LazyAtHome.Service.SMS.YiMeiService.setMOForwardResponse retVal = ((LazyAtHome.Service.SMS.YiMeiService.SDKClient)(this)).setMOForward(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<LazyAtHome.Service.SMS.YiMeiService.setMOForwardResponse> LazyAtHome.Service.SMS.YiMeiService.SDKClient.setMOForwardAsync(LazyAtHome.Service.SMS.YiMeiService.setMOForwardRequest request) {
            return base.Channel.setMOForwardAsync(request);
        }
        
        public System.Threading.Tasks.Task<LazyAtHome.Service.SMS.YiMeiService.setMOForwardResponse> setMOForwardAsync(string arg0, string arg1, string arg2) {
            LazyAtHome.Service.SMS.YiMeiService.setMOForwardRequest inValue = new LazyAtHome.Service.SMS.YiMeiService.setMOForwardRequest();
            inValue.arg0 = arg0;
            inValue.arg1 = arg1;
            inValue.arg2 = arg2;
            return ((LazyAtHome.Service.SMS.YiMeiService.SDKClient)(this)).setMOForwardAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        LazyAtHome.Service.SMS.YiMeiService.setMOForwardExResponse LazyAtHome.Service.SMS.YiMeiService.SDKClient.setMOForwardEx(LazyAtHome.Service.SMS.YiMeiService.setMOForwardExRequest request) {
            return base.Channel.setMOForwardEx(request);
        }
        
        public int setMOForwardEx(string arg0, string arg1, string[] arg2) {
            LazyAtHome.Service.SMS.YiMeiService.setMOForwardExRequest inValue = new LazyAtHome.Service.SMS.YiMeiService.setMOForwardExRequest();
            inValue.arg0 = arg0;
            inValue.arg1 = arg1;
            inValue.arg2 = arg2;
            LazyAtHome.Service.SMS.YiMeiService.setMOForwardExResponse retVal = ((LazyAtHome.Service.SMS.YiMeiService.SDKClient)(this)).setMOForwardEx(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<LazyAtHome.Service.SMS.YiMeiService.setMOForwardExResponse> LazyAtHome.Service.SMS.YiMeiService.SDKClient.setMOForwardExAsync(LazyAtHome.Service.SMS.YiMeiService.setMOForwardExRequest request) {
            return base.Channel.setMOForwardExAsync(request);
        }
        
        public System.Threading.Tasks.Task<LazyAtHome.Service.SMS.YiMeiService.setMOForwardExResponse> setMOForwardExAsync(string arg0, string arg1, string[] arg2) {
            LazyAtHome.Service.SMS.YiMeiService.setMOForwardExRequest inValue = new LazyAtHome.Service.SMS.YiMeiService.setMOForwardExRequest();
            inValue.arg0 = arg0;
            inValue.arg1 = arg1;
            inValue.arg2 = arg2;
            return ((LazyAtHome.Service.SMS.YiMeiService.SDKClient)(this)).setMOForwardExAsync(inValue);
        }
    }
}
