
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package com.landaojia.washclothes.userappserver.service.sms.jianzhou.ws;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.0.4
 * 2015-03-16T15:53:48.223+08:00
 * Generated source version: 3.0.4
 * 
 */

@javax.jws.WebService(
                      serviceName = "BusinessServiceService",
                      portName = "BusinessServicePort",
                      targetNamespace = "http://service.nineorange.com",
                      wsdlLocation = "http://www.jianzhou.sh.cn/JianzhouSMSWSServer/services/BusinessService?wsdl",
                      endpointInterface = "com.landaojia.washclothes.userappserver.service.sms.jianzhou.ws.BusinessService")
                      
public class BusinessServicePortImpl implements BusinessService {

    private static final Logger LOG = Logger.getLogger(BusinessServicePortImpl.class.getName());

    /* (non-Javadoc)
     * @see com.landaojia.washclothes.userappserver.service.sms.jianzhou.ws.BusinessService#validateUser(java.lang.String  account ,)java.lang.String  password )*
     */
    public int validateUser(java.lang.String account,java.lang.String password) { 
        LOG.info("Executing operation validateUser");
        System.out.println(account);
        System.out.println(password);
        try {
            int _return = 0;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.landaojia.washclothes.userappserver.service.sms.jianzhou.ws.BusinessService#sendBatchMessage(java.lang.String  account ,)java.lang.String  password ,)java.lang.String  destmobile ,)java.lang.String  msgText )*
     */
    public int sendBatchMessage(java.lang.String account,java.lang.String password,java.lang.String destmobile,java.lang.String msgText) { 
        LOG.info("Executing operation sendBatchMessage");
        System.out.println(account);
        System.out.println(password);
        System.out.println(destmobile);
        System.out.println(msgText);
        try {
            int _return = 0;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.landaojia.washclothes.userappserver.service.sms.jianzhou.ws.BusinessService#getReceivedMsg(java.lang.String  account ,)java.lang.String  password ,)int  param )*
     */
    public java.lang.String getReceivedMsg(java.lang.String account,java.lang.String password,int param) { 
        LOG.info("Executing operation getReceivedMsg");
        System.out.println(account);
        System.out.println(password);
        System.out.println(param);
        try {
            java.lang.String _return = "";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.landaojia.washclothes.userappserver.service.sms.jianzhou.ws.BusinessService#sendGjBatchMessage(java.lang.String  account ,)java.lang.String  password ,)java.lang.String  sendDateTime ,)java.lang.String  destmobile ,)java.lang.String  msgText )*
     */
    public int sendGjBatchMessage(java.lang.String account,java.lang.String password,java.lang.String sendDateTime,java.lang.String destmobile,java.lang.String msgText) { 
        LOG.info("Executing operation sendGjBatchMessage");
        System.out.println(account);
        System.out.println(password);
        System.out.println(sendDateTime);
        System.out.println(destmobile);
        System.out.println(msgText);
        try {
            int _return = 0;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.landaojia.washclothes.userappserver.service.sms.jianzhou.ws.BusinessService#sendAudio(java.lang.String  account ,)java.lang.String  password ,)java.lang.String  sendDateTime ,)java.lang.String  destmobile ,)java.lang.String  msgText ,)java.lang.String  srcMobile )*
     */
    public int sendAudio(java.lang.String account,java.lang.String password,java.lang.String sendDateTime,java.lang.String destmobile,java.lang.String msgText,java.lang.String srcMobile) { 
        LOG.info("Executing operation sendAudio");
        System.out.println(account);
        System.out.println(password);
        System.out.println(sendDateTime);
        System.out.println(destmobile);
        System.out.println(msgText);
        System.out.println(srcMobile);
        try {
            int _return = 0;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.landaojia.washclothes.userappserver.service.sms.jianzhou.ws.BusinessService#getUserInfo(java.lang.String  account ,)java.lang.String  password )*
     */
    public java.lang.String getUserInfo(java.lang.String account,java.lang.String password) { 
        LOG.info("Executing operation getUserInfo");
        System.out.println(account);
        System.out.println(password);
        try {
            java.lang.String _return = "";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.landaojia.washclothes.userappserver.service.sms.jianzhou.ws.BusinessService#sendPersonalMessages(java.lang.String  account ,)java.lang.String  password ,)java.lang.String  destMobiles ,)java.lang.String  msgContents )*
     */
    public int sendPersonalMessages(java.lang.String account,java.lang.String password,java.lang.String destMobiles,java.lang.String msgContents) { 
        LOG.info("Executing operation sendPersonalMessages");
        System.out.println(account);
        System.out.println(password);
        System.out.println(destMobiles);
        System.out.println(msgContents);
        try {
            int _return = 0;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.landaojia.washclothes.userappserver.service.sms.jianzhou.ws.BusinessService#sendBatchMessageTimelyExt(java.lang.String  account ,)java.lang.String  password ,)java.lang.String  sendDateTime ,)java.lang.String  destmobile ,)java.lang.String  msgText ,)java.lang.String  ext )*
     */
    public int sendBatchMessageTimelyExt(java.lang.String account,java.lang.String password,java.lang.String sendDateTime,java.lang.String destmobile,java.lang.String msgText,java.lang.String ext) { 
        LOG.info("Executing operation sendBatchMessageTimelyExt");
        System.out.println(account);
        System.out.println(password);
        System.out.println(sendDateTime);
        System.out.println(destmobile);
        System.out.println(msgText);
        System.out.println(ext);
        try {
            int _return = 0;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.landaojia.washclothes.userappserver.service.sms.jianzhou.ws.BusinessService#modifyPassword(java.lang.String  account ,)java.lang.String  oldPassword ,)java.lang.String  newPassword )*
     */
    public int modifyPassword(java.lang.String account,java.lang.String oldPassword,java.lang.String newPassword) { 
        LOG.info("Executing operation modifyPassword");
        System.out.println(account);
        System.out.println(oldPassword);
        System.out.println(newPassword);
        try {
            int _return = 0;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.landaojia.washclothes.userappserver.service.sms.jianzhou.ws.BusinessService#gxmt(com.landaojia.washclothes.userappserver.service.sms.jianzhou.ws.Gxmt  parameters )*
     */
    public com.landaojia.washclothes.userappserver.service.sms.jianzhou.ws.GxmtResponse gxmt(Gxmt parameters) { 
        LOG.info("Executing operation gxmt");
        System.out.println(parameters);
        try {
            com.landaojia.washclothes.userappserver.service.sms.jianzhou.ws.GxmtResponse _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.landaojia.washclothes.userappserver.service.sms.jianzhou.ws.BusinessService#sendMessage(java.lang.String  account ,)java.lang.String  password ,)java.lang.String  destmobile ,)java.lang.String  msgText )*
     */
    public int sendMessage(java.lang.String account,java.lang.String password,java.lang.String destmobile,java.lang.String msgText) { 
        LOG.info("Executing operation sendMessage");
        System.out.println(account);
        System.out.println(password);
        System.out.println(destmobile);
        System.out.println(msgText);
        try {
            int _return = 0;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.landaojia.washclothes.userappserver.service.sms.jianzhou.ws.BusinessService#sendMmsMessages(java.lang.String  account ,)java.lang.String  password ,)java.lang.String  phones ,)java.lang.String  mmsString )*
     */
    public int sendMmsMessages(java.lang.String account,java.lang.String password,java.lang.String phones,java.lang.String mmsString) { 
        LOG.info("Executing operation sendMmsMessages");
        System.out.println(account);
        System.out.println(password);
        System.out.println(phones);
        System.out.println(mmsString);
        try {
            int _return = 0;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.landaojia.washclothes.userappserver.service.sms.jianzhou.ws.BusinessService#sendTimelyMessage(java.lang.String  account ,)java.lang.String  password ,)java.lang.String  sendDateTime ,)java.lang.String  destmobile ,)java.lang.String  msgText )*
     */
    public int sendTimelyMessage(java.lang.String account,java.lang.String password,java.lang.String sendDateTime,java.lang.String destmobile,java.lang.String msgText) { 
        LOG.info("Executing operation sendTimelyMessage");
        System.out.println(account);
        System.out.println(password);
        System.out.println(sendDateTime);
        System.out.println(destmobile);
        System.out.println(msgText);
        try {
            int _return = 0;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.landaojia.washclothes.userappserver.service.sms.jianzhou.ws.BusinessService#getReceipt(java.lang.String  account ,)java.lang.String  password ,)int  taskID )*
     */
    public java.lang.String getReceipt(java.lang.String account,java.lang.String password,int taskID) { 
        LOG.info("Executing operation getReceipt");
        System.out.println(account);
        System.out.println(password);
        System.out.println(taskID);
        try {
            java.lang.String _return = "";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
