
package com.landaojia.washclothes.laundry.client.washfactory.yibeijie.ws;

import javax.xml.ws.Endpoint;

/**
 * This class was generated by Apache CXF 3.0.4
 * 2015-02-28T17:18:17.210+08:00
 * Generated source version: 3.0.4
 * 
 */
 
public class IOrderService_BasicHttpBindingIOrderService_Server{

    protected IOrderService_BasicHttpBindingIOrderService_Server() throws java.lang.Exception {
        System.out.println("Starting Server");
        Object implementor = new BasicHttpBinding_IOrderServiceImpl();
        String address = "http://180.166.224.253:89/CabinetWcf/OrderService.svc";
        Endpoint.publish(address, implementor);
    }
    
    public static void main(String args[]) throws java.lang.Exception { 
        new IOrderService_BasicHttpBindingIOrderService_Server();
        System.out.println("Server ready..."); 
        
        Thread.sleep(5 * 60 * 1000); 
        System.out.println("Server exiting");
        System.exit(0);
    }
}
