package com.landaojia.washclothes.laundry.client.washfactory.yibeijie.ws;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.0.4
 * 2015-02-28T17:18:17.210+08:00
 * Generated source version: 3.0.4
 * 
 */
@WebServiceClient(name = "OrderService", 
                  wsdlLocation = "http://180.166.224.253:89/CabinetWcf/OrderService.svc?wsdl",
                  targetNamespace = "http://tempuri.org/") 
public class OrderService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://tempuri.org/", "OrderService");
    public final static QName BasicHttpBindingIOrderService = new QName("http://tempuri.org/", "BasicHttpBinding_IOrderService");
    static {
        URL url = null;
        try {
            url = new URL("http://180.166.224.253:89/CabinetWcf/OrderService.svc?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(OrderService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://180.166.224.253:89/CabinetWcf/OrderService.svc?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public OrderService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public OrderService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public OrderService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public OrderService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public OrderService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public OrderService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    

    /**
     *
     * @return
     *     returns IOrderService
     */
    @WebEndpoint(name = "BasicHttpBinding_IOrderService")
    public IOrderService getBasicHttpBindingIOrderService() {
        return super.getPort(BasicHttpBindingIOrderService, IOrderService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns IOrderService
     */
    @WebEndpoint(name = "BasicHttpBinding_IOrderService")
    public IOrderService getBasicHttpBindingIOrderService(WebServiceFeature... features) {
        return super.getPort(BasicHttpBindingIOrderService, IOrderService.class, features);
    }

}
