//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.34014
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LazyAtHome.Winform.FactoryPortal.SFExpressService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="LoginCredentials", Namespace="http://schemas.datacontract.org/2004/07/LazyAtHome.WCF.WebService.Contract.DataCo" +
        "ntract.PR")]
    [System.SerializableAttribute()]
    public partial class LoginCredentials : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LoginNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private LazyAtHome.Winform.FactoryPortal.SFExpressService.OperatorType OperatorTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PasswordField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LoginName {
            get {
                return this.LoginNameField;
            }
            set {
                if ((object.ReferenceEquals(this.LoginNameField, value) != true)) {
                    this.LoginNameField = value;
                    this.RaisePropertyChanged("LoginName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public LazyAtHome.Winform.FactoryPortal.SFExpressService.OperatorType OperatorType {
            get {
                return this.OperatorTypeField;
            }
            set {
                if ((this.OperatorTypeField.Equals(value) != true)) {
                    this.OperatorTypeField = value;
                    this.RaisePropertyChanged("OperatorType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Password {
            get {
                return this.PasswordField;
            }
            set {
                if ((object.ReferenceEquals(this.PasswordField, value) != true)) {
                    this.PasswordField = value;
                    this.RaisePropertyChanged("Password");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="OperatorType", Namespace="http://schemas.datacontract.org/2004/07/LazyAtHome.WCF.Common.Contract.Enumerate")]
    public enum OperatorType : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Manage = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Factory = 2,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="OrderDC", Namespace="http://schemas.datacontract.org/2004/07/LazyAtHome.WCF.WebService.Contract.DataCo" +
        "ntract.SFExpress")]
    [System.SerializableAttribute()]
    public partial class OrderDC : LazyAtHome.Core.Infrastructure.WCF.EntityBase, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string destcodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int filter_resultField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string mailnoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string orderidField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string origincodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string remarkField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string destcode {
            get {
                return this.destcodeField;
            }
            set {
                if ((object.ReferenceEquals(this.destcodeField, value) != true)) {
                    this.destcodeField = value;
                    this.RaisePropertyChanged("destcode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int filter_result {
            get {
                return this.filter_resultField;
            }
            set {
                if ((this.filter_resultField.Equals(value) != true)) {
                    this.filter_resultField = value;
                    this.RaisePropertyChanged("filter_result");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string mailno {
            get {
                return this.mailnoField;
            }
            set {
                if ((object.ReferenceEquals(this.mailnoField, value) != true)) {
                    this.mailnoField = value;
                    this.RaisePropertyChanged("mailno");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string orderid {
            get {
                return this.orderidField;
            }
            set {
                if ((object.ReferenceEquals(this.orderidField, value) != true)) {
                    this.orderidField = value;
                    this.RaisePropertyChanged("orderid");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string origincode {
            get {
                return this.origincodeField;
            }
            set {
                if ((object.ReferenceEquals(this.origincodeField, value) != true)) {
                    this.origincodeField = value;
                    this.RaisePropertyChanged("origincode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string remark {
            get {
                return this.remarkField;
            }
            set {
                if ((object.ReferenceEquals(this.remarkField, value) != true)) {
                    this.remarkField = value;
                    this.RaisePropertyChanged("remark");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SFExpressService.ISFExpress", SessionMode=System.ServiceModel.SessionMode.Required)]
    public interface ISFExpress {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISFExpress/CreateOrder", ReplyAction="http://tempuri.org/ISFExpress/CreateOrderResponse")]
        LazyAtHome.Core.Infrastructure.WCF.ReturnEntity<LazyAtHome.Winform.FactoryPortal.SFExpressService.OrderDC> CreateOrder(LazyAtHome.Winform.FactoryPortal.SFExpressService.LoginCredentials iCredentials, string iOrderid, string j_Company, string j_Contact, string j_Tel, string j_Address, string j_City, string j_Province, string d_Company, string d_Contact, string d_Tel, string d_Address, string d_City, string d_Province, System.Nullable<decimal> iPayment);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISFExpress/CreateOrder", ReplyAction="http://tempuri.org/ISFExpress/CreateOrderResponse")]
        System.Threading.Tasks.Task<LazyAtHome.Core.Infrastructure.WCF.ReturnEntity<LazyAtHome.Winform.FactoryPortal.SFExpressService.OrderDC>> CreateOrderAsync(LazyAtHome.Winform.FactoryPortal.SFExpressService.LoginCredentials iCredentials, string iOrderid, string j_Company, string j_Contact, string j_Tel, string j_Address, string j_City, string j_Province, string d_Company, string d_Contact, string d_Tel, string d_Address, string d_City, string d_Province, System.Nullable<decimal> iPayment);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISFExpress/OrderSearch", ReplyAction="http://tempuri.org/ISFExpress/OrderSearchResponse")]
        LazyAtHome.Core.Infrastructure.WCF.ReturnEntity<LazyAtHome.Winform.FactoryPortal.SFExpressService.OrderDC> OrderSearch(LazyAtHome.Winform.FactoryPortal.SFExpressService.LoginCredentials iCredentials, string iOrderid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISFExpress/OrderSearch", ReplyAction="http://tempuri.org/ISFExpress/OrderSearchResponse")]
        System.Threading.Tasks.Task<LazyAtHome.Core.Infrastructure.WCF.ReturnEntity<LazyAtHome.Winform.FactoryPortal.SFExpressService.OrderDC>> OrderSearchAsync(LazyAtHome.Winform.FactoryPortal.SFExpressService.LoginCredentials iCredentials, string iOrderid);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ISFExpressChannel : LazyAtHome.Winform.FactoryPortal.SFExpressService.ISFExpress, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SFExpressClient : System.ServiceModel.ClientBase<LazyAtHome.Winform.FactoryPortal.SFExpressService.ISFExpress>, LazyAtHome.Winform.FactoryPortal.SFExpressService.ISFExpress {
        
        public SFExpressClient() {
        }
        
        public SFExpressClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SFExpressClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SFExpressClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SFExpressClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public LazyAtHome.Core.Infrastructure.WCF.ReturnEntity<LazyAtHome.Winform.FactoryPortal.SFExpressService.OrderDC> CreateOrder(LazyAtHome.Winform.FactoryPortal.SFExpressService.LoginCredentials iCredentials, string iOrderid, string j_Company, string j_Contact, string j_Tel, string j_Address, string j_City, string j_Province, string d_Company, string d_Contact, string d_Tel, string d_Address, string d_City, string d_Province, System.Nullable<decimal> iPayment) {
            return base.Channel.CreateOrder(iCredentials, iOrderid, j_Company, j_Contact, j_Tel, j_Address, j_City, j_Province, d_Company, d_Contact, d_Tel, d_Address, d_City, d_Province, iPayment);
        }
        
        public System.Threading.Tasks.Task<LazyAtHome.Core.Infrastructure.WCF.ReturnEntity<LazyAtHome.Winform.FactoryPortal.SFExpressService.OrderDC>> CreateOrderAsync(LazyAtHome.Winform.FactoryPortal.SFExpressService.LoginCredentials iCredentials, string iOrderid, string j_Company, string j_Contact, string j_Tel, string j_Address, string j_City, string j_Province, string d_Company, string d_Contact, string d_Tel, string d_Address, string d_City, string d_Province, System.Nullable<decimal> iPayment) {
            return base.Channel.CreateOrderAsync(iCredentials, iOrderid, j_Company, j_Contact, j_Tel, j_Address, j_City, j_Province, d_Company, d_Contact, d_Tel, d_Address, d_City, d_Province, iPayment);
        }
        
        public LazyAtHome.Core.Infrastructure.WCF.ReturnEntity<LazyAtHome.Winform.FactoryPortal.SFExpressService.OrderDC> OrderSearch(LazyAtHome.Winform.FactoryPortal.SFExpressService.LoginCredentials iCredentials, string iOrderid) {
            return base.Channel.OrderSearch(iCredentials, iOrderid);
        }
        
        public System.Threading.Tasks.Task<LazyAtHome.Core.Infrastructure.WCF.ReturnEntity<LazyAtHome.Winform.FactoryPortal.SFExpressService.OrderDC>> OrderSearchAsync(LazyAtHome.Winform.FactoryPortal.SFExpressService.LoginCredentials iCredentials, string iOrderid) {
            return base.Channel.OrderSearchAsync(iCredentials, iOrderid);
        }
    }
}
