
package com.landaojia.washclothes.laundry.client.washfactory.yibeijie.ws;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.0.4
 * 2015-02-28T17:18:17.130+08:00
 * Generated source version: 3.0.4
 * 
 */
public final class IOrderService_BasicHttpBindingIOrderService_Client {

    private static final QName SERVICE_NAME = new QName("http://tempuri.org/", "OrderService");

    private IOrderService_BasicHttpBindingIOrderService_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = OrderService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        OrderService ss = new OrderService(wsdlURL, SERVICE_NAME);
        IOrderService port = ss.getBasicHttpBindingIOrderService();  
        
        {
        System.out.println("Invoking orderFeedback...");
        java.lang.String _orderFeedback_argNo = "";
        java.lang.String _orderFeedback_argOrder = "";
        java.lang.String _orderFeedback_argPw = "";
        java.lang.String _orderFeedback__return = port.orderFeedback(_orderFeedback_argNo, _orderFeedback_argOrder, _orderFeedback_argPw);
        System.out.println("orderFeedback.result=" + _orderFeedback__return);


        }
        {
        System.out.println("Invoking quotedPrice...");
        java.lang.String _quotedPrice_argPhone = "";
        java.lang.String _quotedPrice_argOrder = "";
        java.lang.String _quotedPrice_argPw = "";
        java.lang.Integer _quotedPrice__return = port.quotedPrice(_quotedPrice_argPhone, _quotedPrice_argOrder, _quotedPrice_argPw);
        System.out.println("quotedPrice.result=" + _quotedPrice__return);


        }
        {
        System.out.println("Invoking orderUpLoad...");
        java.lang.String _orderUpLoad_argOrder = "";
        java.lang.String _orderUpLoad_argPw = "";
        java.lang.Integer _orderUpLoad__return = port.orderUpLoad(_orderUpLoad_argOrder, _orderUpLoad_argPw);
        System.out.println("orderUpLoad.result=" + _orderUpLoad__return);


        }
        {
        System.out.println("Invoking doWork...");
        port.doWork();


        }

        System.exit(0);
    }

}
