
package com.landaojia.washclothes.userappserver.service.sms.jianzhou.ws;

import javax.xml.ws.Endpoint;

/**
 * This class was generated by Apache CXF 3.0.4
 * 2015-03-16T15:53:48.251+08:00
 * Generated source version: 3.0.4
 * 
 */
 
public class BusinessService_BusinessServicePort_Server{

    protected BusinessService_BusinessServicePort_Server() throws java.lang.Exception {
        System.out.println("Starting Server");
        Object implementor = new BusinessServicePortImpl();
        String address = "http://www.jianzhou.sh.cn/JianzhouSMSWSServer/services/BusinessService";
        Endpoint.publish(address, implementor);
    }
    
    public static void main(String args[]) throws java.lang.Exception { 
        new BusinessService_BusinessServicePort_Server();
        System.out.println("Server ready..."); 
        
        Thread.sleep(5 * 60 * 1000); 
        System.out.println("Server exiting");
        System.exit(0);
    }
}
