
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package com.landaojia.washclothes.userappserver.service.sms.yimei.ws;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.0.4
 * 2015-03-16T15:52:16.549+08:00
 * Generated source version: 3.0.4
 * 
 */

@javax.jws.WebService(
                      serviceName = "SDKService",
                      portName = "SDKService",
                      targetNamespace = "http://sdkhttp.eucp.b2m.cn/",
                      wsdlLocation = "http://sdk999ws.eucp.b2m.cn:8080/sdk/SDKService?wsdl",
                      endpointInterface = "com.landaojia.washclothes.userappserver.service.sms.yimei.ws.SDKClient")
                      
public class SDKServiceImpl implements SDKClient {

    private static final Logger LOG = Logger.getLogger(SDKServiceImpl.class.getName());

    /* (non-Javadoc)
     * @see com.landaojia.washclothes.userappserver.service.sms.yimei.ws.SDKClient#registDetailInfo(java.lang.String  arg0 ,)java.lang.String  arg1 ,)java.lang.String  arg2 ,)java.lang.String  arg3 ,)java.lang.String  arg4 ,)java.lang.String  arg5 ,)java.lang.String  arg6 ,)java.lang.String  arg7 ,)java.lang.String  arg8 ,)java.lang.String  arg9 )*
     */
    public int registDetailInfo(java.lang.String arg0,java.lang.String arg1,java.lang.String arg2,java.lang.String arg3,java.lang.String arg4,java.lang.String arg5,java.lang.String arg6,java.lang.String arg7,java.lang.String arg8,java.lang.String arg9) { 
        LOG.info("Executing operation registDetailInfo");
        System.out.println(arg0);
        System.out.println(arg1);
        System.out.println(arg2);
        System.out.println(arg3);
        System.out.println(arg4);
        System.out.println(arg5);
        System.out.println(arg6);
        System.out.println(arg7);
        System.out.println(arg8);
        System.out.println(arg9);
        try {
            int _return = 0;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.landaojia.washclothes.userappserver.service.sms.yimei.ws.SDKClient#getMO(java.lang.String  arg0 ,)java.lang.String  arg1 )*
     */
    public java.util.List<com.landaojia.washclothes.userappserver.service.sms.yimei.ws.Mo> getMO(java.lang.String arg0,java.lang.String arg1) { 
        LOG.info("Executing operation getMO");
        System.out.println(arg0);
        System.out.println(arg1);
        try {
            java.util.List<com.landaojia.washclothes.userappserver.service.sms.yimei.ws.Mo> _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.landaojia.washclothes.userappserver.service.sms.yimei.ws.SDKClient#getEachFee(java.lang.String  arg0 ,)java.lang.String  arg1 )*
     */
    public double getEachFee(java.lang.String arg0,java.lang.String arg1) { 
        LOG.info("Executing operation getEachFee");
        System.out.println(arg0);
        System.out.println(arg1);
        try {
            double _return = 0.0;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.landaojia.washclothes.userappserver.service.sms.yimei.ws.SDKClient#getVersion(*
     */
    public java.lang.String getVersion() { 
        LOG.info("Executing operation getVersion");
        try {
            java.lang.String _return = "";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.landaojia.washclothes.userappserver.service.sms.yimei.ws.SDKClient#serialPwdUpd(java.lang.String  arg0 ,)java.lang.String  arg1 ,)java.lang.String  arg2 ,)java.lang.String  arg3 )*
     */
    public int serialPwdUpd(java.lang.String arg0,java.lang.String arg1,java.lang.String arg2,java.lang.String arg3) { 
        LOG.info("Executing operation serialPwdUpd");
        System.out.println(arg0);
        System.out.println(arg1);
        System.out.println(arg2);
        System.out.println(arg3);
        try {
            int _return = 0;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.landaojia.washclothes.userappserver.service.sms.yimei.ws.SDKClient#getReport(java.lang.String  arg0 ,)java.lang.String  arg1 )*
     */
    public java.util.List<com.landaojia.washclothes.userappserver.service.sms.yimei.ws.StatusReport> getReport(java.lang.String arg0,java.lang.String arg1) { 
        LOG.info("Executing operation getReport");
        System.out.println(arg0);
        System.out.println(arg1);
        try {
            java.util.List<com.landaojia.washclothes.userappserver.service.sms.yimei.ws.StatusReport> _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.landaojia.washclothes.userappserver.service.sms.yimei.ws.SDKClient#cancelMOForward(java.lang.String  arg0 ,)java.lang.String  arg1 )*
     */
    public int cancelMOForward(java.lang.String arg0,java.lang.String arg1) { 
        LOG.info("Executing operation cancelMOForward");
        System.out.println(arg0);
        System.out.println(arg1);
        try {
            int _return = 0;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.landaojia.washclothes.userappserver.service.sms.yimei.ws.SDKClient#logout(java.lang.String  arg0 ,)java.lang.String  arg1 )*
     */
    public int logout(java.lang.String arg0,java.lang.String arg1) { 
        LOG.info("Executing operation logout");
        System.out.println(arg0);
        System.out.println(arg1);
        try {
            int _return = 0;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.landaojia.washclothes.userappserver.service.sms.yimei.ws.SDKClient#getBalance(java.lang.String  arg0 ,)java.lang.String  arg1 )*
     */
    public double getBalance(java.lang.String arg0,java.lang.String arg1) { 
        LOG.info("Executing operation getBalance");
        System.out.println(arg0);
        System.out.println(arg1);
        try {
            double _return = 0.0;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.landaojia.washclothes.userappserver.service.sms.yimei.ws.SDKClient#sendSMS(java.lang.String  arg0 ,)java.lang.String  arg1 ,)java.lang.String  arg2 ,)java.util.List<java.lang.String>  arg3 ,)java.lang.String  arg4 ,)java.lang.String  arg5 ,)java.lang.String  arg6 ,)int  arg7 ,)long  arg8 )*
     */
    public int sendSMS(java.lang.String arg0,java.lang.String arg1,java.lang.String arg2,java.util.List<java.lang.String> arg3,java.lang.String arg4,java.lang.String arg5,java.lang.String arg6,int arg7,long arg8) { 
        LOG.info("Executing operation sendSMS");
        System.out.println(arg0);
        System.out.println(arg1);
        System.out.println(arg2);
        System.out.println(arg3);
        System.out.println(arg4);
        System.out.println(arg5);
        System.out.println(arg6);
        System.out.println(arg7);
        System.out.println(arg8);
        try {
            int _return = 0;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.landaojia.washclothes.userappserver.service.sms.yimei.ws.SDKClient#chargeUp(java.lang.String  arg0 ,)java.lang.String  arg1 ,)java.lang.String  arg2 ,)java.lang.String  arg3 )*
     */
    public int chargeUp(java.lang.String arg0,java.lang.String arg1,java.lang.String arg2,java.lang.String arg3) { 
        LOG.info("Executing operation chargeUp");
        System.out.println(arg0);
        System.out.println(arg1);
        System.out.println(arg2);
        System.out.println(arg3);
        try {
            int _return = 0;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.landaojia.washclothes.userappserver.service.sms.yimei.ws.SDKClient#registEx(java.lang.String  arg0 ,)java.lang.String  arg1 ,)java.lang.String  arg2 )*
     */
    public int registEx(java.lang.String arg0,java.lang.String arg1,java.lang.String arg2) { 
        LOG.info("Executing operation registEx");
        System.out.println(arg0);
        System.out.println(arg1);
        System.out.println(arg2);
        try {
            int _return = 0;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.landaojia.washclothes.userappserver.service.sms.yimei.ws.SDKClient#setMOForwardEx(java.lang.String  arg0 ,)java.lang.String  arg1 ,)java.util.List<java.lang.String>  arg2 )*
     */
    public int setMOForwardEx(java.lang.String arg0,java.lang.String arg1,java.util.List<java.lang.String> arg2) { 
        LOG.info("Executing operation setMOForwardEx");
        System.out.println(arg0);
        System.out.println(arg1);
        System.out.println(arg2);
        try {
            int _return = 0;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.landaojia.washclothes.userappserver.service.sms.yimei.ws.SDKClient#sendVoice(java.lang.String  arg0 ,)java.lang.String  arg1 ,)java.lang.String  arg2 ,)java.util.List<java.lang.String>  arg3 ,)java.lang.String  arg4 ,)java.lang.String  arg5 ,)java.lang.String  arg6 ,)int  arg7 ,)long  arg8 )*
     */
    public java.lang.String sendVoice(java.lang.String arg0,java.lang.String arg1,java.lang.String arg2,java.util.List<java.lang.String> arg3,java.lang.String arg4,java.lang.String arg5,java.lang.String arg6,int arg7,long arg8) { 
        LOG.info("Executing operation sendVoice");
        System.out.println(arg0);
        System.out.println(arg1);
        System.out.println(arg2);
        System.out.println(arg3);
        System.out.println(arg4);
        System.out.println(arg5);
        System.out.println(arg6);
        System.out.println(arg7);
        System.out.println(arg8);
        try {
            java.lang.String _return = "";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.landaojia.washclothes.userappserver.service.sms.yimei.ws.SDKClient#setMOForward(java.lang.String  arg0 ,)java.lang.String  arg1 ,)java.lang.String  arg2 )*
     */
    public int setMOForward(java.lang.String arg0,java.lang.String arg1,java.lang.String arg2) { 
        LOG.info("Executing operation setMOForward");
        System.out.println(arg0);
        System.out.println(arg1);
        System.out.println(arg2);
        try {
            int _return = 0;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
