//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.34014
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LazyAtHome.Library.Partners.InternalExpressService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="LoginCredentials", Namespace="http://schemas.datacontract.org/2004/07/LazyAtHome.WCF.WebService.Contract.DataCo" +
        "ntract.PR")]
    [System.SerializableAttribute()]
    public partial class LoginCredentials : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LoginNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private LazyAtHome.Library.Partners.InternalExpressService.OperatorType OperatorTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PasswordField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LoginName {
            get {
                return this.LoginNameField;
            }
            set {
                if ((object.ReferenceEquals(this.LoginNameField, value) != true)) {
                    this.LoginNameField = value;
                    this.RaisePropertyChanged("LoginName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public LazyAtHome.Library.Partners.InternalExpressService.OperatorType OperatorType {
            get {
                return this.OperatorTypeField;
            }
            set {
                if ((this.OperatorTypeField.Equals(value) != true)) {
                    this.OperatorTypeField = value;
                    this.RaisePropertyChanged("OperatorType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Password {
            get {
                return this.PasswordField;
            }
            set {
                if ((object.ReferenceEquals(this.PasswordField, value) != true)) {
                    this.PasswordField = value;
                    this.RaisePropertyChanged("Password");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="OperatorType", Namespace="http://schemas.datacontract.org/2004/07/LazyAtHome.WCF.Common.Contract.Enumerate")]
    public enum OperatorType : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Manage = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Factory = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Partner = 3,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Exp_OrderDC", Namespace="http://schemas.datacontract.org/2004/07/LazyAtHome.WCF.Express.Contract.DataContr" +
        "act")]
    [System.SerializableAttribute()]
    public partial class Exp_OrderDC : LazyAtHome.Core.Infrastructure.WCF.EntityBase, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AddressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int AllotStatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CSRemarkField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal ChargeFeeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> CompleteTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ContactsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int DistrictIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DistrictNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ExpNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime ExpTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MpnoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NodeAddressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> NodeIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NodeNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NodeNoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> OperatorIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OperatorNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> OperatorTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OutNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PackageCountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PackageInfoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int QuickTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int StepField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StepRemarkField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SystemRemarkField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int TransportTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UserRemarkField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Address {
            get {
                return this.AddressField;
            }
            set {
                if ((object.ReferenceEquals(this.AddressField, value) != true)) {
                    this.AddressField = value;
                    this.RaisePropertyChanged("Address");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int AllotStatus {
            get {
                return this.AllotStatusField;
            }
            set {
                if ((this.AllotStatusField.Equals(value) != true)) {
                    this.AllotStatusField = value;
                    this.RaisePropertyChanged("AllotStatus");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CSRemark {
            get {
                return this.CSRemarkField;
            }
            set {
                if ((object.ReferenceEquals(this.CSRemarkField, value) != true)) {
                    this.CSRemarkField = value;
                    this.RaisePropertyChanged("CSRemark");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal ChargeFee {
            get {
                return this.ChargeFeeField;
            }
            set {
                if ((this.ChargeFeeField.Equals(value) != true)) {
                    this.ChargeFeeField = value;
                    this.RaisePropertyChanged("ChargeFee");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> CompleteTime {
            get {
                return this.CompleteTimeField;
            }
            set {
                if ((this.CompleteTimeField.Equals(value) != true)) {
                    this.CompleteTimeField = value;
                    this.RaisePropertyChanged("CompleteTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Contacts {
            get {
                return this.ContactsField;
            }
            set {
                if ((object.ReferenceEquals(this.ContactsField, value) != true)) {
                    this.ContactsField = value;
                    this.RaisePropertyChanged("Contacts");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int DistrictID {
            get {
                return this.DistrictIDField;
            }
            set {
                if ((this.DistrictIDField.Equals(value) != true)) {
                    this.DistrictIDField = value;
                    this.RaisePropertyChanged("DistrictID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DistrictName {
            get {
                return this.DistrictNameField;
            }
            set {
                if ((object.ReferenceEquals(this.DistrictNameField, value) != true)) {
                    this.DistrictNameField = value;
                    this.RaisePropertyChanged("DistrictName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ExpNumber {
            get {
                return this.ExpNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.ExpNumberField, value) != true)) {
                    this.ExpNumberField = value;
                    this.RaisePropertyChanged("ExpNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime ExpTime {
            get {
                return this.ExpTimeField;
            }
            set {
                if ((this.ExpTimeField.Equals(value) != true)) {
                    this.ExpTimeField = value;
                    this.RaisePropertyChanged("ExpTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Mpno {
            get {
                return this.MpnoField;
            }
            set {
                if ((object.ReferenceEquals(this.MpnoField, value) != true)) {
                    this.MpnoField = value;
                    this.RaisePropertyChanged("Mpno");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NodeAddress {
            get {
                return this.NodeAddressField;
            }
            set {
                if ((object.ReferenceEquals(this.NodeAddressField, value) != true)) {
                    this.NodeAddressField = value;
                    this.RaisePropertyChanged("NodeAddress");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> NodeID {
            get {
                return this.NodeIDField;
            }
            set {
                if ((this.NodeIDField.Equals(value) != true)) {
                    this.NodeIDField = value;
                    this.RaisePropertyChanged("NodeID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NodeName {
            get {
                return this.NodeNameField;
            }
            set {
                if ((object.ReferenceEquals(this.NodeNameField, value) != true)) {
                    this.NodeNameField = value;
                    this.RaisePropertyChanged("NodeName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NodeNo {
            get {
                return this.NodeNoField;
            }
            set {
                if ((object.ReferenceEquals(this.NodeNoField, value) != true)) {
                    this.NodeNoField = value;
                    this.RaisePropertyChanged("NodeNo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> OperatorID {
            get {
                return this.OperatorIDField;
            }
            set {
                if ((this.OperatorIDField.Equals(value) != true)) {
                    this.OperatorIDField = value;
                    this.RaisePropertyChanged("OperatorID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OperatorName {
            get {
                return this.OperatorNameField;
            }
            set {
                if ((object.ReferenceEquals(this.OperatorNameField, value) != true)) {
                    this.OperatorNameField = value;
                    this.RaisePropertyChanged("OperatorName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> OperatorTime {
            get {
                return this.OperatorTimeField;
            }
            set {
                if ((this.OperatorTimeField.Equals(value) != true)) {
                    this.OperatorTimeField = value;
                    this.RaisePropertyChanged("OperatorTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OutNumber {
            get {
                return this.OutNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.OutNumberField, value) != true)) {
                    this.OutNumberField = value;
                    this.RaisePropertyChanged("OutNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PackageCount {
            get {
                return this.PackageCountField;
            }
            set {
                if ((this.PackageCountField.Equals(value) != true)) {
                    this.PackageCountField = value;
                    this.RaisePropertyChanged("PackageCount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PackageInfo {
            get {
                return this.PackageInfoField;
            }
            set {
                if ((object.ReferenceEquals(this.PackageInfoField, value) != true)) {
                    this.PackageInfoField = value;
                    this.RaisePropertyChanged("PackageInfo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int QuickType {
            get {
                return this.QuickTypeField;
            }
            set {
                if ((this.QuickTypeField.Equals(value) != true)) {
                    this.QuickTypeField = value;
                    this.RaisePropertyChanged("QuickType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Step {
            get {
                return this.StepField;
            }
            set {
                if ((this.StepField.Equals(value) != true)) {
                    this.StepField = value;
                    this.RaisePropertyChanged("Step");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StepRemark {
            get {
                return this.StepRemarkField;
            }
            set {
                if ((object.ReferenceEquals(this.StepRemarkField, value) != true)) {
                    this.StepRemarkField = value;
                    this.RaisePropertyChanged("StepRemark");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SystemRemark {
            get {
                return this.SystemRemarkField;
            }
            set {
                if ((object.ReferenceEquals(this.SystemRemarkField, value) != true)) {
                    this.SystemRemarkField = value;
                    this.RaisePropertyChanged("SystemRemark");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TransportType {
            get {
                return this.TransportTypeField;
            }
            set {
                if ((this.TransportTypeField.Equals(value) != true)) {
                    this.TransportTypeField = value;
                    this.RaisePropertyChanged("TransportType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserRemark {
            get {
                return this.UserRemarkField;
            }
            set {
                if ((object.ReferenceEquals(this.UserRemarkField, value) != true)) {
                    this.UserRemarkField = value;
                    this.RaisePropertyChanged("UserRemark");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="InternalExpressService.IInternalExpress", SessionMode=System.ServiceModel.SessionMode.Required)]
    public interface IInternalExpress {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInternalExpress/CreateExpressOrder", ReplyAction="http://tempuri.org/IInternalExpress/CreateExpressOrderResponse")]
        LazyAtHome.Core.Infrastructure.WCF.ReturnEntity<bool> CreateExpressOrder(string iOutNumber, int iGetDistrictID, string iGetAddress, string iGetContacts, string iGetMpno, System.DateTime iGetExpTime, int iSendDistrictID, string iSendAddress, string iSendContacts, string iSendMpno, System.DateTime iSendExpTime, string iPackageInfo, int iPackageCount, decimal iChargeFee, string iUserRemark);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInternalExpress/CreateExpressOrder", ReplyAction="http://tempuri.org/IInternalExpress/CreateExpressOrderResponse")]
        System.Threading.Tasks.Task<LazyAtHome.Core.Infrastructure.WCF.ReturnEntity<bool>> CreateExpressOrderAsync(string iOutNumber, int iGetDistrictID, string iGetAddress, string iGetContacts, string iGetMpno, System.DateTime iGetExpTime, int iSendDistrictID, string iSendAddress, string iSendContacts, string iSendMpno, System.DateTime iSendExpTime, string iPackageInfo, int iPackageCount, decimal iChargeFee, string iUserRemark);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInternalExpress/Exp_Order_Create_SendNumber", ReplyAction="http://tempuri.org/IInternalExpress/Exp_Order_Create_SendNumberResponse")]
        LazyAtHome.Core.Infrastructure.WCF.ReturnEntity<LazyAtHome.Library.Partners.InternalExpressService.Exp_OrderDC> Exp_Order_Create_SendNumber(LazyAtHome.Library.Partners.InternalExpressService.LoginCredentials iCredentials, string iOutNumber);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInternalExpress/Exp_Order_Create_SendNumber", ReplyAction="http://tempuri.org/IInternalExpress/Exp_Order_Create_SendNumberResponse")]
        System.Threading.Tasks.Task<LazyAtHome.Core.Infrastructure.WCF.ReturnEntity<LazyAtHome.Library.Partners.InternalExpressService.Exp_OrderDC>> Exp_Order_Create_SendNumberAsync(LazyAtHome.Library.Partners.InternalExpressService.LoginCredentials iCredentials, string iOutNumber);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInternalExpress/Exp_Order_UPDATE_Send_ChargeFee", ReplyAction="http://tempuri.org/IInternalExpress/Exp_Order_UPDATE_Send_ChargeFeeResponse")]
        LazyAtHome.Core.Infrastructure.WCF.ReturnEntity<bool> Exp_Order_UPDATE_Send_ChargeFee(string iOutNumber, decimal iChargeFee, string iPackageInfo, int iPackageCount);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInternalExpress/Exp_Order_UPDATE_Send_ChargeFee", ReplyAction="http://tempuri.org/IInternalExpress/Exp_Order_UPDATE_Send_ChargeFeeResponse")]
        System.Threading.Tasks.Task<LazyAtHome.Core.Infrastructure.WCF.ReturnEntity<bool>> Exp_Order_UPDATE_Send_ChargeFeeAsync(string iOutNumber, decimal iChargeFee, string iPackageInfo, int iPackageCount);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IInternalExpressChannel : LazyAtHome.Library.Partners.InternalExpressService.IInternalExpress, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class InternalExpressClient : System.ServiceModel.ClientBase<LazyAtHome.Library.Partners.InternalExpressService.IInternalExpress>, LazyAtHome.Library.Partners.InternalExpressService.IInternalExpress {
        
        public InternalExpressClient() {
        }
        
        public InternalExpressClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public InternalExpressClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public InternalExpressClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public InternalExpressClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public LazyAtHome.Core.Infrastructure.WCF.ReturnEntity<bool> CreateExpressOrder(string iOutNumber, int iGetDistrictID, string iGetAddress, string iGetContacts, string iGetMpno, System.DateTime iGetExpTime, int iSendDistrictID, string iSendAddress, string iSendContacts, string iSendMpno, System.DateTime iSendExpTime, string iPackageInfo, int iPackageCount, decimal iChargeFee, string iUserRemark) {
            return base.Channel.CreateExpressOrder(iOutNumber, iGetDistrictID, iGetAddress, iGetContacts, iGetMpno, iGetExpTime, iSendDistrictID, iSendAddress, iSendContacts, iSendMpno, iSendExpTime, iPackageInfo, iPackageCount, iChargeFee, iUserRemark);
        }
        
        public System.Threading.Tasks.Task<LazyAtHome.Core.Infrastructure.WCF.ReturnEntity<bool>> CreateExpressOrderAsync(string iOutNumber, int iGetDistrictID, string iGetAddress, string iGetContacts, string iGetMpno, System.DateTime iGetExpTime, int iSendDistrictID, string iSendAddress, string iSendContacts, string iSendMpno, System.DateTime iSendExpTime, string iPackageInfo, int iPackageCount, decimal iChargeFee, string iUserRemark) {
            return base.Channel.CreateExpressOrderAsync(iOutNumber, iGetDistrictID, iGetAddress, iGetContacts, iGetMpno, iGetExpTime, iSendDistrictID, iSendAddress, iSendContacts, iSendMpno, iSendExpTime, iPackageInfo, iPackageCount, iChargeFee, iUserRemark);
        }
        
        public LazyAtHome.Core.Infrastructure.WCF.ReturnEntity<LazyAtHome.Library.Partners.InternalExpressService.Exp_OrderDC> Exp_Order_Create_SendNumber(LazyAtHome.Library.Partners.InternalExpressService.LoginCredentials iCredentials, string iOutNumber) {
            return base.Channel.Exp_Order_Create_SendNumber(iCredentials, iOutNumber);
        }
        
        public System.Threading.Tasks.Task<LazyAtHome.Core.Infrastructure.WCF.ReturnEntity<LazyAtHome.Library.Partners.InternalExpressService.Exp_OrderDC>> Exp_Order_Create_SendNumberAsync(LazyAtHome.Library.Partners.InternalExpressService.LoginCredentials iCredentials, string iOutNumber) {
            return base.Channel.Exp_Order_Create_SendNumberAsync(iCredentials, iOutNumber);
        }
        
        public LazyAtHome.Core.Infrastructure.WCF.ReturnEntity<bool> Exp_Order_UPDATE_Send_ChargeFee(string iOutNumber, decimal iChargeFee, string iPackageInfo, int iPackageCount) {
            return base.Channel.Exp_Order_UPDATE_Send_ChargeFee(iOutNumber, iChargeFee, iPackageInfo, iPackageCount);
        }
        
        public System.Threading.Tasks.Task<LazyAtHome.Core.Infrastructure.WCF.ReturnEntity<bool>> Exp_Order_UPDATE_Send_ChargeFeeAsync(string iOutNumber, decimal iChargeFee, string iPackageInfo, int iPackageCount) {
            return base.Channel.Exp_Order_UPDATE_Send_ChargeFeeAsync(iOutNumber, iChargeFee, iPackageInfo, iPackageCount);
        }
    }
}
