//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18408
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

// 
// 此源代码由 wsdl 自动生成, Version=4.0.30319.33440。
// 
namespace LazyAtHome.Web.WeiXin4.CouponService
{
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;


    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.33440")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name = "CouponServiceImplServiceSoapBinding", Namespace = "http://coupon.landaojia.com/")]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(baseObject))]
    public partial class CouponServiceImplService : System.Web.Services.Protocols.SoapHttpClientProtocol
    {

        private System.Threading.SendOrPostCallback lockSingleCouponOperationCompleted;

        private System.Threading.SendOrPostCallback shareCouponOperationCompleted;

        private System.Threading.SendOrPostCallback useSingleCouponOperationCompleted;

        private System.Threading.SendOrPostCallback getCouponOperationCompleted;

        private System.Threading.SendOrPostCallback lockCouponByAmountOperationCompleted;

        private System.Threading.SendOrPostCallback useCouponByLockRefOperationCompleted;

        private System.Threading.SendOrPostCallback unlockCouponOperationCompleted;

        private System.Threading.SendOrPostCallback useCouponByAmountOperationCompleted;

        private System.Threading.SendOrPostCallback queryCouponOperationCompleted;

        private System.Threading.SendOrPostCallback getNewUserCouponOperationCompleted;
        public static string address = System.Configuration.ConfigurationManager.AppSettings["CouponService"];
        /// <remarks/>
        public CouponServiceImplService()
        {
            this.Url = address;
        }

        /// <remarks/>
        public event lockSingleCouponCompletedEventHandler lockSingleCouponCompleted;

        /// <remarks/>
        public event shareCouponCompletedEventHandler shareCouponCompleted;

        /// <remarks/>
        public event useSingleCouponCompletedEventHandler useSingleCouponCompleted;

        /// <remarks/>
        public event getCouponCompletedEventHandler getCouponCompleted;

        /// <remarks/>
        public event lockCouponByAmountCompletedEventHandler lockCouponByAmountCompleted;

        /// <remarks/>
        public event useCouponByLockRefCompletedEventHandler useCouponByLockRefCompleted;

        /// <remarks/>
        public event unlockCouponCompletedEventHandler unlockCouponCompleted;

        /// <remarks/>
        public event useCouponByAmountCompletedEventHandler useCouponByAmountCompleted;

        /// <remarks/>
        public event queryCouponCompletedEventHandler queryCouponCompleted;

        /// <remarks/>
        public event getNewUserCouponCompletedEventHandler getNewUserCouponCompleted;

        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace = "http://coupon.api.landaojia.com/", ResponseNamespace = "http://coupon.api.landaojia.com/", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public useCouponResult lockSingleCoupon([System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)] string arg0, [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)] string arg1, [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)] string arg2)
        {
            object[] results = this.Invoke("lockSingleCoupon", new object[] {
                        arg0,
                        arg1,
                        arg2});
            return ((useCouponResult)(results[0]));
        }

        /// <remarks/>
        public System.IAsyncResult BeginlockSingleCoupon(string arg0, string arg1, string arg2, System.AsyncCallback callback, object asyncState)
        {
            return this.BeginInvoke("lockSingleCoupon", new object[] {
                        arg0,
                        arg1,
                        arg2}, callback, asyncState);
        }

        /// <remarks/>
        public useCouponResult EndlockSingleCoupon(System.IAsyncResult asyncResult)
        {
            object[] results = this.EndInvoke(asyncResult);
            return ((useCouponResult)(results[0]));
        }

        /// <remarks/>
        public void lockSingleCouponAsync(string arg0, string arg1, string arg2)
        {
            this.lockSingleCouponAsync(arg0, arg1, arg2, null);
        }

        /// <remarks/>
        public void lockSingleCouponAsync(string arg0, string arg1, string arg2, object userState)
        {
            if ((this.lockSingleCouponOperationCompleted == null))
            {
                this.lockSingleCouponOperationCompleted = new System.Threading.SendOrPostCallback(this.OnlockSingleCouponOperationCompleted);
            }
            this.InvokeAsync("lockSingleCoupon", new object[] {
                        arg0,
                        arg1,
                        arg2}, this.lockSingleCouponOperationCompleted, userState);
        }

        private void OnlockSingleCouponOperationCompleted(object arg)
        {
            if ((this.lockSingleCouponCompleted != null))
            {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.lockSingleCouponCompleted(this, new lockSingleCouponCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }

        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace = "http://coupon.api.landaojia.com/", ResponseNamespace = "http://coupon.api.landaojia.com/", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public shareCouponResult shareCoupon([System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)] string arg0, [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)] string arg1)
        {
            object[] results = this.Invoke("shareCoupon", new object[] {
                        arg0,
                        arg1});
            return ((shareCouponResult)(results[0]));
        }

        /// <remarks/>
        public System.IAsyncResult BeginshareCoupon(string arg0, string arg1, System.AsyncCallback callback, object asyncState)
        {
            return this.BeginInvoke("shareCoupon", new object[] {
                        arg0,
                        arg1}, callback, asyncState);
        }

        /// <remarks/>
        public shareCouponResult EndshareCoupon(System.IAsyncResult asyncResult)
        {
            object[] results = this.EndInvoke(asyncResult);
            return ((shareCouponResult)(results[0]));
        }

        /// <remarks/>
        public void shareCouponAsync(string arg0, string arg1)
        {
            this.shareCouponAsync(arg0, arg1, null);
        }

        /// <remarks/>
        public void shareCouponAsync(string arg0, string arg1, object userState)
        {
            if ((this.shareCouponOperationCompleted == null))
            {
                this.shareCouponOperationCompleted = new System.Threading.SendOrPostCallback(this.OnshareCouponOperationCompleted);
            }
            this.InvokeAsync("shareCoupon", new object[] {
                        arg0,
                        arg1}, this.shareCouponOperationCompleted, userState);
        }

        private void OnshareCouponOperationCompleted(object arg)
        {
            if ((this.shareCouponCompleted != null))
            {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.shareCouponCompleted(this, new shareCouponCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }

        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace = "http://coupon.api.landaojia.com/", ResponseNamespace = "http://coupon.api.landaojia.com/", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public useCouponResult useSingleCoupon([System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)] string arg0, [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)] string arg1, [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)] string arg2)
        {
            object[] results = this.Invoke("useSingleCoupon", new object[] {
                        arg0,
                        arg1,
                        arg2});
            return ((useCouponResult)(results[0]));
        }

        /// <remarks/>
        public System.IAsyncResult BeginuseSingleCoupon(string arg0, string arg1, string arg2, System.AsyncCallback callback, object asyncState)
        {
            return this.BeginInvoke("useSingleCoupon", new object[] {
                        arg0,
                        arg1,
                        arg2}, callback, asyncState);
        }

        /// <remarks/>
        public useCouponResult EnduseSingleCoupon(System.IAsyncResult asyncResult)
        {
            object[] results = this.EndInvoke(asyncResult);
            return ((useCouponResult)(results[0]));
        }

        /// <remarks/>
        public void useSingleCouponAsync(string arg0, string arg1, string arg2)
        {
            this.useSingleCouponAsync(arg0, arg1, arg2, null);
        }

        /// <remarks/>
        public void useSingleCouponAsync(string arg0, string arg1, string arg2, object userState)
        {
            if ((this.useSingleCouponOperationCompleted == null))
            {
                this.useSingleCouponOperationCompleted = new System.Threading.SendOrPostCallback(this.OnuseSingleCouponOperationCompleted);
            }
            this.InvokeAsync("useSingleCoupon", new object[] {
                        arg0,
                        arg1,
                        arg2}, this.useSingleCouponOperationCompleted, userState);
        }

        private void OnuseSingleCouponOperationCompleted(object arg)
        {
            if ((this.useSingleCouponCompleted != null))
            {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.useSingleCouponCompleted(this, new useSingleCouponCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }

        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace = "http://coupon.api.landaojia.com/", ResponseNamespace = "http://coupon.api.landaojia.com/", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public getCouponResult getCoupon([System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)] string arg0, [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)] long arg1, [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)] [System.Xml.Serialization.XmlIgnoreAttribute()] bool arg1Specified, [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)] string arg2, [System.Xml.Serialization.XmlArrayAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)] [System.Xml.Serialization.XmlArrayItemAttribute("entry", Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = false)] getCouponEntry[] arg3)
        {
            object[] results = this.Invoke("getCoupon", new object[] {
                        arg0,
                        arg1,
                        arg1Specified,
                        arg2,
                        arg3});
            return ((getCouponResult)(results[0]));
        }

        /// <remarks/>
        public System.IAsyncResult BegingetCoupon(string arg0, long arg1, bool arg1Specified, string arg2, getCouponEntry[] arg3, System.AsyncCallback callback, object asyncState)
        {
            return this.BeginInvoke("getCoupon", new object[] {
                        arg0,
                        arg1,
                        arg1Specified,
                        arg2,
                        arg3}, callback, asyncState);
        }

        /// <remarks/>
        public getCouponResult EndgetCoupon(System.IAsyncResult asyncResult)
        {
            object[] results = this.EndInvoke(asyncResult);
            return ((getCouponResult)(results[0]));
        }

        /// <remarks/>
        public void getCouponAsync(string arg0, long arg1, bool arg1Specified, string arg2, getCouponEntry[] arg3)
        {
            this.getCouponAsync(arg0, arg1, arg1Specified, arg2, arg3, null);
        }

        /// <remarks/>
        public void getCouponAsync(string arg0, long arg1, bool arg1Specified, string arg2, getCouponEntry[] arg3, object userState)
        {
            if ((this.getCouponOperationCompleted == null))
            {
                this.getCouponOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetCouponOperationCompleted);
            }
            this.InvokeAsync("getCoupon", new object[] {
                        arg0,
                        arg1,
                        arg1Specified,
                        arg2,
                        arg3}, this.getCouponOperationCompleted, userState);
        }

        private void OngetCouponOperationCompleted(object arg)
        {
            if ((this.getCouponCompleted != null))
            {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getCouponCompleted(this, new getCouponCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }

        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace = "http://coupon.api.landaojia.com/", ResponseNamespace = "http://coupon.api.landaojia.com/", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public useCouponResult lockCouponByAmount([System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)] string arg0, [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)] decimal arg1, [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)] [System.Xml.Serialization.XmlIgnoreAttribute()] bool arg1Specified, [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)] string arg2)
        {
            object[] results = this.Invoke("lockCouponByAmount", new object[] {
                        arg0,
                        arg1,
                        arg1Specified,
                        arg2});
            return ((useCouponResult)(results[0]));
        }

        /// <remarks/>
        public System.IAsyncResult BeginlockCouponByAmount(string arg0, decimal arg1, bool arg1Specified, string arg2, System.AsyncCallback callback, object asyncState)
        {
            return this.BeginInvoke("lockCouponByAmount", new object[] {
                        arg0,
                        arg1,
                        arg1Specified,
                        arg2}, callback, asyncState);
        }

        /// <remarks/>
        public useCouponResult EndlockCouponByAmount(System.IAsyncResult asyncResult)
        {
            object[] results = this.EndInvoke(asyncResult);
            return ((useCouponResult)(results[0]));
        }

        /// <remarks/>
        public void lockCouponByAmountAsync(string arg0, decimal arg1, bool arg1Specified, string arg2)
        {
            this.lockCouponByAmountAsync(arg0, arg1, arg1Specified, arg2, null);
        }

        /// <remarks/>
        public void lockCouponByAmountAsync(string arg0, decimal arg1, bool arg1Specified, string arg2, object userState)
        {
            if ((this.lockCouponByAmountOperationCompleted == null))
            {
                this.lockCouponByAmountOperationCompleted = new System.Threading.SendOrPostCallback(this.OnlockCouponByAmountOperationCompleted);
            }
            this.InvokeAsync("lockCouponByAmount", new object[] {
                        arg0,
                        arg1,
                        arg1Specified,
                        arg2}, this.lockCouponByAmountOperationCompleted, userState);
        }

        private void OnlockCouponByAmountOperationCompleted(object arg)
        {
            if ((this.lockCouponByAmountCompleted != null))
            {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.lockCouponByAmountCompleted(this, new lockCouponByAmountCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }

        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace = "http://coupon.api.landaojia.com/", ResponseNamespace = "http://coupon.api.landaojia.com/", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public useCouponResult useCouponByLockRef([System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)] string arg0, [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)] string arg1)
        {
            object[] results = this.Invoke("useCouponByLockRef", new object[] {
                        arg0,
                        arg1});
            return ((useCouponResult)(results[0]));
        }

        /// <remarks/>
        public System.IAsyncResult BeginuseCouponByLockRef(string arg0, string arg1, System.AsyncCallback callback, object asyncState)
        {
            return this.BeginInvoke("useCouponByLockRef", new object[] {
                        arg0,
                        arg1}, callback, asyncState);
        }

        /// <remarks/>
        public useCouponResult EnduseCouponByLockRef(System.IAsyncResult asyncResult)
        {
            object[] results = this.EndInvoke(asyncResult);
            return ((useCouponResult)(results[0]));
        }

        /// <remarks/>
        public void useCouponByLockRefAsync(string arg0, string arg1)
        {
            this.useCouponByLockRefAsync(arg0, arg1, null);
        }

        /// <remarks/>
        public void useCouponByLockRefAsync(string arg0, string arg1, object userState)
        {
            if ((this.useCouponByLockRefOperationCompleted == null))
            {
                this.useCouponByLockRefOperationCompleted = new System.Threading.SendOrPostCallback(this.OnuseCouponByLockRefOperationCompleted);
            }
            this.InvokeAsync("useCouponByLockRef", new object[] {
                        arg0,
                        arg1}, this.useCouponByLockRefOperationCompleted, userState);
        }

        private void OnuseCouponByLockRefOperationCompleted(object arg)
        {
            if ((this.useCouponByLockRefCompleted != null))
            {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.useCouponByLockRefCompleted(this, new useCouponByLockRefCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }

        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace = "http://coupon.api.landaojia.com/", ResponseNamespace = "http://coupon.api.landaojia.com/", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public useCouponResult unlockCoupon([System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)] string arg0, [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)] string arg1)
        {
            object[] results = this.Invoke("unlockCoupon", new object[] {
                        arg0,
                        arg1});
            return ((useCouponResult)(results[0]));
        }

        /// <remarks/>
        public System.IAsyncResult BeginunlockCoupon(string arg0, string arg1, System.AsyncCallback callback, object asyncState)
        {
            return this.BeginInvoke("unlockCoupon", new object[] {
                        arg0,
                        arg1}, callback, asyncState);
        }

        /// <remarks/>
        public useCouponResult EndunlockCoupon(System.IAsyncResult asyncResult)
        {
            object[] results = this.EndInvoke(asyncResult);
            return ((useCouponResult)(results[0]));
        }

        /// <remarks/>
        public void unlockCouponAsync(string arg0, string arg1)
        {
            this.unlockCouponAsync(arg0, arg1, null);
        }

        /// <remarks/>
        public void unlockCouponAsync(string arg0, string arg1, object userState)
        {
            if ((this.unlockCouponOperationCompleted == null))
            {
                this.unlockCouponOperationCompleted = new System.Threading.SendOrPostCallback(this.OnunlockCouponOperationCompleted);
            }
            this.InvokeAsync("unlockCoupon", new object[] {
                        arg0,
                        arg1}, this.unlockCouponOperationCompleted, userState);
        }

        private void OnunlockCouponOperationCompleted(object arg)
        {
            if ((this.unlockCouponCompleted != null))
            {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.unlockCouponCompleted(this, new unlockCouponCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }

        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace = "http://coupon.api.landaojia.com/", ResponseNamespace = "http://coupon.api.landaojia.com/", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public useCouponResult useCouponByAmount([System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)] string arg0, [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)] decimal arg1, [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)] [System.Xml.Serialization.XmlIgnoreAttribute()] bool arg1Specified, [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)] string arg2)
        {
            object[] results = this.Invoke("useCouponByAmount", new object[] {
                        arg0,
                        arg1,
                        arg1Specified,
                        arg2});
            return ((useCouponResult)(results[0]));
        }

        /// <remarks/>
        public System.IAsyncResult BeginuseCouponByAmount(string arg0, decimal arg1, bool arg1Specified, string arg2, System.AsyncCallback callback, object asyncState)
        {
            return this.BeginInvoke("useCouponByAmount", new object[] {
                        arg0,
                        arg1,
                        arg1Specified,
                        arg2}, callback, asyncState);
        }

        /// <remarks/>
        public useCouponResult EnduseCouponByAmount(System.IAsyncResult asyncResult)
        {
            object[] results = this.EndInvoke(asyncResult);
            return ((useCouponResult)(results[0]));
        }

        /// <remarks/>
        public void useCouponByAmountAsync(string arg0, decimal arg1, bool arg1Specified, string arg2)
        {
            this.useCouponByAmountAsync(arg0, arg1, arg1Specified, arg2, null);
        }

        /// <remarks/>
        public void useCouponByAmountAsync(string arg0, decimal arg1, bool arg1Specified, string arg2, object userState)
        {
            if ((this.useCouponByAmountOperationCompleted == null))
            {
                this.useCouponByAmountOperationCompleted = new System.Threading.SendOrPostCallback(this.OnuseCouponByAmountOperationCompleted);
            }
            this.InvokeAsync("useCouponByAmount", new object[] {
                        arg0,
                        arg1,
                        arg1Specified,
                        arg2}, this.useCouponByAmountOperationCompleted, userState);
        }

        private void OnuseCouponByAmountOperationCompleted(object arg)
        {
            if ((this.useCouponByAmountCompleted != null))
            {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.useCouponByAmountCompleted(this, new useCouponByAmountCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }

        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace = "http://coupon.api.landaojia.com/", ResponseNamespace = "http://coupon.api.landaojia.com/", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public queryCouponResult queryCoupon([System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)] string arg0)
        {
            object[] results = this.Invoke("queryCoupon", new object[] {
                        arg0});
            return ((queryCouponResult)(results[0]));
        }

        /// <remarks/>
        public System.IAsyncResult BeginqueryCoupon(string arg0, System.AsyncCallback callback, object asyncState)
        {
            return this.BeginInvoke("queryCoupon", new object[] {
                        arg0}, callback, asyncState);
        }

        /// <remarks/>
        public queryCouponResult EndqueryCoupon(System.IAsyncResult asyncResult)
        {
            object[] results = this.EndInvoke(asyncResult);
            return ((queryCouponResult)(results[0]));
        }

        /// <remarks/>
        public void queryCouponAsync(string arg0)
        {
            this.queryCouponAsync(arg0, null);
        }

        /// <remarks/>
        public void queryCouponAsync(string arg0, object userState)
        {
            if ((this.queryCouponOperationCompleted == null))
            {
                this.queryCouponOperationCompleted = new System.Threading.SendOrPostCallback(this.OnqueryCouponOperationCompleted);
            }
            this.InvokeAsync("queryCoupon", new object[] {
                        arg0}, this.queryCouponOperationCompleted, userState);
        }

        private void OnqueryCouponOperationCompleted(object arg)
        {
            if ((this.queryCouponCompleted != null))
            {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.queryCouponCompleted(this, new queryCouponCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }

        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace = "http://coupon.api.landaojia.com/", ResponseNamespace = "http://coupon.api.landaojia.com/", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public getCouponResult getNewUserCoupon([System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)] string arg0, [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)] string arg1)
        {
            object[] results = this.Invoke("getNewUserCoupon", new object[] {
                        arg0,
                        arg1});
            return ((getCouponResult)(results[0]));
        }

        /// <remarks/>
        public System.IAsyncResult BegingetNewUserCoupon(string arg0, string arg1, System.AsyncCallback callback, object asyncState)
        {
            return this.BeginInvoke("getNewUserCoupon", new object[] {
                        arg0,
                        arg1}, callback, asyncState);
        }

        /// <remarks/>
        public getCouponResult EndgetNewUserCoupon(System.IAsyncResult asyncResult)
        {
            object[] results = this.EndInvoke(asyncResult);
            return ((getCouponResult)(results[0]));
        }

        /// <remarks/>
        public void getNewUserCouponAsync(string arg0, string arg1)
        {
            this.getNewUserCouponAsync(arg0, arg1, null);
        }

        /// <remarks/>
        public void getNewUserCouponAsync(string arg0, string arg1, object userState)
        {
            if ((this.getNewUserCouponOperationCompleted == null))
            {
                this.getNewUserCouponOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetNewUserCouponOperationCompleted);
            }
            this.InvokeAsync("getNewUserCoupon", new object[] {
                        arg0,
                        arg1}, this.getNewUserCouponOperationCompleted, userState);
        }

        private void OngetNewUserCouponOperationCompleted(object arg)
        {
            if ((this.getNewUserCouponCompleted != null))
            {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getNewUserCouponCompleted(this, new getNewUserCouponCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }

        /// <remarks/>
        public new void CancelAsync(object userState)
        {
            base.CancelAsync(userState);
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://coupon.api.landaojia.com/")]
    public partial class useCouponResult : result
    {

        private string extRefField;

        private string refField;

        private string unameField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string extRef
        {
            get
            {
                return this.extRefField;
            }
            set
            {
                this.extRefField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string @ref
        {
            get
            {
                return this.refField;
            }
            set
            {
                this.refField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string uname
        {
            get
            {
                return this.unameField;
            }
            set
            {
                this.unameField = value;
            }
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(queryCouponResult))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(getCouponResult))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(shareCouponResult))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(useCouponResult))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://coupon.api.landaojia.com/")]
    public partial class result : baseObject
    {

        private int resultCodeField;

        private bool resultCodeFieldSpecified;

        private string resultMsgField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int resultCode
        {
            get
            {
                return this.resultCodeField;
            }
            set
            {
                this.resultCodeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool resultCodeSpecified
        {
            get
            {
                return this.resultCodeFieldSpecified;
            }
            set
            {
                this.resultCodeFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string resultMsg
        {
            get
            {
                return this.resultMsgField;
            }
            set
            {
                this.resultMsgField = value;
            }
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(couponDetail))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(couponSum))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(result))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(queryCouponResult))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(getCouponResult))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(shareCouponResult))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(useCouponResult))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://coupon.api.landaojia.com/")]
    public partial class baseObject
    {
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://coupon.api.landaojia.com/")]
    public partial class couponDetail : baseObject
    {

        private int combinableField;

        private bool combinableFieldSpecified;

        private string couponNoField;

        private decimal denominationField;

        private bool denominationFieldSpecified;

        private System.DateTime expDateField;

        private bool expDateFieldSpecified;

        private string nameField;

        private int statusField;

        private bool statusFieldSpecified;

        private int typeField;

        private bool typeFieldSpecified;

        private System.DateTime validDateField;

        private bool validDateFieldSpecified;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int combinable
        {
            get
            {
                return this.combinableField;
            }
            set
            {
                this.combinableField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool combinableSpecified
        {
            get
            {
                return this.combinableFieldSpecified;
            }
            set
            {
                this.combinableFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string couponNo
        {
            get
            {
                return this.couponNoField;
            }
            set
            {
                this.couponNoField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal denomination
        {
            get
            {
                return this.denominationField;
            }
            set
            {
                this.denominationField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool denominationSpecified
        {
            get
            {
                return this.denominationFieldSpecified;
            }
            set
            {
                this.denominationFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public System.DateTime expDate
        {
            get
            {
                return this.expDateField;
            }
            set
            {
                this.expDateField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool expDateSpecified
        {
            get
            {
                return this.expDateFieldSpecified;
            }
            set
            {
                this.expDateFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int status
        {
            get
            {
                return this.statusField;
            }
            set
            {
                this.statusField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool statusSpecified
        {
            get
            {
                return this.statusFieldSpecified;
            }
            set
            {
                this.statusFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int type
        {
            get
            {
                return this.typeField;
            }
            set
            {
                this.typeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool typeSpecified
        {
            get
            {
                return this.typeFieldSpecified;
            }
            set
            {
                this.typeFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public System.DateTime validDate
        {
            get
            {
                return this.validDateField;
            }
            set
            {
                this.validDateField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool validDateSpecified
        {
            get
            {
                return this.validDateFieldSpecified;
            }
            set
            {
                this.validDateFieldSpecified = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://coupon.api.landaojia.com/")]
    public partial class couponSum : baseObject
    {

        private string couponNoField;

        private decimal denominationField;

        private bool denominationFieldSpecified;

        private System.DateTime expDateField;

        private bool expDateFieldSpecified;

        private string nameField;

        private int typeField;

        private bool typeFieldSpecified;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string couponNo
        {
            get
            {
                return this.couponNoField;
            }
            set
            {
                this.couponNoField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal denomination
        {
            get
            {
                return this.denominationField;
            }
            set
            {
                this.denominationField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool denominationSpecified
        {
            get
            {
                return this.denominationFieldSpecified;
            }
            set
            {
                this.denominationFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public System.DateTime expDate
        {
            get
            {
                return this.expDateField;
            }
            set
            {
                this.expDateField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool expDateSpecified
        {
            get
            {
                return this.expDateFieldSpecified;
            }
            set
            {
                this.expDateFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int type
        {
            get
            {
                return this.typeField;
            }
            set
            {
                this.typeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool typeSpecified
        {
            get
            {
                return this.typeFieldSpecified;
            }
            set
            {
                this.typeFieldSpecified = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://coupon.api.landaojia.com/")]
    public partial class queryCouponResult : result
    {

        private couponSum[] couponSumField;

        private couponDetail[] couponsField;

        private string unameField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("couponSum", Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = true)]
        public couponSum[] couponSum
        {
            get
            {
                return this.couponSumField;
            }
            set
            {
                this.couponSumField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("coupons", Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = true)]
        public couponDetail[] coupons
        {
            get
            {
                return this.couponsField;
            }
            set
            {
                this.couponsField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string uname
        {
            get
            {
                return this.unameField;
            }
            set
            {
                this.unameField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://coupon.api.landaojia.com/")]
    public partial class getCouponResult : result
    {

        private decimal amountField;

        private bool amountFieldSpecified;

        private string couponNoField;

        private long marketingIdField;

        private bool marketingIdFieldSpecified;

        private string unameField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal amount
        {
            get
            {
                return this.amountField;
            }
            set
            {
                this.amountField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool amountSpecified
        {
            get
            {
                return this.amountFieldSpecified;
            }
            set
            {
                this.amountFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string couponNo
        {
            get
            {
                return this.couponNoField;
            }
            set
            {
                this.couponNoField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long marketingId
        {
            get
            {
                return this.marketingIdField;
            }
            set
            {
                this.marketingIdField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool marketingIdSpecified
        {
            get
            {
                return this.marketingIdFieldSpecified;
            }
            set
            {
                this.marketingIdFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string uname
        {
            get
            {
                return this.unameField;
            }
            set
            {
                this.unameField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://coupon.api.landaojia.com/")]
    public partial class shareCouponResult : result
    {

        private string shareIdField;

        private string unameField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string shareId
        {
            get
            {
                return this.shareIdField;
            }
            set
            {
                this.shareIdField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string uname
        {
            get
            {
                return this.unameField;
            }
            set
            {
                this.unameField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://coupon.api.landaojia.com/")]
    public partial class getCouponEntry
    {

        private string keyField;

        private string valueField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string key
        {
            get
            {
                return this.keyField;
            }
            set
            {
                this.keyField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.33440")]
    public delegate void lockSingleCouponCompletedEventHandler(object sender, lockSingleCouponCompletedEventArgs e);

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.33440")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class lockSingleCouponCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
    {

        private object[] results;

        internal lockSingleCouponCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) :
            base(exception, cancelled, userState)
        {
            this.results = results;
        }

        /// <remarks/>
        public useCouponResult Result
        {
            get
            {
                this.RaiseExceptionIfNecessary();
                return ((useCouponResult)(this.results[0]));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.33440")]
    public delegate void shareCouponCompletedEventHandler(object sender, shareCouponCompletedEventArgs e);

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.33440")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class shareCouponCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
    {

        private object[] results;

        internal shareCouponCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) :
            base(exception, cancelled, userState)
        {
            this.results = results;
        }

        /// <remarks/>
        public shareCouponResult Result
        {
            get
            {
                this.RaiseExceptionIfNecessary();
                return ((shareCouponResult)(this.results[0]));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.33440")]
    public delegate void useSingleCouponCompletedEventHandler(object sender, useSingleCouponCompletedEventArgs e);

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.33440")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class useSingleCouponCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
    {

        private object[] results;

        internal useSingleCouponCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) :
            base(exception, cancelled, userState)
        {
            this.results = results;
        }

        /// <remarks/>
        public useCouponResult Result
        {
            get
            {
                this.RaiseExceptionIfNecessary();
                return ((useCouponResult)(this.results[0]));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.33440")]
    public delegate void getCouponCompletedEventHandler(object sender, getCouponCompletedEventArgs e);

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.33440")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getCouponCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
    {

        private object[] results;

        internal getCouponCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) :
            base(exception, cancelled, userState)
        {
            this.results = results;
        }

        /// <remarks/>
        public getCouponResult Result
        {
            get
            {
                this.RaiseExceptionIfNecessary();
                return ((getCouponResult)(this.results[0]));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.33440")]
    public delegate void lockCouponByAmountCompletedEventHandler(object sender, lockCouponByAmountCompletedEventArgs e);

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.33440")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class lockCouponByAmountCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
    {

        private object[] results;

        internal lockCouponByAmountCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) :
            base(exception, cancelled, userState)
        {
            this.results = results;
        }

        /// <remarks/>
        public useCouponResult Result
        {
            get
            {
                this.RaiseExceptionIfNecessary();
                return ((useCouponResult)(this.results[0]));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.33440")]
    public delegate void useCouponByLockRefCompletedEventHandler(object sender, useCouponByLockRefCompletedEventArgs e);

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.33440")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class useCouponByLockRefCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
    {

        private object[] results;

        internal useCouponByLockRefCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) :
            base(exception, cancelled, userState)
        {
            this.results = results;
        }

        /// <remarks/>
        public useCouponResult Result
        {
            get
            {
                this.RaiseExceptionIfNecessary();
                return ((useCouponResult)(this.results[0]));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.33440")]
    public delegate void unlockCouponCompletedEventHandler(object sender, unlockCouponCompletedEventArgs e);

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.33440")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class unlockCouponCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
    {

        private object[] results;

        internal unlockCouponCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) :
            base(exception, cancelled, userState)
        {
            this.results = results;
        }

        /// <remarks/>
        public useCouponResult Result
        {
            get
            {
                this.RaiseExceptionIfNecessary();
                return ((useCouponResult)(this.results[0]));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.33440")]
    public delegate void useCouponByAmountCompletedEventHandler(object sender, useCouponByAmountCompletedEventArgs e);

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.33440")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class useCouponByAmountCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
    {

        private object[] results;

        internal useCouponByAmountCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) :
            base(exception, cancelled, userState)
        {
            this.results = results;
        }

        /// <remarks/>
        public useCouponResult Result
        {
            get
            {
                this.RaiseExceptionIfNecessary();
                return ((useCouponResult)(this.results[0]));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.33440")]
    public delegate void queryCouponCompletedEventHandler(object sender, queryCouponCompletedEventArgs e);

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.33440")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class queryCouponCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
    {

        private object[] results;

        internal queryCouponCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) :
            base(exception, cancelled, userState)
        {
            this.results = results;
        }

        /// <remarks/>
        public queryCouponResult Result
        {
            get
            {
                this.RaiseExceptionIfNecessary();
                return ((queryCouponResult)(this.results[0]));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.33440")]
    public delegate void getNewUserCouponCompletedEventHandler(object sender, getNewUserCouponCompletedEventArgs e);

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.33440")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getNewUserCouponCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
    {

        private object[] results;

        internal getNewUserCouponCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) :
            base(exception, cancelled, userState)
        {
            this.results = results;
        }

        /// <remarks/>
        public getCouponResult Result
        {
            get
            {
                this.RaiseExceptionIfNecessary();
                return ((getCouponResult)(this.results[0]));
            }
        }
    }
}
