//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18408
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

// 
// 此源代码由 wsdl 自动生成, Version=4.0.30319.33440。
// 
namespace LazyAtHome.Web.WeiXin4.MarketService
{
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;


    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.33440")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name = "MarketingServiceImplServiceSoapBinding", Namespace = "http://coupon.landaojia.com/")]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(queryMarketingDetailResponse))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(queryMarketingDetail))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(queryMarketingResponse))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(queryMarketing))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(baseObject))]
    public partial class MarketingServiceImplService : System.Web.Services.Protocols.SoapHttpClientProtocol
    {

        private System.Threading.SendOrPostCallback queryMarketingOperationCompleted;

        private System.Threading.SendOrPostCallback queryMarketingDetailOperationCompleted;
        public static string address = System.Configuration.ConfigurationManager.AppSettings["MarketingService"];
        /// <remarks/>
        public MarketingServiceImplService()
        {
            this.Url = address;
        }

        /// <remarks/>
        public event queryMarketingCompletedEventHandler queryMarketingCompleted;

        /// <remarks/>
        public event queryMarketingDetailCompletedEventHandler queryMarketingDetailCompleted;

        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace = "http://coupon.api.landaojia.com/", ResponseNamespace = "http://coupon.api.landaojia.com/", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public queryMarketingResult queryMarketing([System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)] string arg0, [System.Xml.Serialization.XmlArrayAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)] [System.Xml.Serialization.XmlArrayItemAttribute("entry", Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = false)] queryMarketingEntry[] arg1)
        {
            object[] results = this.Invoke("queryMarketing", new object[] {
                        arg0,
                        arg1});
            return ((queryMarketingResult)(results[0]));
        }

        /// <remarks/>
        public System.IAsyncResult BeginqueryMarketing(string arg0, queryMarketingEntry[] arg1, System.AsyncCallback callback, object asyncState)
        {
            return this.BeginInvoke("queryMarketing", new object[] {
                        arg0,
                        arg1}, callback, asyncState);
        }

        /// <remarks/>
        public queryMarketingResult EndqueryMarketing(System.IAsyncResult asyncResult)
        {
            object[] results = this.EndInvoke(asyncResult);
            return ((queryMarketingResult)(results[0]));
        }

        /// <remarks/>
        public void queryMarketingAsync(string arg0, queryMarketingEntry[] arg1)
        {
            this.queryMarketingAsync(arg0, arg1, null);
        }

        /// <remarks/>
        public void queryMarketingAsync(string arg0, queryMarketingEntry[] arg1, object userState)
        {
            if ((this.queryMarketingOperationCompleted == null))
            {
                this.queryMarketingOperationCompleted = new System.Threading.SendOrPostCallback(this.OnqueryMarketingOperationCompleted);
            }
            this.InvokeAsync("queryMarketing", new object[] {
                        arg0,
                        arg1}, this.queryMarketingOperationCompleted, userState);
        }

        private void OnqueryMarketingOperationCompleted(object arg)
        {
            if ((this.queryMarketingCompleted != null))
            {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.queryMarketingCompleted(this, new queryMarketingCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }

        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace = "http://coupon.api.landaojia.com/", ResponseNamespace = "http://coupon.api.landaojia.com/", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public marketingDetail queryMarketingDetail([System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)] long arg0, [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)] [System.Xml.Serialization.XmlIgnoreAttribute()] bool arg0Specified, [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)] string arg1, [System.Xml.Serialization.XmlArrayAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)] [System.Xml.Serialization.XmlArrayItemAttribute("entry", Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = false)] queryMarketingDetailEntry[] arg2)
        {
            object[] results = this.Invoke("queryMarketingDetail", new object[] {
                        arg0,
                        arg0Specified,
                        arg1,
                        arg2});
            return ((marketingDetail)(results[0]));
        }

        /// <remarks/>
        public System.IAsyncResult BeginqueryMarketingDetail(long arg0, bool arg0Specified, string arg1, queryMarketingDetailEntry[] arg2, System.AsyncCallback callback, object asyncState)
        {
            return this.BeginInvoke("queryMarketingDetail", new object[] {
                        arg0,
                        arg0Specified,
                        arg1,
                        arg2}, callback, asyncState);
        }

        /// <remarks/>
        public marketingDetail EndqueryMarketingDetail(System.IAsyncResult asyncResult)
        {
            object[] results = this.EndInvoke(asyncResult);
            return ((marketingDetail)(results[0]));
        }

        /// <remarks/>
        public void queryMarketingDetailAsync(long arg0, bool arg0Specified, string arg1, queryMarketingDetailEntry[] arg2)
        {
            this.queryMarketingDetailAsync(arg0, arg0Specified, arg1, arg2, null);
        }

        /// <remarks/>
        public void queryMarketingDetailAsync(long arg0, bool arg0Specified, string arg1, queryMarketingDetailEntry[] arg2, object userState)
        {
            if ((this.queryMarketingDetailOperationCompleted == null))
            {
                this.queryMarketingDetailOperationCompleted = new System.Threading.SendOrPostCallback(this.OnqueryMarketingDetailOperationCompleted);
            }
            this.InvokeAsync("queryMarketingDetail", new object[] {
                        arg0,
                        arg0Specified,
                        arg1,
                        arg2}, this.queryMarketingDetailOperationCompleted, userState);
        }

        private void OnqueryMarketingDetailOperationCompleted(object arg)
        {
            if ((this.queryMarketingDetailCompleted != null))
            {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.queryMarketingDetailCompleted(this, new queryMarketingDetailCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }

        /// <remarks/>
        public new void CancelAsync(object userState)
        {
            base.CancelAsync(userState);
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://coupon.api.landaojia.com/")]
    public partial class queryMarketingEntry
    {

        private string keyField;

        private string valueField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string key
        {
            get
            {
                return this.keyField;
            }
            set
            {
                this.keyField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://coupon.api.landaojia.com/")]
    public partial class queryMarketingDetailResponse
    {

        private marketingDetail returnField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public marketingDetail @return
        {
            get
            {
                return this.returnField;
            }
            set
            {
                this.returnField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://coupon.api.landaojia.com/")]
    public partial class marketingDetail : baseObject
    {

        private bool couponFlagField;

        private string descriptionField;

        private long marketingIdField;

        private bool marketingIdFieldSpecified;

        private string marketingUrlField;

        private string nameField;

        private string unameField;

        private marketingDetailEntry[] userMarketingInfoField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool couponFlag
        {
            get
            {
                return this.couponFlagField;
            }
            set
            {
                this.couponFlagField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string description
        {
            get
            {
                return this.descriptionField;
            }
            set
            {
                this.descriptionField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long marketingId
        {
            get
            {
                return this.marketingIdField;
            }
            set
            {
                this.marketingIdField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool marketingIdSpecified
        {
            get
            {
                return this.marketingIdFieldSpecified;
            }
            set
            {
                this.marketingIdFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string marketingUrl
        {
            get
            {
                return this.marketingUrlField;
            }
            set
            {
                this.marketingUrlField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string uname
        {
            get
            {
                return this.unameField;
            }
            set
            {
                this.unameField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("entry", Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = false)]
        public marketingDetailEntry[] userMarketingInfo
        {
            get
            {
                return this.userMarketingInfoField;
            }
            set
            {
                this.userMarketingInfoField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://coupon.api.landaojia.com/")]
    public partial class marketingDetailEntry
    {

        private string keyField;

        private object valueField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string key
        {
            get
            {
                return this.keyField;
            }
            set
            {
                this.keyField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public object value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(marketingDetail))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(result))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(queryMarketingResult))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://coupon.api.landaojia.com/")]
    public partial class baseObject
    {
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(queryMarketingResult))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://coupon.api.landaojia.com/")]
    public partial class result : baseObject
    {

        private int resultCodeField;

        private bool resultCodeFieldSpecified;

        private string resultMsgField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int resultCode
        {
            get
            {
                return this.resultCodeField;
            }
            set
            {
                this.resultCodeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool resultCodeSpecified
        {
            get
            {
                return this.resultCodeFieldSpecified;
            }
            set
            {
                this.resultCodeFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string resultMsg
        {
            get
            {
                return this.resultMsgField;
            }
            set
            {
                this.resultMsgField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://coupon.api.landaojia.com/")]
    public partial class queryMarketingResult : result
    {

        private marketingDetail[] marketingsField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("marketings", Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = true)]
        public marketingDetail[] marketings
        {
            get
            {
                return this.marketingsField;
            }
            set
            {
                this.marketingsField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://coupon.api.landaojia.com/")]
    public partial class queryMarketingDetail
    {

        private long arg0Field;

        private bool arg0FieldSpecified;

        private string arg1Field;

        private queryMarketingDetailEntry[] arg2Field;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long arg0
        {
            get
            {
                return this.arg0Field;
            }
            set
            {
                this.arg0Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool arg0Specified
        {
            get
            {
                return this.arg0FieldSpecified;
            }
            set
            {
                this.arg0FieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string arg1
        {
            get
            {
                return this.arg1Field;
            }
            set
            {
                this.arg1Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("entry", Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = false)]
        public queryMarketingDetailEntry[] arg2
        {
            get
            {
                return this.arg2Field;
            }
            set
            {
                this.arg2Field = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://coupon.api.landaojia.com/")]
    public partial class queryMarketingDetailEntry
    {

        private string keyField;

        private string valueField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string key
        {
            get
            {
                return this.keyField;
            }
            set
            {
                this.keyField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://coupon.api.landaojia.com/")]
    public partial class queryMarketingResponse
    {

        private queryMarketingResult returnField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public queryMarketingResult @return
        {
            get
            {
                return this.returnField;
            }
            set
            {
                this.returnField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://coupon.api.landaojia.com/")]
    public partial class queryMarketing
    {

        private string arg0Field;

        private queryMarketingEntry[] arg1Field;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string arg0
        {
            get
            {
                return this.arg0Field;
            }
            set
            {
                this.arg0Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("entry", Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = false)]
        public queryMarketingEntry[] arg1
        {
            get
            {
                return this.arg1Field;
            }
            set
            {
                this.arg1Field = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.33440")]
    public delegate void queryMarketingCompletedEventHandler(object sender, queryMarketingCompletedEventArgs e);

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.33440")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class queryMarketingCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
    {

        private object[] results;

        internal queryMarketingCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) :
            base(exception, cancelled, userState)
        {
            this.results = results;
        }

        /// <remarks/>
        public queryMarketingResult Result
        {
            get
            {
                this.RaiseExceptionIfNecessary();
                return ((queryMarketingResult)(this.results[0]));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.33440")]
    public delegate void queryMarketingDetailCompletedEventHandler(object sender, queryMarketingDetailCompletedEventArgs e);

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.33440")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class queryMarketingDetailCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
    {

        private object[] results;

        internal queryMarketingDetailCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) :
            base(exception, cancelled, userState)
        {
            this.results = results;
        }

        /// <remarks/>
        public marketingDetail Result
        {
            get
            {
                this.RaiseExceptionIfNecessary();
                return ((marketingDetail)(this.results[0]));
            }
        }
    }
}
