package com.landaojia.washclothes.userappserver.service.sms.jianzhou.ws;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.0.4
 * 2015-03-16T15:53:48.254+08:00
 * Generated source version: 3.0.4
 * 
 */
@WebServiceClient(name = "BusinessServiceService", 
                  wsdlLocation = "http://www.jianzhou.sh.cn/JianzhouSMSWSServer/services/BusinessService?wsdl",
                  targetNamespace = "http://service.nineorange.com") 
public class BusinessServiceService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://service.nineorange.com", "BusinessServiceService");
    public final static QName BusinessServicePort = new QName("http://service.nineorange.com", "BusinessServicePort");
    static {
        URL url = null;
        try {
            url = new URL("http://www.jianzhou.sh.cn/JianzhouSMSWSServer/services/BusinessService?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(BusinessServiceService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://www.jianzhou.sh.cn/JianzhouSMSWSServer/services/BusinessService?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public BusinessServiceService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public BusinessServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public BusinessServiceService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public BusinessServiceService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public BusinessServiceService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public BusinessServiceService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    

    /**
     *
     * @return
     *     returns BusinessService
     */
    @WebEndpoint(name = "BusinessServicePort")
    public BusinessService getBusinessServicePort() {
        return super.getPort(BusinessServicePort, BusinessService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns BusinessService
     */
    @WebEndpoint(name = "BusinessServicePort")
    public BusinessService getBusinessServicePort(WebServiceFeature... features) {
        return super.getPort(BusinessServicePort, BusinessService.class, features);
    }

}
